Update patch set 5
Patch Set 5: Test-x86-1

MCKERNEL : mckernel-refs-changes-88-510788-1-?
IHK      : ihk-refs-changes-88-510788-1-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/510788/1 // 6e6d2b80044159945350fa4741e265246afe6880
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_refs-changes-88-510788-1_submodule
START : 20210216153938
END   : 20210216154010

+++ dirname /work/mcktest/bin/autobuild.sh
++ cd /work/mcktest/bin/..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ pwd
+ CWD=/
++ dirname /work/mcktest/bin/autobuild.sh
+ cd /work/mcktest/bin
+ . ./config.sh
+++ shopt -po xtrace
++ tracestate='set -o xtrace'
++ echo set -o xtrace
++ grep -q -
++ set +x
+ export BINDIR=
+ BINDIR=
+ bash -x ./wget-postpeta.sh mckernel refs-changes-88-510788-1
++ pwd
+ CWD=/work/mcktest/bin
+++ dirname ./wget-postpeta.sh
++ cd ./..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ dirname ./wget-postpeta.sh
+ cd .
+ . ./config.sh
+++ shopt -po xtrace
++ tracestate='set -o xtrace'
++ echo set -o xtrace
++ grep -q -
++ set +x
+ forwatchgerrit=0
+ REPO=mckernel
+ BRANCH=refs-changes-88-510788-1
+ case "$BRANCH" in
+ remote_type=gerrit-git
+ PATHSPEC=refs/changes/88/510788/1
+ '[' /work/mcktest/work_refs-changes-88-510788-1_submodule/src == '' ']'
+ '[' mckernel == '' ']'
+ DEST=mckernel
+ [[ -d /work/mcktest/work_refs-changes-88-510788-1_submodule/src ]]
+ mkdir /work/mcktest/work_refs-changes-88-510788-1_submodule/src
+ rm -rf '/work/mcktest/work_refs-changes-88-510788-1_submodule/src/mckernel-*'
+ case $NODETYPE in
+ case $remote_type in
+ pushd /work/mcktest/git
/work/mcktest/git /work/mcktest/bin
+ sudo -u mcktest rm -rf mckernel
+ sudo -u mcktest git clone ssh://riken-syssoft-gerrit@review.gerrithub.io/RIKEN-SysSoft/mckernel
Cloning into 'mckernel'...
Total 33104 (delta 21340), reused 32583 (delta 21340)
+ cd mckernel
+ sudo -u mcktest git fetch origin refs/changes/88/510788/1
Total 9 (delta 8), reused 9 (delta 8)
From ssh://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/88/510788/1 -> FETCH_HEAD
++ sudo -u mcktest git rev-parse FETCH_HEAD
+ COMMIT=6e6d2b80044159945350fa4741e265246afe6880
+ DEST=mckernel-refs-changes-88-510788-1-6e6d2b80044159945350fa4741e265246afe6880
+ popd
/work/mcktest/bin
+ '[' 0 -ne 0 ']'
+ '[' 0 -eq 1 ']'
+ case $remote_type in
+ mkdir /work/mcktest/work_refs-changes-88-510788-1_submodule/src/mckernel-refs-changes-88-510788-1-6e6d2b80044159945350fa4741e265246afe6880
+ cd /work/mcktest/work_refs-changes-88-510788-1_submodule/src/mckernel-refs-changes-88-510788-1-6e6d2b80044159945350fa4741e265246afe6880
+ GIT_DIR=/work/mcktest/git/mckernel/.git
+ git reset --hard 6e6d2b80044159945350fa4741e265246afe6880
HEAD is now at 6e6d2b8 uti: futex: McKernel waker sends IPI to Linux waiter CPU
+ GIT_DIR=/work/mcktest/git/mckernel/.git
+ git submodule update --init
From https://github.com/bgerofi/libdwarf
 * [new branch]      alt        -> origin/alt
 * [new branch]      exprloc    -> origin/exprloc
 * [new branch]      master     -> origin/master
 * [new branch]      suppress_warnings -> origin/suppress_warnings
Submodule path 'executer/user/lib/libdwarf/libdwarf': checked out 'ab9230b2b8aa66a3d1d52e4be11fca17a3b63753'
From https://github.com/RIKEN-SysSoft/ihk
 * [new branch]      a64fx      -> origin/a64fx
 * [new branch]      add_ihklib_tests5 -> origin/add_ihklib_tests5
 * [new branch]      bbtest5b_merge18 -> origin/bbtest5b_merge18
 * [new branch]      bbtest5b_merge22 -> origin/bbtest5b_merge22
 * [new branch]      dev+fix    -> origin/dev+fix
 * [new branch]      dev+fix+pkm -> origin/dev+fix+pkm
 * [new branch]      dev+fix-riken2 -> origin/dev+fix-riken2
 * [new branch]      development -> origin/development
 * [new branch]      development+a64fx-rebased -> origin/development+a64fx-rebased
 * [new branch]      development+a64fx-rebased+fullview -> origin/development+a64fx-rebased+fullview
 * [new branch]      development+a64fx-rebased+tofu -> origin/development+a64fx-rebased+tofu
 * [new branch]      development+apollo -> origin/development+apollo
 * [new branch]      development+apollo+a64fx -> origin/development+apollo+a64fx
 * [new branch]      development+apollo+a64fx+fullview -> origin/development+apollo+a64fx+fullview
 * [new branch]      development+apollo+a64fx2 -> origin/development+apollo+a64fx2
 * [new branch]      development+gerrithubrefs -> origin/development+gerrithubrefs
 * [new branch]      development+unimap+hfi -> origin/development+unimap+hfi
 * [new branch]      development+unimap+uti_extract78 -> origin/development+unimap+uti_extract78
 * [new branch]      fix_ihklib -> origin/fix_ihklib
 * [new branch]      fix_remote_PF -> origin/fix_remote_PF
 * [new branch]      fix_uti_kstack2 -> origin/fix_uti_kstack2
 * [new branch]      fix_xpmem2 -> origin/fix_xpmem2
 * [new branch]      for_uti_test -> origin/for_uti_test
 * [new branch]      ihk_api_bbtest6 -> origin/ihk_api_bbtest6
 * [new branch]      ihk_api_bbtest7 -> origin/ihk_api_bbtest7
 * [new branch]      master     -> origin/master
 * [new branch]      merge-no-full-view2 -> origin/merge-no-full-view2
 * [new branch]      postk_master -> origin/postk_master
 * [new branch]      rebase3.1  -> origin/rebase3.1
 * [new branch]      rebase3.2  -> origin/rebase3.2
 * [new branch]      rebase3.3  -> origin/rebase3.3
 * [new branch]      rebase8.4  -> origin/rebase8.4
 * [new branch]      rebase8.5  -> origin/rebase8.5
 * [new branch]      rebase8.6  -> origin/rebase8.6
 * [new branch]      tofu_fix_xpmem -> origin/tofu_fix_xpmem
 * [new branch]      wip_ihklib -> origin/wip_ihklib
 * [new tag]         0.4.0      -> 0.4.0
 * [new tag]         0.9.0      -> 0.9.0
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.1.1      -> 1.1.1
 * [new tag]         1.1.2      -> 1.1.2
 * [new tag]         1.1.3      -> 1.1.3
 * [new tag]         1.2.0      -> 1.2.0
 * [new tag]         1.2.1      -> 1.2.1
 * [new tag]         1.2.2      -> 1.2.2
 * [new tag]         1.2.3      -> 1.2.3
 * [new tag]         1.2.4      -> 1.2.4
 * [new tag]         1.2.5      -> 1.2.5
 * [new tag]         1.2.6      -> 1.2.6
 * [new tag]         1.3.0      -> 1.3.0
 * [new tag]         1.4.0      -> 1.4.0
 * [new tag]         1.5.0      -> 1.5.0
 * [new tag]         1.5.0-knl+hfi -> 1.5.0-knl+hfi
 * [new tag]         1.5.1      -> 1.5.1
 * [new tag]         1.5.1-rc1  -> 1.5.1-rc1
 * [new tag]         1.6.0      -> 1.6.0
 * [new tag]         1.7.0-0.2  -> 1.7.0-0.2
 * [new tag]         1.7.0-0.3  -> 1.7.0-0.3
 * [new tag]         fj_test_201902 -> fj_test_201902
Submodule path 'ihk': checked out '2c16f87330a899224270570e241c4deddd9cfdfa'
+ cd /work/mcktest/bin
+ exit 0
+ [[ submodule == \s\u\b\m\o\d\u\l\e ]]
+ read subref _
++ cd /work/mcktest/work_refs-changes-88-510788-1_submodule/src/mckernel-refs-changes-88-510788-1-6e6d2b80044159945350fa4741e265246afe6880
++ GIT_DIR=/work/mcktest/git/mckernel/.git
++ /work/mcktest/tools/bin/git submodule status
++ awk '$2 == "ihk" {print}'
+ SUBMODULE_HASH=2c16f87330a899224270570e241c4deddd9cfdfa
++ ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io 'gerrit query --format=TEXT --current-patch-set --commit-message commit:2c16f87330a899224270570e241c4deddd9cfdfa'
++ awk '/ref:/ { print $2 }'
+ SUBMODULE_PATHSPEC=refs/changes/07/509807/2
+ [[ refs/changes/07/509807/2 != '' ]]
+ IHKBRANCH=refs-changes-07-509807-2
+ echo 'ihk: submodule commit resolved to refs-changes-07-509807-2'
ihk: submodule commit resolved to refs-changes-07-509807-2
+ [[ -n refs-changes-07-509807-2 ]]
+ case "$IHKBRANCH" in
+ bash -x ./wget-postpeta.sh ihk refs-changes-07-509807-2
++ pwd
+ CWD=/work/mcktest/bin
+++ dirname ./wget-postpeta.sh
++ cd ./..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ dirname ./wget-postpeta.sh
+ cd .
+ . ./config.sh
+++ shopt -po xtrace
++ tracestate='set -o xtrace'
++ echo set -o xtrace
++ grep -q -
++ set +x
+ forwatchgerrit=0
+ REPO=ihk
+ BRANCH=refs-changes-07-509807-2
+ case "$BRANCH" in
+ remote_type=gerrit-git
+ PATHSPEC=refs/changes/07/509807/2
+ '[' /work/mcktest/work_refs-changes-88-510788-1_submodule/src == '' ']'
+ '[' ihk == '' ']'
+ DEST=ihk
+ [[ -d /work/mcktest/work_refs-changes-88-510788-1_submodule/src ]]
+ rm -rf '/work/mcktest/work_refs-changes-88-510788-1_submodule/src/ihk-*'
+ case $NODETYPE in
+ case $remote_type in
+ pushd /work/mcktest/git
/work/mcktest/git /work/mcktest/bin
+ sudo -u mcktest rm -rf ihk
+ sudo -u mcktest git clone ssh://riken-syssoft-gerrit@review.gerrithub.io/RIKEN-SysSoft/ihk
Cloning into 'ihk'...
Total 9827 (delta 7241), reused 9614 (delta 7241)
+ cd ihk
+ sudo -u mcktest git fetch origin refs/changes/07/509807/2
From ssh://review.gerrithub.io/RIKEN-SysSoft/ihk
 * branch            refs/changes/07/509807/2 -> FETCH_HEAD
++ sudo -u mcktest git rev-parse FETCH_HEAD
+ COMMIT=2c16f87330a899224270570e241c4deddd9cfdfa
+ DEST=ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa
+ popd
/work/mcktest/bin
+ '[' 0 -ne 0 ']'
+ '[' 0 -eq 1 ']'
+ case $remote_type in
+ mkdir /work/mcktest/work_refs-changes-88-510788-1_submodule/src/ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa
+ cd /work/mcktest/work_refs-changes-88-510788-1_submodule/src/ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa
+ GIT_DIR=/work/mcktest/git/ihk/.git
+ git reset --hard 2c16f87330a899224270570e241c4deddd9cfdfa
HEAD is now at 2c16f87 ihklib: fix printk
+ GIT_DIR=/work/mcktest/git/ihk/.git
+ git submodule update --init
+ cd /work/mcktest/bin
+ exit 0
++ head -n1
++ ls -dt /work/mcktest/work_refs-changes-88-510788-1_submodule/src/ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa
++ xargs -r basename
+ IHKHEAD=ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa
++ head -n1
++ ls -dt /work/mcktest/work_refs-changes-88-510788-1_submodule/src/mckernel-refs-changes-88-510788-1-6e6d2b80044159945350fa4741e265246afe6880
++ xargs -r basename
+ MCKERNELHEAD=mckernel-refs-changes-88-510788-1-6e6d2b80044159945350fa4741e265246afe6880
+ '[' -f /work/mcktest/work_refs-changes-88-510788-1_submodule/mck/ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa ']'
+ rm -f /work/mcktest/work_refs-changes-88-510788-1_submodule/src/ihk
+ rm -f /work/mcktest/work_refs-changes-88-510788-1_submodule/src/mckernel
+ '[' '!' -d /work/mcktest/work_refs-changes-88-510788-1_submodule/src/ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa ']'
+ ln -s ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa /work/mcktest/work_refs-changes-88-510788-1_submodule/src/ihk
+ '[' '!' -d /work/mcktest/work_refs-changes-88-510788-1_submodule/src/mckernel-refs-changes-88-510788-1-6e6d2b80044159945350fa4741e265246afe6880 ']'
+ ln -s mckernel-refs-changes-88-510788-1-6e6d2b80044159945350fa4741e265246afe6880 /work/mcktest/work_refs-changes-88-510788-1_submodule/src/mckernel
+ rm -rf /work/mcktest/work_refs-changes-88-510788-1_submodule/src/mckernel/ihk
+ echo MCKBUILD=/work/mcktest/work_refs-changes-88-510788-1_submodule/build
MCKBUILD=/work/mcktest/work_refs-changes-88-510788-1_submodule/build
+ echo MCKINSTALL=/work/mcktest/work_refs-changes-88-510788-1_submodule/mck
MCKINSTALL=/work/mcktest/work_refs-changes-88-510788-1_submodule/mck
+ sudo rm -rf /work/mcktest/work_refs-changes-88-510788-1_submodule/build
+ /work/mcktest/bin/config_and_build_smp_x86.sh /work/mcktest/work_refs-changes-88-510788-1_submodule/src /work/mcktest/work_refs-changes-88-510788-1_submodule/build /work/mcktest/work_refs-changes-88-510788-1_submodule/mck
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.11 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
+ error 'autobuild.sh failed'
+ echo 'ERROR: autobuild.sh failed'
ERROR: autobuild.sh failed
+ cd /
+ exit -1

Patch-set: 5
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Test-x86=-1