Update patch set 1
Patch Set 1: Verified-1

mckernel build failed:
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcctrl SUBDIRS=/tmp/build/mckernel/executer/kernel/mcctrl ARCH=x86_64 modules
make[2]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[2]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[2]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 SUBDIRS=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 ARCH=x86_64 modules
make[3]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[3]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[2]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[1]: Entering directory `/tmp/build/mckernel/executer/user'
(cd arch/x86_64; make)
make[2]: Entering directory `/tmp/build/mckernel/executer/user/arch/x86_64'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/tmp/build/mckernel/executer/user/arch/x86_64'
gcc -shared -fPIC -Wl,-soname,sched_yield.so.1 -o libsched_yield.so.1.0.0 /work/mcktest/git/mckernel/executer/user/libsched_yield.c -lc -ldl
make[1]: Leaving directory `/tmp/build/mckernel/executer/user'
make[1]: Entering directory `/tmp/build/mckernel/kernel'
make[1]: Circular /tmp/build/mckernel/kernel/build/smp-x86/kernel.img <- /tmp/build/mckernel/kernel/build/smp-x86/kernel.img dependency dropped.
Building for /tmp/build/mckernel/kernel/build/smp-x86/
 (smp-x86) DEPEND
 (smp-x86) BUILD IHK smp-x86
 (smp-x86) BUILD IHK smp-x86
 (smp-x86) DEPEND [IHK]
 (smp-x86) BUILD IKC [IHK] smp-x86
 (smp-x86) DEPEND [IKC]
rm /tmp/build/mckernel/kernel/build/smp-x86/Makefile
make[1]: Leaving directory `/tmp/build/mckernel/kernel'
make[1]: Entering directory `/tmp/build/mckernel/tools/mcstat'
gcc -I/lib/modules/3.10.0-693.2.2.el7.x86_64/build -Wall -O -I. -I/work/mcktest/git/mckernel/tools/mcstat/../../../ihk/linux/include/ -I/work/mcktest/git/mckernel/tools/mcstat/../../executer/include -I/tmp/build/mckernel/tools/mcstat/../../../ihk/linux/include/ihk  -L/tmp/build/mckernel/tools/mcstat/../../../ihk/linux/user -lihk -Wl,-rpath -Wl,/tmp/install/lib  -o mcstat /work/mcktest/git/mckernel/tools/mcstat/mcstat.c
/work/mcktest/git/mckernel/tools/mcstat/mcstat.c: In function ‘mygetrusage’:
/work/mcktest/git/mckernel/tools/mcstat/mcstat.c:160:2: warning: implicit declaration of function ‘ihk_os_query_total_mem’ [-Wimplicit-function-declaration]
  rc = ihk_os_query_total_mem(idx, memtotal, num_numa_nodes);
  ^
/tmp/cc23aSuC.o: In function `mygetrusage':
mcstat.c:(.text+0xd3): undefined reference to `ihk_os_query_total_mem'
collect2: error: ld returned 1 exit status
make[1]: *** [mcstat] Error 1
make[1]: Target `all' not remade because of errors.
make[1]: Leaving directory `/tmp/build/mckernel/tools/mcstat'
make: *** [mck-tools] Error 2
make: Target `all' not remade because of errors.

Patch-set: 1
Reviewer: riken-syssoft-gerrit <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1