Update patch set 4
Patch Set 4: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 15%] Generating kmod_always_rebuild
[ 16%] Building kmod mcctrl
[ 18%] Built target mcctrl_ko
[ 19%] Building C object executer/user/CMakeFiles/eclair.dir/arch/x86_64/arch-eclair.c.o
/work/mcktest/git/mckernel/executer/user/arch/x86_64/arch-eclair.c: In function ‘arch_read_kregs’:
/work/mcktest/git/mckernel/executer/user/arch/x86_64/arch-eclair.c:140:2: error: implicit declaration of function ‘read_mem’ [-Werror=implicit-function-declaration]
  return read_mem(ctx, kregs, sizeof(*kregs));
  ^
/work/mcktest/git/mckernel/executer/user/arch/x86_64/arch-eclair.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [executer/user/CMakeFiles/eclair.dir/arch/x86_64/arch-eclair.c.o] Error 1
make[2]: Target `executer/user/CMakeFiles/eclair.dir/build' not remade because of errors.
make[1]: *** [executer/user/CMakeFiles/eclair.dir/all] Error 2
[ 20%] Built target ldump2mcdump
[ 22%] Built target libmcexec
[ 23%] Built target mcexec
[ 25%] Built target sched_yield
[ 97%] Built target mckernel.img
[ 98%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 4
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1