Update patch set 4
Patch Set 4: Verified-1

build failed for aarch64:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  5%] Built target ihkconfig
[  6%] Built target ihkmond
[  7%] Built target ihkosctl
[  8%] Generating kmod_always_rebuild
[  9%] Building kmod ihk-smp-arm64
[ 10%] Built target ihk-smp-arm64_ko
[ 11%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/arm64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/arm64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 12%] Building kmod mcctrl
/work/mcktest/git/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c: In function ‘arch_mcexec_uti_save_fs’:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:314:3: error: unknown field ‘regs’ specified in initializer
   .regs = current_pt_regs()->user_regs,
   ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:314:3: error: implicit declaration of function ‘current_pt_regs’ [-Werror=implicit-function-declaration]
/work/mcktest/git/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:314:28: error: invalid type argument of ‘->’ (have ‘int’)
   .regs = current_pt_regs()->user_regs,
                            ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:320:2: error: implicit declaration of function ‘copy_to_user’ [-Werror=implicit-function-declaration]
  if (copy_to_user(lctx, &klctx, sizeof(klctx))) {
  ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:326:2: error: implicit declaration of function ‘copy_from_user’ [-Werror=implicit-function-declaration]
  if (copy_from_user(&current_pt_regs()->user_regs,
  ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:326:39: error: invalid type argument of ‘->’ (have ‘int’)
  if (copy_from_user(&current_pt_regs()->user_regs,
                                       ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:327:12: error: ‘struct trans_uctx’ has no member named ‘regs’
       &rctx->regs, sizeof(rctx->regs))) {
            ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:327:31: error: ‘struct trans_uctx’ has no member named ‘regs’
       &rctx->regs, sizeof(rctx->regs))) {
                               ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:332:2: error: implicit declaration of function ‘restore_tls’ [-Werror=implicit-function-declaration]
  restore_tls(get_tls_ctx(rctx));
  ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:332:2: error: implicit declaration of function ‘get_tls_ctx’ [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-aarch64-mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-aarch64-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 14%] Built target eclair
[ 15%] Built target ldump2mcdump
[ 16%] Built target libmcexec
[ 17%] Built target mcexec
[ 18%] Built target sched_yield
[ 97%] Built target mckernel.img
[ 98%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 4
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1