Update patch set 3
Patch Set 3:

wallaby7: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 10%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 15%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/x86_64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/x86_64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 16%] Building kmod mcctrl
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c: In function ‘mcctrl_perf_num’:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:2179:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  struct mcctrl_usrdata *usrdata = ihk_host_os_get_usrdata(os);
  ^
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/control.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 19%] Built target eclair
[ 20%] Built target ldump2mcdump
[ 21%] Built target libmcexec
[ 23%] Built target mcexec
[ 24%] Built target mcinspect
[ 26%] Built target sched_yield
[ 97%] Built target mckernel.img
[ 98%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 3
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>