Update patch set 3
Patch Set 3: Verified-1

wallaby7: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 10%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 14%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/x86_64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/x86_64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 16%] Building kmod mcctrl
/work/mcktest/git/mckernel/executer/kernel/mcctrl/syscall.c: In function ‘__return_syscall’:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/syscall.c:1908:5: error: ‘MAX_USER_VA_BITS’ undeclared (first use in this function)
     MAX_USER_VA_BITS, PGDIR_SHIFT);
     ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/syscall.c:1908:5: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/syscall.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 18%] Built target eclair
[ 20%] Built target ldump2mcdump
[ 21%] Built target libmcexec
[ 22%] Built target mcexec
[ 24%] Built target mcinspect
[ 25%] Built target sched_yield
[ 27%] Building C object kernel/CMakeFiles/mckernel.img.dir/host.c.o
/work/mcktest/git/mckernel/kernel/host.c: In function ‘process_msg_prepare_process’:
/work/mcktest/git/mckernel/kernel/host.c:553:3: error: implicit declaration of function ‘tof_utofu_finalize’ [-Werror=implicit-function-declaration]
   tof_utofu_finalize();
   ^
/work/mcktest/git/mckernel/kernel/host.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/host.c.o] Error 1
[ 28%] Building C object kernel/CMakeFiles/mckernel.img.dir/tofu/tof_utofu_main.c.o
/work/mcktest/git/mckernel/kernel/tofu/tof_utofu_main.c:13:16: fatal error: io.h: No such file or directory
 #include <io.h>
                ^
compilation terminated.
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/tofu/tof_utofu_main.c.o] Error 1
[ 29%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/cpu.c.o
In file included from /work/mcktest/git/mckernel/lib/include/memory.h:17:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:19,
                 from /work/mcktest/git/mckernel/arch/x86_64/kernel/cpu.c:19:
/work/mcktest/git/mckernel/arch/x86_64/kernel/cpu.c: In function ‘__show_context_stack’:
/work/mcktest/git/mckernel/arch/x86_64/kernel/cpu.c:877:41: error: ‘KERNEL_STACK_SIZE’ undeclared (first use in this function)
     stack_top = ALIGN_UP(sp, (uintptr_t)KERNEL_STACK_SIZE);
                                         ^
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:457:35: note: in definition of macro ‘ALIGN_DOWN’
 # define ALIGN_DOWN(x, align)   ((x) & ~((align) - 1))
                                   ^
/work/mcktest/git/mckernel/arch/x86_64/kernel/cpu.c:877:17: note: in expansion of macro ‘ALIGN_UP’
     stack_top = ALIGN_UP(sp, (uintptr_t)KERNEL_STACK_SIZE);
                 ^
/work/mcktest/git/mckernel/arch/x86_64/kernel/cpu.c:877:41: note: each undeclared identifier is reported only once for each function it appears in
     stack_top = ALIGN_UP(sp, (uintptr_t)KERNEL_STACK_SIZE);
                                         ^
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:457:35: note: in definition of macro ‘ALIGN_DOWN’
 # define ALIGN_DOWN(x, align)   ((x) & ~((align) - 1))
                                   ^
/work/mcktest/git/mckernel/arch/x86_64/kernel/cpu.c:877:17: note: in expansion of macro ‘ALIGN_UP’
     stack_top = ALIGN_UP(sp, (uintptr_t)KERNEL_STACK_SIZE);
                 ^
/work/mcktest/git/mckernel/arch/x86_64/kernel/cpu.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/cpu.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 31%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 3
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1