Update patch set 3
Patch Set 3: Verified-1

mckernel build failed:
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcctrl SUBDIRS=/tmp/build/mckernel/executer/kernel/mcctrl ARCH=x86_64 modules
make[2]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[2]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[2]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 SUBDIRS=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 ARCH=x86_64 modules
make[3]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[3]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[2]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[1]: Entering directory `/tmp/build/mckernel/executer/user'
(cd arch/x86_64; make)
make[2]: Entering directory `/tmp/build/mckernel/executer/user/arch/x86_64'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/tmp/build/mckernel/executer/user/arch/x86_64'
gcc -shared -fPIC -Wl,-soname,sched_yield.so.1 -o libsched_yield.so.1.0.0 /work/mcktest/git/mckernel/executer/user/libsched_yield.c -lc -ldl
make[1]: Leaving directory `/tmp/build/mckernel/executer/user'
make[1]: Entering directory `/tmp/build/mckernel/kernel'
make[1]: Circular /tmp/build/mckernel/kernel/build/smp-x86/kernel.img <- /tmp/build/mckernel/kernel/build/smp-x86/kernel.img dependency dropped.
Building for /tmp/build/mckernel/kernel/build/smp-x86/
 (smp-x86) DEPEND
 (smp-x86) BUILD IHK smp-x86
 (smp-x86) BUILD IHK smp-x86
 (smp-x86) DEPEND [IHK]
 (smp-x86) BUILD IKC [IHK] smp-x86
 (smp-x86) DEPEND [IKC]
 (smp-x86) CC [IKC] queue.c
In file included from /work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/include/arch-lock.h:9:0,
                 from /work/mcktest/git/mckernel/kernel/../lib/include/ihk/debug.h:17,
                 from /work/mcktest/git/mckernel/ihk/cokernel/../ikc/include/ikc/ihk.h:37,
                 from queue.c:8:
/work/mcktest/git/mckernel/kernel/../kernel/include/lwk/compiler.h:492:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static __always_inline void __read_once_size(const volatile void *p, void *res, int size)
                        ^
/work/mcktest/git/mckernel/kernel/../kernel/include/lwk/compiler.h:506:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static __always_inline void __write_once_size(volatile void *p, void *res, int size)
                        ^
In file included from /work/mcktest/git/mckernel/kernel/../lib/include/ihk/debug.h:17:0,
                 from /work/mcktest/git/mckernel/ihk/cokernel/../ikc/include/ikc/ihk.h:37,
                 from queue.c:8:
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/include/arch-lock.h: In function ‘__ihk_mc_spinlock_lock_noirq’:
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/include/arch-lock.h:122:2: warning: implicit declaration of function ‘barrier’ [-Wimplicit-function-declaration]
  barrier(); /* make sure nothing creeps before the lock is taken */
  ^
make[4]: *** [/tmp/build/mckernel/kernel/build/smp-x86/ihk/ikc/queue.o] Error 1
 (smp-x86) CC [IKC] master.c
In file included from /work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/include/arch-lock.h:9:0,
                 from /work/mcktest/git/mckernel/kernel/../lib/include/ihk/debug.h:17,
                 from /work/mcktest/git/mckernel/ihk/cokernel/../ikc/include/ikc/ihk.h:37,
                 from master.c:7:
/work/mcktest/git/mckernel/kernel/../kernel/include/lwk/compiler.h:492:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static __always_inline void __read_once_size(const volatile void *p, void *res, int size)
                        ^
/work/mcktest/git/mckernel/kernel/../kernel/include/lwk/compiler.h:506:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static __always_inline void __write_once_size(volatile void *p, void *res, int size)
                        ^
In file included from /work/mcktest/git/mckernel/kernel/../lib/include/ihk/debug.h:17:0,
                 from /work/mcktest/git/mckernel/ihk/cokernel/../ikc/include/ikc/ihk.h:37,
                 from master.c:7:
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/include/arch-lock.h: In function ‘__ihk_mc_spinlock_lock_noirq’:
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/include/arch-lock.h:122:2: warning: implicit declaration of function ‘barrier’ [-Wimplicit-function-declaration]
  barrier(); /* make sure nothing creeps before the lock is taken */
  ^
make[4]: *** [/tmp/build/mckernel/kernel/build/smp-x86/ihk/ikc/master.o] Error 1
 (smp-x86) CC [IKC] manycore.c
In file included from /work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/include/arch-lock.h:9:0,
                 from /work/mcktest/git/mckernel/kernel/../lib/include/ihk/debug.h:17,
                 from /work/mcktest/git/mckernel/ihk/cokernel/../ikc/include/ikc/ihk.h:37,
                 from manycore.c:7:
/work/mcktest/git/mckernel/kernel/../kernel/include/lwk/compiler.h:492:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static __always_inline void __read_once_size(const volatile void *p, void *res, int size)
                        ^
/work/mcktest/git/mckernel/kernel/../kernel/include/lwk/compiler.h:506:24: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static __always_inline void __write_once_size(volatile void *p, void *res, int size)
                        ^
In file included from /work/mcktest/git/mckernel/kernel/../lib/include/ihk/debug.h:17:0,
                 from /work/mcktest/git/mckernel/ihk/cokernel/../ikc/include/ikc/ihk.h:37,
                 from manycore.c:7:
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/include/arch-lock.h: In function ‘__ihk_mc_spinlock_lock_noirq’:
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/include/arch-lock.h:122:2: warning: implicit declaration of function ‘barrier’ [-Wimplicit-function-declaration]
  barrier(); /* make sure nothing creeps before the lock is taken */
  ^
make[4]: *** [/tmp/build/mckernel/kernel/build/smp-x86/ihk/ikc/manycore.o] Error 1
make[4]: Target `all' not remade because of errors.
make[3]: *** [/tmp/build/mckernel/kernel/build/smp-x86/ihk/ikc/ikc.o] Error 2
make[3]: Target `all' not remade because of errors.
make[2]: *** [ihk/ihk.o] Error 2
make[2]: Target `all' not remade because of errors.
make[1]: *** [/tmp/build/mckernel/kernel/build/smp-x86/kernel.img] Error 2
make[1]: Target `all' not remade because of errors.
rm /tmp/build/mckernel/kernel/build/smp-x86/Makefile
make[1]: Leaving directory `/tmp/build/mckernel/kernel'
make: *** [mckernel] Error 2
make[1]: Entering directory `/tmp/build/mckernel/tools/mcstat'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/tmp/build/mckernel/tools/mcstat'
make: Target `all' not remade because of errors.

Patch-set: 3
Reviewer: syssoft-gerrit@ml.riken.jp <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1