Update patch set 1
Patch Set 1: Test-arm64-1

MCKERNEL : mckernel-refs-changes-02-427602-1-?
IHK      : ihk-refs-changes-02-427602-1-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/427602/1 // cad305d893fafcf5594aef2925723756c92f1027
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 2-11,30-39 -m 10G@0,10G@1 -r 2-6:0+7-11:1+30-34:28+35-39:29 -o root -O
HOST  : apollo16.postk.local.r-ccs.riken.jp
DIR   : /work/mcktest/work_refs-changes-02-427602-1_submodule
START : 20190320195852
END   : 20190320195855

From https://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/02/427602/1 -> FETCH_HEAD
HEAD is now at cad305d procfs: add missing information in /proc/stat
error: pathspec 'ihk' did not match any file(s) known to git.
Did you forget to 'git add'?
ERROR: no IHK branch set and submodule not found

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Test-arm64=-1