Update patch set 2
Patch Set 2:

MCKERNEL : mckernel-refs-changes-11-427611-2-?
IHK      : ihk-refs-changes-11-427611-2-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/427611/2 // 2feb485c4be719d6ba2d6f400da3d66ca89e1405
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_refs-changes-11-427611-2_submodule
START : 20181013211207
END   : 20181013211217

From ssh://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/11/427611/2 -> FETCH_HEAD
HEAD is now at 2feb485 cmake: Add ENABLE_UBSAN for -fsanitize=undefined
HEAD is now at 29be544 build system: switch to cmake
MCKBUILD=/work/mcktest/work_refs-changes-11-427611-2_submodule/build
MCKINSTALL=/work/mcktest/work_refs-changes-11-427611-2_submodule/mck
/work/mcktest/bin/config_and_build_smp_x86.sh: line 24: /work/mcktest/work_refs-changes-11-427611-2_submodule/src/ihk/configure: No such file or directory
ERROR: autobuild.sh failed

Patch-set: 2
Reviewer: syssoft-gerrit@ml.riken.jp <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>