Update patch set 2
Patch Set 2:

MCKERNEL : mckernel-refs-changes-93-443693-2-?
IHK      : ihk-refs-changes-93-443693-2-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/443693/2 // bcfb9faa1ce4a3bd1f4b00f84c009dc498e9c5fd
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_refs-changes-93-443693-2_submodule
START : 20190212072404
END   : 20190212072407

From https://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/93/443693/2 -> FETCH_HEAD
HEAD is now at bcfb9fa ubsan: fix undefined shifts
HEAD is now at 7ed498e warnings: fix printf warning on %p with va_list
MCKBUILD=/work/mcktest/work_refs-changes-93-443693-2_submodule/build
MCKINSTALL=/work/mcktest/work_refs-changes-93-443693-2_submodule/mck
-- The C compiler identification is GNU 4.8.5
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Performing Test IMPLICIT_FALLTHROUGH
-- Performing Test IMPLICIT_FALLTHROUGH - Success
CMake Warning (dev) at CMakeLists.txt:116 (add_subdirectory):
  The source directory

    /work/mcktest/work_refs-changes-93-443693-2_submodule/src/mckernel/ihk

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

Defined module mcctrl
-------------------------------
Option summary
-------------------------------
Build type: Debug
Build target: smp-x86
IHK_SOURCE_DIR: ihk (relative to mckernel source tree)
UNAME_R: 3.10.0-693.2.2.el7.x86_64
KERNEL_DIR: /lib/modules/3.10.0-693.2.2.el7.x86_64/build
SYSTEM_MAP: /lib/modules/3.10.0-693.2.2.el7.x86_64/build/System.map
VMLINUX: /lib/modules/3.10.0-693.2.2.el7.x86_64/build/vmlinux
KBUILD_C_FLAGS: 
ENABLE_MEMDUMP: ON
ENABLE_PERF: ON
ENABLE_RUSAGE: ON
ENABLE_MCOVERLAYFS: OFF
ENABLE_WERROR: OFF
ENABLE_UBSAN: OFF
-------------------------------
-- Configuring done
CMake Error at kernel/CMakeLists.txt:168 (add_executable):
  Cannot find source file:

    /work/mcktest/work_refs-changes-93-443693-2_submodule/src/mckernel/ihk/ikc/manycore.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


-- Build files have been written to: /work/mcktest/work_refs-changes-93-443693-2_submodule/build/3.10.0-693.2.2.el7.x86_64
ERROR: autobuild.sh failed

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>