Update patch set 4
Patch Set 4: Test-x86-1

MCKERNEL : mckernel-refs-changes-88-506088-4-?
IHK      : ihk-refs-changes-88-506088-4-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/506088/4 // f24d61fda5a9cd429fd001a4200862f8aa7e78c6
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_refs-changes-88-506088-4_submodule
START : 20210216154520
END   : 20210216154555

+++ dirname /work/mcktest/bin/autobuild.sh
++ cd /work/mcktest/bin/..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ pwd
+ CWD=/
++ dirname /work/mcktest/bin/autobuild.sh
+ cd /work/mcktest/bin
+ . ./config.sh
+++ shopt -po xtrace
++ tracestate='set -o xtrace'
++ echo set -o xtrace
++ grep -q -
++ set +x
+ export BINDIR=
+ BINDIR=
+ bash -x ./wget-postpeta.sh mckernel refs-changes-88-506088-4
++ pwd
+ CWD=/work/mcktest/bin
+++ dirname ./wget-postpeta.sh
++ cd ./..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ dirname ./wget-postpeta.sh
+ cd .
+ . ./config.sh
+++ shopt -po xtrace
++ tracestate='set -o xtrace'
++ echo set -o xtrace
++ grep -q -
++ set +x
+ forwatchgerrit=0
+ REPO=mckernel
+ BRANCH=refs-changes-88-506088-4
+ case "$BRANCH" in
+ remote_type=gerrit-git
+ PATHSPEC=refs/changes/88/506088/4
+ '[' /work/mcktest/work_refs-changes-88-506088-4_submodule/src == '' ']'
+ '[' mckernel == '' ']'
+ DEST=mckernel
+ [[ -d /work/mcktest/work_refs-changes-88-506088-4_submodule/src ]]
+ mkdir /work/mcktest/work_refs-changes-88-506088-4_submodule/src
+ rm -rf '/work/mcktest/work_refs-changes-88-506088-4_submodule/src/mckernel-*'
+ case $NODETYPE in
+ case $remote_type in
+ pushd /work/mcktest/git
/work/mcktest/git /work/mcktest/bin
+ sudo -u mcktest rm -rf mckernel
+ sudo -u mcktest git clone ssh://riken-syssoft-gerrit@review.gerrithub.io/RIKEN-SysSoft/mckernel
Cloning into 'mckernel'...
Total 33104 (delta 21340), reused 32583 (delta 21340)
+ cd mckernel
+ sudo -u mcktest git fetch origin refs/changes/88/506088/4
Total 19 (delta 8), reused 17 (delta 8)
From ssh://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/88/506088/4 -> FETCH_HEAD
++ sudo -u mcktest git rev-parse FETCH_HEAD
+ COMMIT=f24d61fda5a9cd429fd001a4200862f8aa7e78c6
+ DEST=mckernel-refs-changes-88-506088-4-f24d61fda5a9cd429fd001a4200862f8aa7e78c6
+ popd
/work/mcktest/bin
+ '[' 0 -ne 0 ']'
+ '[' 0 -eq 1 ']'
+ case $remote_type in
+ mkdir /work/mcktest/work_refs-changes-88-506088-4_submodule/src/mckernel-refs-changes-88-506088-4-f24d61fda5a9cd429fd001a4200862f8aa7e78c6
+ cd /work/mcktest/work_refs-changes-88-506088-4_submodule/src/mckernel-refs-changes-88-506088-4-f24d61fda5a9cd429fd001a4200862f8aa7e78c6
+ GIT_DIR=/work/mcktest/git/mckernel/.git
+ git reset --hard f24d61fda5a9cd429fd001a4200862f8aa7e78c6
HEAD is now at f24d61f Send a signal to mcexec after switching to that process.
+ GIT_DIR=/work/mcktest/git/mckernel/.git
+ git submodule update --init
Submodule 'executer/user/lib/libdwarf/libdwarf' (https://github.com/bgerofi/libdwarf.git) registered for path 'executer/user/lib/libdwarf/libdwarf'
Submodule 'ihk' (https://github.com/RIKEN-SysSoft/ihk.git) registered for path 'ihk'
Cloning into 'executer/user/lib/libdwarf/libdwarf'...
Submodule path 'executer/user/lib/libdwarf/libdwarf': checked out 'ab9230b2b8aa66a3d1d52e4be11fca17a3b63753'
Cloning into 'ihk'...
Submodule path 'ihk': checked out '2c16f87330a899224270570e241c4deddd9cfdfa'
+ cd /work/mcktest/bin
+ exit 0
+ [[ submodule == \s\u\b\m\o\d\u\l\e ]]
+ read subref _
++ cd /work/mcktest/work_refs-changes-88-506088-4_submodule/src/mckernel-refs-changes-88-506088-4-f24d61fda5a9cd429fd001a4200862f8aa7e78c6
++ GIT_DIR=/work/mcktest/git/mckernel/.git
++ /work/mcktest/tools/bin/git submodule status
++ awk '$2 == "ihk" {print}'
+ SUBMODULE_HASH=2c16f87330a899224270570e241c4deddd9cfdfa
++ ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io 'gerrit query --format=TEXT --current-patch-set --commit-message commit:2c16f87330a899224270570e241c4deddd9cfdfa'
++ awk '/ref:/ { print $2 }'
+ SUBMODULE_PATHSPEC=refs/changes/07/509807/2
+ [[ refs/changes/07/509807/2 != '' ]]
+ IHKBRANCH=refs-changes-07-509807-2
+ echo 'ihk: submodule commit resolved to refs-changes-07-509807-2'
ihk: submodule commit resolved to refs-changes-07-509807-2
+ [[ -n refs-changes-07-509807-2 ]]
+ case "$IHKBRANCH" in
+ bash -x ./wget-postpeta.sh ihk refs-changes-07-509807-2
++ pwd
+ CWD=/work/mcktest/bin
+++ dirname ./wget-postpeta.sh
++ cd ./..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ dirname ./wget-postpeta.sh
+ cd .
+ . ./config.sh
+++ shopt -po xtrace
++ tracestate='set -o xtrace'
++ echo set -o xtrace
++ grep -q -
++ set +x
+ forwatchgerrit=0
+ REPO=ihk
+ BRANCH=refs-changes-07-509807-2
+ case "$BRANCH" in
+ remote_type=gerrit-git
+ PATHSPEC=refs/changes/07/509807/2
+ '[' /work/mcktest/work_refs-changes-88-506088-4_submodule/src == '' ']'
+ '[' ihk == '' ']'
+ DEST=ihk
+ [[ -d /work/mcktest/work_refs-changes-88-506088-4_submodule/src ]]
+ rm -rf '/work/mcktest/work_refs-changes-88-506088-4_submodule/src/ihk-*'
+ case $NODETYPE in
+ case $remote_type in
+ pushd /work/mcktest/git
/work/mcktest/git /work/mcktest/bin
+ sudo -u mcktest rm -rf ihk
+ sudo -u mcktest git clone ssh://riken-syssoft-gerrit@review.gerrithub.io/RIKEN-SysSoft/ihk
Cloning into 'ihk'...
Total 9827 (delta 7241), reused 9614 (delta 7241)
+ cd ihk
+ sudo -u mcktest git fetch origin refs/changes/07/509807/2
From ssh://review.gerrithub.io/RIKEN-SysSoft/ihk
 * branch            refs/changes/07/509807/2 -> FETCH_HEAD
++ sudo -u mcktest git rev-parse FETCH_HEAD
+ COMMIT=2c16f87330a899224270570e241c4deddd9cfdfa
+ DEST=ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa
+ popd
/work/mcktest/bin
+ '[' 0 -ne 0 ']'
+ '[' 0 -eq 1 ']'
+ case $remote_type in
+ mkdir /work/mcktest/work_refs-changes-88-506088-4_submodule/src/ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa
+ cd /work/mcktest/work_refs-changes-88-506088-4_submodule/src/ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa
+ GIT_DIR=/work/mcktest/git/ihk/.git
+ git reset --hard 2c16f87330a899224270570e241c4deddd9cfdfa
HEAD is now at 2c16f87 ihklib: fix printk
+ GIT_DIR=/work/mcktest/git/ihk/.git
+ git submodule update --init
+ cd /work/mcktest/bin
+ exit 0
++ head -n1
++ ls -dt /work/mcktest/work_refs-changes-88-506088-4_submodule/src/ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa
++ xargs -r basename
+ IHKHEAD=ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa
++ head -n1
++ ls -dt /work/mcktest/work_refs-changes-88-506088-4_submodule/src/mckernel-refs-changes-88-506088-4-f24d61fda5a9cd429fd001a4200862f8aa7e78c6
++ xargs -r basename
+ MCKERNELHEAD=mckernel-refs-changes-88-506088-4-f24d61fda5a9cd429fd001a4200862f8aa7e78c6
+ '[' -f /work/mcktest/work_refs-changes-88-506088-4_submodule/mck/ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa ']'
+ rm -f /work/mcktest/work_refs-changes-88-506088-4_submodule/src/ihk
+ rm -f /work/mcktest/work_refs-changes-88-506088-4_submodule/src/mckernel
+ '[' '!' -d /work/mcktest/work_refs-changes-88-506088-4_submodule/src/ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa ']'
+ ln -s ihk-refs-changes-07-509807-2-2c16f87330a899224270570e241c4deddd9cfdfa /work/mcktest/work_refs-changes-88-506088-4_submodule/src/ihk
+ '[' '!' -d /work/mcktest/work_refs-changes-88-506088-4_submodule/src/mckernel-refs-changes-88-506088-4-f24d61fda5a9cd429fd001a4200862f8aa7e78c6 ']'
+ ln -s mckernel-refs-changes-88-506088-4-f24d61fda5a9cd429fd001a4200862f8aa7e78c6 /work/mcktest/work_refs-changes-88-506088-4_submodule/src/mckernel
+ rm -rf /work/mcktest/work_refs-changes-88-506088-4_submodule/src/mckernel/ihk
+ echo MCKBUILD=/work/mcktest/work_refs-changes-88-506088-4_submodule/build
MCKBUILD=/work/mcktest/work_refs-changes-88-506088-4_submodule/build
+ echo MCKINSTALL=/work/mcktest/work_refs-changes-88-506088-4_submodule/mck
MCKINSTALL=/work/mcktest/work_refs-changes-88-506088-4_submodule/mck
+ sudo rm -rf /work/mcktest/work_refs-changes-88-506088-4_submodule/build
+ /work/mcktest/bin/config_and_build_smp_x86.sh /work/mcktest/work_refs-changes-88-506088-4_submodule/src /work/mcktest/work_refs-changes-88-506088-4_submodule/build /work/mcktest/work_refs-changes-88-506088-4_submodule/mck
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.11 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
+ error 'autobuild.sh failed'
+ echo 'ERROR: autobuild.sh failed'
ERROR: autobuild.sh failed
+ cd /
+ exit -1

Patch-set: 4
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Test-x86=-1