Update patch set 4
Patch Set 4: Build-arm64-1

apollo15: build report: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  6%] Built target ihkmond
[  8%] Built target ihkconfig
[ 10%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-arm64
[ 13%] Built target ihk-smp-arm64_ko
[ 14%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/arm64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/arm64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 15%] Building kmod mcctrl
/tmp/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c: In function ‘arch_symbols_init’:
/tmp/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:106:2: error: ‘mcctrl_tof_core_cq_cacheflush’ undeclared (first use in this function)
  mcctrl_tof_core_cq_cacheflush =
  ^
/tmp/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:106:2: note: each undeclared identifier is reported only once for each function it appears in
/tmp/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:111:2: error: ‘mcctrl_tof_core_disable_bch’ undeclared (first use in this function)
  mcctrl_tof_core_disable_bch =
  ^
/tmp/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:116:2: error: ‘mcctrl_tof_core_unset_bg’ undeclared (first use in this function)
  mcctrl_tof_core_unset_bg =
  ^
/tmp/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:121:2: error: ‘mcctrl_tof_core_register_signal_bg’ undeclared (first use in this function)
  mcctrl_tof_core_register_signal_bg =
  ^
/tmp/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:126:2: error: ‘mcctrl_tof_utofu_bg’ undeclared (first use in this function)
  mcctrl_tof_utofu_bg =
  ^
/tmp/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:131:2: error: ‘mcctrl_tof_utofu_mn_ops’ undeclared (first use in this function)
  mcctrl_tof_utofu_mn_ops =
  ^
/tmp/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:139:10: error: ‘__mcctrl_tof_utofu_mn_ops’ undeclared (first use in this function)
  memcpy(&__mcctrl_tof_utofu_mn_ops, mcctrl_tof_utofu_mn_ops,
          ^
/tmp/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:142:3: error: ‘__mcctrl_tof_utofu_mn_invalidate_range_end’ undeclared (first use in this function)
   __mcctrl_tof_utofu_mn_invalidate_range_end;
   ^
/tmp/mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.c:144:2: error: ‘mcctrl_tof_utofu_mn_invalidate_range_end’ undeclared (first use in this function)
  mcctrl_tof_utofu_mn_invalidate_range_end =
  ^
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/arch/arm64/archdeps.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 17%] Built target libmcexec
[ 18%] Built target mcexec
[ 20%] Built target mcinspect
[ 22%] Built target sched_yield
[ 24%] Built target ldump2mcdump
[ 26%] Built target eclair
[ 97%] Built target mckernel.img
[ 99%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 4
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1