Update patch set 3
Patch Set 3: Build-arm64-1

apollo15: build report: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  5%] Built target ihkconfig
[  6%] Built target ihkmond
[  7%] Built target ihkosctl
[  8%] Generating kmod_always_rebuild
[  9%] Building kmod ihk-smp-arm64
[ 10%] Built target ihk-smp-arm64_ko
[ 11%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/arm64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/arm64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 12%] Building kmod mcctrl
/tmp/mckernel/executer/kernel/mcctrl/syscall.c: In function ‘__return_syscall’:
/tmp/mckernel/executer/kernel/mcctrl/syscall.c:1906:5: error: ‘MAX_USER_VA_BITS’ undeclared (first use in this function)
     MAX_USER_VA_BITS, PGDIR_SHIFT);
     ^
/tmp/mckernel/executer/kernel/mcctrl/syscall.c:1906:5: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/syscall.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 14%] Built target eclair
[ 15%] Built target ldump2mcdump
[ 16%] Built target libmcexec
[ 17%] Built target mcexec
[ 18%] Built target mcinspect
[ 19%] Built target sched_yield
[ 20%] Building C object kernel/CMakeFiles/mckernel.img.dir/host.c.o
/tmp/mckernel/kernel/host.c: In function ‘process_msg_prepare_process’:
/tmp/mckernel/kernel/host.c:553:3: error: implicit declaration of function ‘tof_utofu_finalize’ [-Werror=implicit-function-declaration]
   tof_utofu_finalize();
   ^
/tmp/mckernel/kernel/host.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/host.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 21%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 3
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1