Update patch set 1
Patch Set 1: Verified-1

apollo15.postk.local.r-ccs.riken.jp: build failed:
[  1%] Generating kmod_always_rebuild
[  1%] Building kmod ihk
[  2%] Built target ihk_ko
[  3%] Built target ihklib
[  3%] Built target ihkconfig
[  3%] Built target ihkmond
[  4%] Built target ihkosctl
[  5%] Generating kmod_always_rebuild
[  5%] Building kmod ihk-smp-arm64
[  6%] Built target ihk-smp-arm64_ko
[  7%] Generating kmod_always_rebuild
[  8%] Building kmod mcctrl
[  8%] Built target mcctrl_ko
[  9%] Built target eclair
[ 10%] Built target ldump2mcdump
[ 10%] Built target libmcexec
[ 11%] Built target mcexec
[ 13%] Built target gennames
[ 50%] Built target dwarf
[ 50%] Built target mcinspect
[ 51%] Built target sched_yield
[ 51%] Building C object kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o
/work/mcktest/git/mckernel/kernel/xpmem.c: In function ‘xpmem_attach’:
/work/mcktest/git/mckernel/kernel/xpmem.c:1113:3: error: passing argument 1 of ‘__ihk_mc_spinlock_unlock_noirq’ from incompatible pointer type [-Werror]
   ihk_mc_spinlock_unlock_noirq(&vm->memory_range_lock);
   ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/arch-lock.h:221:13: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static void __ihk_mc_spinlock_unlock_noirq(ihk_spinlock_t *lock)
             ^
/work/mcktest/git/mckernel/kernel/xpmem.c:1139:2: error: passing argument 1 of ‘__ihk_mc_spinlock_lock_noirq’ from incompatible pointer type [-Werror]
  ihk_mc_spinlock_lock_noirq(&vm->memory_range_lock);
  ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/arch-lock.h:146:13: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static void __ihk_mc_spinlock_lock_noirq(ihk_spinlock_t *lock)
             ^
/work/mcktest/git/mckernel/kernel/xpmem.c:1150:2: error: passing argument 1 of ‘__ihk_mc_spinlock_unlock_noirq’ from incompatible pointer type [-Werror]
  ihk_mc_spinlock_unlock_noirq(&vm->memory_range_lock);
  ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/arch-lock.h:221:13: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static void __ihk_mc_spinlock_unlock_noirq(ihk_spinlock_t *lock)
             ^
/work/mcktest/git/mckernel/kernel/xpmem.c: In function ‘xpmem_detach_att’:
/work/mcktest/git/mckernel/kernel/xpmem.c:1420:2: error: passing argument 1 of ‘__ihk_mc_spinlock_lock_noirq’ from incompatible pointer type [-Werror]
  ihk_mc_spinlock_lock_noirq(&vm->memory_range_lock);
  ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/arch-lock.h:146:13: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static void __ihk_mc_spinlock_lock_noirq(ihk_spinlock_t *lock)
             ^
/work/mcktest/git/mckernel/kernel/xpmem.c:1426:3: error: passing argument 1 of ‘__ihk_mc_spinlock_unlock_noirq’ from incompatible pointer type [-Werror]
   ihk_mc_spinlock_unlock_noirq(&vm->memory_range_lock);
   ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/arch-lock.h:221:13: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static void __ihk_mc_spinlock_unlock_noirq(ihk_spinlock_t *lock)
             ^
/work/mcktest/git/mckernel/kernel/xpmem.c: In function ‘xpmem_remove_process_memory_range’:
/work/mcktest/git/mckernel/kernel/xpmem.c:1668:3: error: passing argument 1 of ‘__ihk_mc_spinlock_lock_noirq’ from incompatible pointer type [-Werror]
   &cpu_local_var(current)->vm->memory_range_lock);
   ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/arch-lock.h:146:13: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static void __ihk_mc_spinlock_lock_noirq(ihk_spinlock_t *lock)
             ^
/work/mcktest/git/mckernel/kernel/xpmem.c:1751:3: error: passing argument 1 of ‘__ihk_mc_spinlock_unlock_noirq’ from incompatible pointer type [-Werror]
   &cpu_local_var(current)->vm->memory_range_lock);
   ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/arch-lock.h:221:13: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static void __ihk_mc_spinlock_unlock_noirq(ihk_spinlock_t *lock)
             ^
/work/mcktest/git/mckernel/kernel/xpmem.c: In function ‘xpmem_remap_pte’:
/work/mcktest/git/mckernel/kernel/xpmem.c:1908:2: error: passing argument 1 of ‘__ihk_mc_spinlock_lock_noirq’ from incompatible pointer type [-Werror]
  ihk_mc_spinlock_lock_noirq(&seg_tg->vm->memory_range_lock);
  ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/arch-lock.h:146:13: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static void __ihk_mc_spinlock_lock_noirq(ihk_spinlock_t *lock)
             ^
/work/mcktest/git/mckernel/kernel/xpmem.c:1913:2: error: passing argument 1 of ‘__ihk_mc_spinlock_unlock_noirq’ from incompatible pointer type [-Werror]
  ihk_mc_spinlock_unlock_noirq(&seg_tg->vm->memory_range_lock);
  ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/arch-lock.h:221:13: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static void __ihk_mc_spinlock_unlock_noirq(ihk_spinlock_t *lock)
             ^
/work/mcktest/git/mckernel/kernel/xpmem.c: In function ‘xpmem_pin_page’:
/work/mcktest/git/mckernel/kernel/xpmem.c:2045:2: error: passing argument 1 of ‘__ihk_mc_spinlock_lock_noirq’ from incompatible pointer type [-Werror]
  ihk_mc_spinlock_lock_noirq(&src_vm->memory_range_lock);
  ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/arch-lock.h:146:13: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static void __ihk_mc_spinlock_lock_noirq(ihk_spinlock_t *lock)
             ^
/work/mcktest/git/mckernel/kernel/xpmem.c:2049:2: error: passing argument 1 of ‘__ihk_mc_spinlock_unlock_noirq’ from incompatible pointer type [-Werror]
  ihk_mc_spinlock_unlock_noirq(&src_vm->memory_range_lock);
  ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/arch-lock.h:221:13: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static void __ihk_mc_spinlock_unlock_noirq(ihk_spinlock_t *lock)
             ^
/work/mcktest/git/mckernel/kernel/xpmem.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 52%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1