Update patch set 1
Patch Set 1: Test-x86-1

MCKERNEL : mckernel-refs-changes-22-456922-1-?
IHK      : ihk-refs-changes-22-456922-1-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/456922/1 // 5204dfec26421c538268f80968d5f9e0bbd4450f
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_refs-changes-22-456922-1_submodule
START : 20190605140428
END   : 20190605140436

From https://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/22/456922/1 -> FETCH_HEAD
HEAD is now at 5204dfe crash: use fix kernel mapping instead of module space on ARM
HEAD is now at 95c57b6 cmake: kmod: Convert McKernel "arm64" into Linux "aarch64"
MCKBUILD=/work/mcktest/work_refs-changes-22-456922-1_submodule/build
MCKINSTALL=/work/mcktest/work_refs-changes-22-456922-1_submodule/mck
-- The C compiler identification is GNU 4.8.5
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Performing Test IMPLICIT_FALLTHROUGH
-- Performing Test IMPLICIT_FALLTHROUGH - Success
Defined module ihk
Defined module ihk-smp-x86_64
Defined module mcctrl
-------------------------------
Option summary
-------------------------------
Build type: Debug
Build target: smp-x86
IHK_SOURCE_DIR: ../ihk (relative to mckernel source tree)
UNAME_R: 3.10.0-693.2.2.el7.x86_64
KERNEL_DIR: /lib/modules/3.10.0-693.2.2.el7.x86_64/build
SYSTEM_MAP: 
VMLINUX: 
KBUILD_C_FLAGS:  -DIHK_IKC_USE_LINUX_WORK_IRQ
ENABLE_MEMDUMP: ON
ENABLE_PERF: ON
ENABLE_RUSAGE: ON
ENABLE_QLMPI: OFF
ENABLE_UTI: OFF
ENABLE_WERROR: OFF
ENABLE_UBSAN: OFF
ENABLE_LINUX_WORK_IRQ_FOR_IKC: ON
-------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /work/mcktest/work_refs-changes-22-456922-1_submodule/build/3.10.0-693.2.2.el7.x86_64
Scanning dependencies of target ihk_ko
Scanning dependencies of target libmcexec
Scanning dependencies of target eclair
Scanning dependencies of target sched_yield
[  1%] [  2%] Scanning dependencies of target ihklib
[  4%] [  5%] Scanning dependencies of target ldump2mcdump
[  6%] [  8%] Generating kmod_always_rebuild
Building ASM object executer/user/CMakeFiles/libmcexec.dir/arch/x86_64/archdep.S.o
[  9%] Generating old_timestamp, host_driver.o, mem_alloc.o, mm.o, mikc.o, ../../ikc/linux.o, ../../ikc/master.o, ../../ikc/queue.o, .host_driver.o.cmd, .mem_alloc.o.cmd, .mm.o.cmd, .mikc.o.cmd, ../../ikc/.linux.o.cmd, ../../ikc/.master.o.cmd, ../../ikc/.queue.o.cmd, ihk.o, .ihk.o.cmd, ihk.mod.c, ihk.mod.o, .ihk.mod.o.cmd, .ihk.ko.cmd, .tmp_versions/ihk.mod, .tmp_versions, modules.order
Building C object executer/user/CMakeFiles/sched_yield.dir/libsched_yield.c.o
[ 11%] Building C object executer/user/CMakeFiles/eclair.dir/eclair.c.o
Building C object executer/user/CMakeFiles/eclair.dir/arch/x86_64/arch-eclair.c.o
Building C object ihk/linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
[ 12%] Building C object executer/user/CMakeFiles/ldump2mcdump.dir/ldump2mcdump.c.o
Building kmod ihk
Linking ASM static library libmcexec.a
Linking C shared library libsched_yield.so
[ 12%] Built target libmcexec
[ 12%] Built target sched_yield
Scanning dependencies of target mckernel.img
Linking C shared library libldump2mcdump.so
[ 13%] [ 16%] [ 16%] [ 18%] [ 19%] [ 22%] [ 23%] [ 23%] [ 25%] [ 26%] [ 27%] [ 29%] [ 30%] [ 31%] [ 33%] [ 34%] [ 36%] Building C object kernel/CMakeFiles/mckernel.img.dir/debug.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/mikc.c.o
[ 37%] Building C object kernel/CMakeFiles/mckernel.img.dir/mem.c.o
[ 38%] [ 40%] [ 41%] [ 43%] Building C object kernel/CMakeFiles/mckernel.img.dir/init.c.o
[ 44%] Building C object kernel/CMakeFiles/mckernel.img.dir/host.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/ap.c.o
[ 45%] Building C object kernel/CMakeFiles/mckernel.img.dir/syscall.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/copy.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/waitq.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/listeners.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/process.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/cls.c.o
Linking C executable eclair
Building C object kernel/CMakeFiles/mckernel.img.dir/fileobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/futex.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/timer.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/plist.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/devobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/shmobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/procfs.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/zeroobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/sysfs.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/freeze.c.o
[ 47%] Building C object kernel/CMakeFiles/mckernel.img.dir/profile.c.o
[ 48%] [ 50%] [ 51%] [ 52%] Building C object kernel/CMakeFiles/mckernel.img.dir/rbtree.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/gencore.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/pager.c.o
[ 54%] Building C object kernel/CMakeFiles/mckernel.img.dir/hugefileobj.c.o
[ 54%] Building C object kernel/CMakeFiles/mckernel.img.dir/llist.c.o
[ 55%] Built target ldump2mcdump
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-22-456922-1_submodule/src/ihk/ikc/manycore.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-22-456922-1_submodule/src/ihk/ikc/master.c.o
[ 56%] [ 58%] [ 59%] Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-22-456922-1_submodule/src/ihk/ikc/queue.c.o
[ 59%] Built target eclair
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/abort.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/bitmap.c.o
[ 61%] [ 62%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/bitops.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/page_alloc.c.o
[ 63%] [ 65%] [ 66%] [ 69%] [ 69%] Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-22-456922-1_submodule/src/ihk/cokernel/smp/ikc.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/string.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/vsprintf.c.o
[ 70%] Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-22-456922-1_submodule/src/ihk/cokernel/smp/x86_64/dma.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-22-456922-1_submodule/src/ihk/cokernel/smp/x86_64/setup.c.o
Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/context.S.o
[ 72%] [ 73%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/coredump.c.o
[ 75%] [ 76%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/cpu.c.o
Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/interrupt.S.o
[ 77%] [ 79%] Linking C shared library libihk.so
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/local.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/mikc.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/memory.c.o
[ 80%] [ 81%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/syscall.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/perfctr.c.o
[ 83%] [ 84%] Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/trampoline.S.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/vsyscall.c.o
In file included from /work/mcktest/work_refs-changes-22-456922-1_submodule/src/mckernel/arch/x86_64/kernel/perfctr.c:11:0:
/work/mcktest/work_refs-changes-22-456922-1_submodule/src/mckernel/lib/include/ihk/perfctr.h:76:33: warning: ‘struct thread’ declared inside parameter list [enabled by default]
 int ihk_mc_perfctr_alloc(struct thread *thread, int cpu_cycles);
                                 ^
/work/mcktest/work_refs-changes-22-456922-1_submodule/src/mckernel/lib/include/ihk/perfctr.h:76:33: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
/work/mcktest/work_refs-changes-22-456922-1_submodule/src/mckernel/arch/x86_64/kernel/perfctr.c:415:5: error: conflicting types for ‘ihk_mc_perfctr_alloc’
 int ihk_mc_perfctr_alloc(struct thread *thread, int cpu_cycles)
     ^
In file included from /work/mcktest/work_refs-changes-22-456922-1_submodule/src/mckernel/arch/x86_64/kernel/perfctr.c:11:0:
/work/mcktest/work_refs-changes-22-456922-1_submodule/src/mckernel/lib/include/ihk/perfctr.h:76:5: note: previous declaration of ‘ihk_mc_perfctr_alloc’ was here
 int ihk_mc_perfctr_alloc(struct thread *thread, int cpu_cycles);
     ^
cc1: warning: unrecognized command line option "-Wno-implicit-fallthrough" [enabled by default]
[ 84%] make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/perfctr.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Built target ihklib
Scanning dependencies of target mcstat
Scanning dependencies of target ihkosctl
Scanning dependencies of target ihkconfig
Scanning dependencies of target ihkmond
Scanning dependencies of target mcexec
[ 86%] [ 87%] [ 88%] [ 90%] [ 91%] Building C object ihk/linux/user/CMakeFiles/ihkmond.dir/ihkmond.c.o
Building C object tools/mcstat/CMakeFiles/mcstat.dir/mcstat.c.o
Building C object ihk/linux/user/CMakeFiles/ihkconfig.dir/ihkconfig.c.o
Building C object ihk/linux/user/CMakeFiles/ihkosctl.dir/ihkosctl.c.o
Building C object executer/user/CMakeFiles/mcexec.dir/mcexec.c.o
Linking C executable mcstat
[ 91%] Built target mcstat
Linking C executable ihkconfig
Linking C executable ihkosctl
[ 91%] Built target ihkconfig
Linking C executable ihkmond
[ 91%] Built target ihkosctl
[ 91%] Built target ihkmond
Linking C executable mcexec
[ 91%] Built target mcexec
[ 91%] Built target ihk_ko
Scanning dependencies of target ihk-smp-x86_64_ko
Scanning dependencies of target mcctrl_ko
[ 93%] [ 94%] [ 95%] [ 97%] Generating kmod_always_rebuild
Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/x86_64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/x86_64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
Generating kmod_always_rebuild
Generating old_timestamp, arch/x86_64/smp-x86_64-startup.o, arch/x86_64/smp-x86_64-trampoline.o, arch/x86_64/smp-arch-driver.o, smp-driver.o, arch/x86_64/.smp-x86_64-startup.o.cmd, arch/x86_64/.smp-x86_64-trampoline.o.cmd, arch/x86_64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-x86_64.o, .ihk-smp-x86_64.o.cmd, ihk-smp-x86_64.mod.c, ihk-smp-x86_64.mod.o, .ihk-smp-x86_64.mod.o.cmd, .ihk-smp-x86_64.ko.cmd, .tmp_versions/ihk-smp-x86_64.mod, .tmp_versions, modules.order
[ 98%] [100%] Building kmod mcctrl
Building kmod ihk-smp-x86_64
/work/mcktest/work_refs-changes-22-456922-1_submodule/build/3.10.0-693.2.2.el7.x86_64/ihk/linux/driver/smp/arch/x86_64/smp-x86_64-startup.o: warning: objtool: .text+0x7: can't find jump dest instruction at .text+0x38
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target mcctrl_ko
[100%] Built target ihk-smp-x86_64_ko
make: *** [all] Error 2
ERROR: autobuild.sh failed

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Test-x86=-1