Update patch set 1
Patch Set 1: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 15%] Generating kmod_always_rebuild
[ 16%] Building kmod mcctrl
[ 18%] Built target mcctrl_ko
[ 20%] Built target eclair
[ 22%] Built target ldump2mcdump
[ 23%] Built target libmcexec
[ 25%] Built target mcexec
[ 26%] Built target sched_yield
[ 27%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/perfctr.c.o
In file included from /work/mcktest/git/mckernel/arch/x86_64/kernel/perfctr.c:11:0:
/work/mcktest/git/mckernel/lib/include/ihk/perfctr.h:76:33: error: ‘struct thread’ declared inside parameter list [-Werror]
 int ihk_mc_perfctr_alloc(struct thread *thread, int cpu_cycles);
                                 ^
/work/mcktest/git/mckernel/lib/include/ihk/perfctr.h:76:33: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
/work/mcktest/git/mckernel/arch/x86_64/kernel/perfctr.c:415:5: error: conflicting types for ‘ihk_mc_perfctr_alloc’
 int ihk_mc_perfctr_alloc(struct thread *thread, int cpu_cycles)
     ^
In file included from /work/mcktest/git/mckernel/arch/x86_64/kernel/perfctr.c:11:0:
/work/mcktest/git/mckernel/lib/include/ihk/perfctr.h:76:5: note: previous declaration of ‘ihk_mc_perfctr_alloc’ was here
 int ihk_mc_perfctr_alloc(struct thread *thread, int cpu_cycles);
     ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/perfctr.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 29%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1