Update patch set 2
Patch Set 2:

apollo15: build report: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  5%] Built target ihkconfig
[  6%] Built target ihkmond
[  7%] Built target ihkosctl
[  8%] Generating kmod_always_rebuild
[  9%] Building kmod ihk-smp-arm64
[ 10%] Built target ihk-smp-arm64_ko
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod mcctrl
[ 13%] Built target mcctrl_ko
[ 15%] Built target eclair
[ 16%] Built target ldump2mcdump
[ 17%] Built target libmcexec
[ 18%] Built target mcexec
[ 19%] Built target mcinspect
[ 20%] Built target sched_yield
[ 21%] Building C object kernel/CMakeFiles/mckernel.img.dir/tofu/tof_utofu_main.c.o
/tmp/mckernel/kernel/tofu/tof_utofu_main.c: In function ‘tof_utofu_init_globals’:
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2041:34: error: dereferencing pointer to incomplete type
  tof_ib_stag_list = (int16_t *)tg->tof_ib_stag_list_addr;
                                  ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2042:41: error: dereferencing pointer to incomplete type
  tof_ib_stag_lock = (ihk_spinlock_t *)tg->tof_ib_stag_lock_addr;
                                         ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2043:38: error: dereferencing pointer to incomplete type
  tof_ib_stag_list_Rp_addr = (int *)tg->tof_ib_stag_list_Rp_addr;
                                      ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2044:38: error: dereferencing pointer to incomplete type
  tof_ib_stag_list_Wp_addr = (int *)tg->tof_ib_stag_list_Wp_addr;
                                      ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2046:36: error: dereferencing pointer to incomplete type
   (struct tof_util_aligned_mem *)tg->tof_ib_mbpt_mem_addr;
                                    ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2048:38: error: dereferencing pointer to incomplete type
   (struct tof_icc_steering_entry *)tg->tof_ib_steering_addr;
                                      ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2050:32: error: dereferencing pointer to incomplete type
   (struct tof_icc_mb_entry *)tg->tof_ib_mb_addr;
                                ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2052:27: error: dereferencing pointer to incomplete type
   (struct tof_core_cq *)tg->tof_core_cq_addr;
                           ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2054:27: error: dereferencing pointer to incomplete type
   (struct tof_core_bg *)tg->tof_core_bg_addr;
                           ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2056:28: error: dereferencing pointer to incomplete type
   (struct tof_utofu_bg *)tg->tof_utofu_bg_addr;
                            ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2058:38: error: dereferencing pointer to incomplete type
   (tof_utofu_handler_bg_signal_t *)tg->tof_utofu_handler_bg_signal_addr;
                                      ^
In file included from /tmp/mckernel/arch/arm64/kernel/include/arch-lock.h:12:0,
                 from /tmp/mckernel/lib/include/ihk/lock.h:16,
                 from /tmp/mckernel/lib/include/ihk/mm.h:20,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/tofu/tof_utofu_main.c:5:
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2061:15: error: dereferencing pointer to incomplete type
   __func__, tg->tof_ib_stag_lock_addr);
               ^
/tmp/mckernel/lib/include/ihk/debug.h:44:18: note: in definition of macro ‘dkprintf’
   kprintf(fmt, ##args); \
                  ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2063:16: error: dereferencing pointer to incomplete type
    __func__, tg->tof_ib_stag_list_Wp_addr);
                ^
/tmp/mckernel/lib/include/ihk/debug.h:44:18: note: in definition of macro ‘dkprintf’
   kprintf(fmt, ##args); \
                  ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2065:25: error: dereferencing pointer to incomplete type
    __func__, *((int *)tg->tof_ib_stag_list_Wp_addr));
                         ^
/tmp/mckernel/lib/include/ihk/debug.h:44:18: note: in definition of macro ‘dkprintf’
   kprintf(fmt, ##args); \
                  ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2066:55: error: dereferencing pointer to incomplete type
  kprintf("%s: linux_vmalloc_start: %p\n", __func__, tg->linux_vmalloc_start);
                                                       ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c: In function ‘tof_utofu_finalize’:
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2123:38: error: dereferencing pointer to incomplete type
  ihk_mc_clear_kernel_range((void *)tg->linux_vmalloc_start,
                                      ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:2124:14: error: dereferencing pointer to incomplete type
    (void *)tg->linux_vmalloc_end);
              ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/tofu/tof_utofu_main.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 22%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 2