Update patch set 1
Patch Set 1: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  7%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 14%] Built target ihk-smp-x86_64_ko
[ 15%] Generating kmod_always_rebuild
[ 16%] Building kmod mcctrl
[ 18%] Built target mcctrl_ko
[ 21%] Built target eclair
[ 22%] Built target ldump2mcdump
[ 23%] Built target libmcexec
[ 25%] Built target mcexec
[ 26%] Built target sched_yield
[ 28%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/syscall.c.o
In file included from /work/mcktest/git/mckernel/lib/include/ihk/cpu.h:18:0,
                 from /work/mcktest/git/mckernel/arch/x86_64/kernel/syscall.c:18:
/work/mcktest/git/mckernel/arch/x86_64/kernel/syscall.c: In function ‘arch_ptrace_syscall_enter’:
/work/mcktest/git/mckernel/arch/x86_64/kernel/syscall.c:2866:21: error: ‘ctx’ undeclared (first use in this function)
  ihk_mc_syscall_ret(ctx) = setret;
                     ^
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/ihk/context.h:51:34: note: in definition of macro ‘ihk_mc_syscall_ret’
 #define ihk_mc_syscall_ret(uc)  (uc)->gpr.rax
                                  ^
/work/mcktest/git/mckernel/arch/x86_64/kernel/syscall.c:2866:21: note: each undeclared identifier is reported only once for each function it appears in
  ihk_mc_syscall_ret(ctx) = setret;
                     ^
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/ihk/context.h:51:34: note: in definition of macro ‘ihk_mc_syscall_ret’
 #define ihk_mc_syscall_ret(uc)  (uc)->gpr.rax
                                  ^
/work/mcktest/git/mckernel/arch/x86_64/kernel/syscall.c: In function ‘arch_ptrace_syscall_exit’:
/work/mcktest/git/mckernel/arch/x86_64/kernel/syscall.c:2872:21: error: ‘ctx’ undeclared (first use in this function)
  ihk_mc_syscall_ret(ctx) = setret;
                     ^
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/ihk/context.h:51:34: note: in definition of macro ‘ihk_mc_syscall_ret’
 #define ihk_mc_syscall_ret(uc)  (uc)->gpr.rax
                                  ^
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/syscall.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 29%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1