Update patch set 3
Patch Set 3: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 11%] Generating old_timestamp, arch/x86_64/smp-x86_64-startup.o, arch/x86_64/smp-x86_64-trampoline.o, arch/x86_64/smp-arch-driver.o, smp-driver.o, arch/x86_64/.smp-x86_64-startup.o.cmd, arch/x86_64/.smp-x86_64-trampoline.o.cmd, arch/x86_64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-x86_64.o, .ihk-smp-x86_64.o.cmd, ihk-smp-x86_64.mod.c, ihk-smp-x86_64.mod.o, .ihk-smp-x86_64.mod.o.cmd, .ihk-smp-x86_64.ko.cmd, .tmp_versions/ihk-smp-x86_64.mod, .tmp_versions, modules.order
[ 12%] Building kmod ihk-smp-x86_64
/work/mcktest/git/mckernel/ihk/linux/driver/smp/arch/x86_64/smp-arch-driver.c: In function ‘smp_ihk_os_send_multi_intr’:
/work/mcktest/git/mckernel/ihk/linux/driver/smp/arch/x86_64/smp-arch-driver.c:540:6: error: unused variable ‘i’ [-Werror=unused-variable]
  int i, ret;
      ^
/work/mcktest/git/mckernel/ihk/linux/driver/smp/arch/x86_64/smp-arch-driver.c:539:22: error: unused variable ‘os’ [-Werror=unused-variable]
  struct smp_os_data *os = priv;
                      ^
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-mckernel/ihk/linux/driver/smp/arch/x86_64/smp-arch-driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/ihk/linux/driver/smp] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [ihk/linux/driver/smp/ihk-smp-x86_64.ko] Error 2
make[2]: Target `ihk/linux/driver/smp/CMakeFiles/ihk-smp-x86_64_ko.dir/build' not remade because of errors.
make[1]: *** [ihk/linux/driver/smp/CMakeFiles/ihk-smp-x86_64_ko.dir/all] Error 2
[ 13%] Generating kmod_always_rebuild
[ 15%] Building kmod mcctrl
[ 16%] Built target mcctrl_ko
[ 19%] Built target eclair
[ 20%] Built target ldump2mcdump
[ 22%] Built target libmcexec
[ 23%] Built target mcexec
[ 25%] Built target sched_yield
[ 97%] Built target mckernel.img
[ 98%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 3
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1