Update patch set 1
Patch Set 1: Verified-1

mckernel build failed:
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcctrl SUBDIRS=/tmp/build/mckernel/executer/kernel/mcctrl ARCH=x86_64 modules
make[2]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[2]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[2]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 SUBDIRS=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 ARCH=x86_64 modules
make[3]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[3]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[2]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[1]: Entering directory `/tmp/build/mckernel/executer/user'
(cd arch/x86_64; make)
make[2]: Entering directory `/tmp/build/mckernel/executer/user/arch/x86_64'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/tmp/build/mckernel/executer/user/arch/x86_64'
gcc -shared -fPIC -Wl,-soname,sched_yield.so.1 -o libsched_yield.so.1.0.0 /work/mcktest/git/mckernel/executer/user/libsched_yield.c -lc -ldl
make[1]: Leaving directory `/tmp/build/mckernel/executer/user'
make[1]: Entering directory `/tmp/build/mckernel/kernel'
make[1]: Circular /tmp/build/mckernel/kernel/build/smp-x86/kernel.img <- /tmp/build/mckernel/kernel/build/smp-x86/kernel.img dependency dropped.
Building for /tmp/build/mckernel/kernel/build/smp-x86/
 (smp-x86) DEPEND
 (smp-x86) CC /work/mcktest/git/mckernel/kernel/syscall.c
/work/mcktest/git/mckernel/kernel/syscall.c: In function ‘perf_counter_alloc’:
/work/mcktest/git/mckernel/kernel/syscall.c:3413:20: error: ‘X86_IA32_NUM_PERF_COUNTERS’ undeclared (first use in this function)
     for(i = 0; i < X86_IA32_NUM_PERF_COUNTERS; i++) {
                    ^
/work/mcktest/git/mckernel/kernel/syscall.c:3413:20: note: each undeclared identifier is reported only once for each function it appears in
/work/mcktest/git/mckernel/kernel/syscall.c: In function ‘perf_counter_start’:
/work/mcktest/git/mckernel/kernel/syscall.c:3437:51: error: ‘X86_IA32_NUM_PERF_COUNTERS’ undeclared (first use in this function)
  if(event->counter_id >= 0 && event->counter_id < X86_IA32_NUM_PERF_COUNTERS) {
                                                   ^
/work/mcktest/git/mckernel/kernel/syscall.c:3447:31: error: ‘X86_IA32_BASE_FIXED_PERF_COUNTERS’ undeclared (first use in this function)
  else if(event->counter_id >= X86_IA32_BASE_FIXED_PERF_COUNTERS &&
                               ^
/work/mcktest/git/mckernel/kernel/syscall.c:3448:59: error: ‘X86_IA32_NUM_FIXED_PERF_COUNTERS’ undeclared (first use in this function)
   event->counter_id < X86_IA32_BASE_FIXED_PERF_COUNTERS + X86_IA32_NUM_FIXED_PERF_COUNTERS) {
                                                           ^
/work/mcktest/git/mckernel/kernel/syscall.c: In function ‘perf_start’:
/work/mcktest/git/mckernel/kernel/syscall.c:3584:26: error: ‘X86_IA32_PERF_COUNTERS_MASK’ undeclared (first use in this function)
  if((1UL << counter_id & X86_IA32_PERF_COUNTERS_MASK) | 
                          ^
/work/mcktest/git/mckernel/kernel/syscall.c:3585:23: error: ‘X86_IA32_FIXED_PERF_COUNTERS_MASK’ undeclared (first use in this function)
  (1UL << counter_id & X86_IA32_FIXED_PERF_COUNTERS_MASK)) {
                       ^
/work/mcktest/git/mckernel/kernel/syscall.c: In function ‘perf_reset’:
/work/mcktest/git/mckernel/kernel/syscall.c:3606:26: error: ‘X86_IA32_PERF_COUNTERS_MASK’ undeclared (first use in this function)
  if((1UL << counter_id & X86_IA32_PERF_COUNTERS_MASK) | 
                          ^
/work/mcktest/git/mckernel/kernel/syscall.c:3607:23: error: ‘X86_IA32_FIXED_PERF_COUNTERS_MASK’ undeclared (first use in this function)
  (1UL << counter_id & X86_IA32_FIXED_PERF_COUNTERS_MASK)) {
                       ^
/work/mcktest/git/mckernel/kernel/syscall.c: In function ‘perf_stop’:
/work/mcktest/git/mckernel/kernel/syscall.c:3642:26: error: ‘X86_IA32_PERF_COUNTERS_MASK’ undeclared (first use in this function)
  if((1UL << counter_id & X86_IA32_PERF_COUNTERS_MASK) |
                          ^
/work/mcktest/git/mckernel/kernel/syscall.c:3643:23: error: ‘X86_IA32_FIXED_PERF_COUNTERS_MASK’ undeclared (first use in this function)
  (1UL << counter_id & X86_IA32_FIXED_PERF_COUNTERS_MASK)) {
                       ^
make[2]: *** [syscall.o] Error 1
 (smp-x86) BUILD IHK smp-x86
 (smp-x86) BUILD IHK smp-x86
 (smp-x86) DEPEND [IHK]
 (smp-x86) CC [IHK] /work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/perfctr.c
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/perfctr.c: In function ‘x86_init_perfctr’:
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/perfctr.c:87:4: error: ‘X86_IA32_BASE_FIXED_PERF_COUNTERS’ undeclared (first use in this function)
    X86_IA32_BASE_FIXED_PERF_COUNTERS;
    ^
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/perfctr.c:87:4: note: each undeclared identifier is reported only once for each function it appears in
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/perfctr.c: In function ‘set_pmc_x86_direct’:
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/perfctr.c:158:41: error: ‘X86_IA32_BASE_FIXED_PERF_COUNTERS’ undeclared (first use in this function)
   wrmsr(MSR_IA32_FIXED_CTR0 + counter - X86_IA32_BASE_FIXED_PERF_COUNTERS, val);
                                         ^
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/perfctr.c: In function ‘set_fixed_counter’:
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/perfctr.c:178:30: error: ‘X86_IA32_BASE_FIXED_PERF_COUNTERS’ undeclared (first use in this function)
  int counter_idx = counter - X86_IA32_BASE_FIXED_PERF_COUNTERS ;
                              ^
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/perfctr.c: In function ‘ihk_mc_perfctr_fixed_init’:
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/perfctr.c:379:30: error: ‘X86_IA32_BASE_FIXED_PERF_COUNTERS’ undeclared (first use in this function)
  int counter_idx = counter - X86_IA32_BASE_FIXED_PERF_COUNTERS ;
                              ^
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/perfctr.c: In function ‘ihk_mc_perfctr_read’:
/work/mcktest/git/mckernel/kernel/../arch/x86_64/kernel/perfctr.c:449:41: error: ‘X86_IA32_BASE_FIXED_PERF_COUNTERS’ undeclared (first use in this function)
   retval = rdpmc((1 << 30) + (counter - X86_IA32_BASE_FIXED_PERF_COUNTERS));
                                         ^
make[3]: *** [/tmp/build/mckernel/kernel/build/smp-x86/ihk/perfctr.o] Error 1
 (smp-x86) BUILD IKC [IHK] smp-x86
 (smp-x86) DEPEND [IKC]
 (smp-x86) CC [IKC] queue.c
queue.c: In function ‘ihk_ikc_free_channel’:
queue.c:425:4: error: too few arguments to function ‘ihk_mc_unmap_virtual’
    ihk_ikc_unmap_virtual(ihk_os_to_dev(os),
    ^
In file included from /work/mcktest/git/mckernel/ihk/cokernel/../ikc/include/ikc/ihk.h:41:0,
                 from queue.c:8:
/work/mcktest/git/mckernel/kernel/../lib/include/ihk/mm.h:109:6: note: declared here
 void ihk_mc_unmap_virtual(void *va, int npages, int free_physical);
      ^
queue.c:439:4: error: too few arguments to function ‘ihk_mc_unmap_virtual’
    ihk_ikc_unmap_virtual(ihk_os_to_dev(os),
    ^
In file included from /work/mcktest/git/mckernel/ihk/cokernel/../ikc/include/ikc/ihk.h:41:0,
                 from queue.c:8:
/work/mcktest/git/mckernel/kernel/../lib/include/ihk/mm.h:109:6: note: declared here
 void ihk_mc_unmap_virtual(void *va, int npages, int free_physical);
      ^
make[4]: *** [/tmp/build/mckernel/kernel/build/smp-x86/ihk/ikc/queue.o] Error 1
make[4]: Target `all' not remade because of errors.
make[3]: *** [/tmp/build/mckernel/kernel/build/smp-x86/ihk/ikc/ikc.o] Error 2
make[3]: Target `all' not remade because of errors.
make[2]: *** [ihk/ihk.o] Error 2
make[2]: Target `all' not remade because of errors.
make[1]: *** [/tmp/build/mckernel/kernel/build/smp-x86/kernel.img] Error 2
make[1]: Target `all' not remade because of errors.
rm /tmp/build/mckernel/kernel/build/smp-x86/Makefile
make[1]: Leaving directory `/tmp/build/mckernel/kernel'
make: *** [mckernel] Error 2
make[1]: Entering directory `/tmp/build/mckernel/tools/mcstat'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/tmp/build/mckernel/tools/mcstat'
make: Target `all' not remade because of errors.

Patch-set: 1
Reviewer: syssoft-gerrit@ml.riken.jp <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1