Update patch set 11
Patch Set 11: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  7%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 14%] Built target ihk-smp-x86_64_ko
[ 15%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/x86_64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/x86_64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 16%] Building kmod mcctrl
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c: In function ‘mcctrl_getrusage’:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:2424:10: error: ‘struct mcctrl_ioctl_getrusage_desc’ has no member named ‘size_rusage’
  if (desc.size_rusage > sizeof(struct ihk_os_rusage)) {
          ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:2426:24: error: ‘struct mcctrl_ioctl_getrusage_desc’ has no member named ‘size_rusage’
          __func__, desc.size_rusage,
                        ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:2432:46: error: ‘struct mcctrl_ioctl_getrusage_desc’ has no member named ‘size_rusage’
  ret = copy_to_user(desc.rusage, rusage, desc.size_rusage);
                                              ^
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/control.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 19%] Built target eclair
[ 21%] Built target ldump2mcdump
[ 22%] Built target libmcexec
[ 23%] Built target mcexec
[ 25%] Built target sched_yield
[ 97%] Built target mckernel.img
[ 98%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 11
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1