Update patch set 8
Patch Set 8: Verified-1

wallaby7: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 10%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 15%] Generating kmod_always_rebuild
[ 16%] Building kmod mcctrl
[ 17%] Built target mcctrl_ko
[ 20%] Built target eclair
[ 21%] Built target ldump2mcdump
[ 23%] Built target libmcexec
[ 24%] Built target mcexec
[ 26%] Built target mcinspect
[ 27%] Built target sched_yield
Linking C executable mckernel.img
CMakeFiles/mckernel.img.dir/init.c.o: In function `post_init':
/work/mcktest/git/mckernel/kernel/init.c:374: undefined reference to `tof_utofu_init_globals'
CMakeFiles/mckernel.img.dir/mem.c.o: In function `page_fault_handler':
/work/mcktest/git/mckernel/kernel/mem.c:1390: undefined reference to `ihk_mc_linux_pt_virt_to_phys_size'
/work/mcktest/git/mckernel/kernel/mem.c:1403: undefined reference to `ihk_mc_clear_kernel_range'
CMakeFiles/mckernel.img.dir/syscall.c.o: In function `sys_ioctl':
/work/mcktest/git/mckernel/kernel/syscall.c:3866: undefined reference to `tof_utofu_unlocked_ioctl_cq'
CMakeFiles/mckernel.img.dir/syscall.c.o: In function `sys_close':
/work/mcktest/git/mckernel/kernel/syscall.c:4019: undefined reference to `tof_utofu_release_cq'
CMakeFiles/mckernel.img.dir/syscall.c.o: In function `terminate':
/work/mcktest/git/mckernel/kernel/syscall.c:1303: undefined reference to `tof_utofu_release_cq'
CMakeFiles/mckernel.img.dir/host.c.o: In function `process_msg_prepare_process':
/work/mcktest/git/mckernel/kernel/host.c:555: undefined reference to `tof_utofu_finalize'
CMakeFiles/mckernel.img.dir/process.c.o: In function `release_process':
/work/mcktest/git/mckernel/kernel/process.c:2865: undefined reference to `tof_utofu_finalize'
make[2]: *** [kernel/mckernel.img] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 28%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 8
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1