Update patch set 1
Patch Set 1: Verified-1

setns_dummy_uts: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  5%] Built target ihklib
[  8%] Built target ihkmond
[ 10%] Built target ihkconfig
[ 12%] Built target ihkosctl
[ 14%] Generating kmod_always_rebuild
[ 15%] Building kmod ihk-smp-x86_64
[ 16%] Built target ihk-smp-x86_64_ko
[ 17%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, mc_plist.o, futex.o, arch/x86_64/archdeps.o, arch/x86_64/cpu.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, .mc_plist.o.cmd, .futex.o.cmd, arch/x86_64/.archdeps.o.cmd, arch/x86_64/.cpu.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 18%] Building kmod mcctrl
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c: In function ‘mcexec_syscall_thread’:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:2961:3: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
   long start = cntvct();
   ^
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/control.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 21%] Built target libmcexec
[ 23%] Built target mcexec
[ 25%] Built target mcinspect
[ 28%] Built target sched_yield
[ 30%] Built target ldump2mcdump
[ 34%] Built target eclair
[ 35%] Building C object kernel/CMakeFiles/mckernel.img.dir/futex.c.o
/work/mcktest/git/mckernel/kernel/futex.c: Assembler messages:
/work/mcktest/git/mckernel/kernel/futex.c:82: Error: no such instruction: `isb'
/work/mcktest/git/mckernel/kernel/futex.c:83: Error: no such instruction: `mrs %rax,cntvct_el0'
/work/mcktest/git/mckernel/kernel/futex.c:82: Error: no such instruction: `isb'
/work/mcktest/git/mckernel/kernel/futex.c:83: Error: no such instruction: `mrs %rdx,cntvct_el0'
/work/mcktest/git/mckernel/kernel/futex.c:82: Error: no such instruction: `isb'
/work/mcktest/git/mckernel/kernel/futex.c:83: Error: no such instruction: `mrs %rax,cntvct_el0'
/work/mcktest/git/mckernel/kernel/futex.c:82: Error: no such instruction: `isb'
/work/mcktest/git/mckernel/kernel/futex.c:83: Error: no such instruction: `mrs %rdx,cntvct_el0'
/work/mcktest/git/mckernel/kernel/futex.c:82: Error: no such instruction: `isb'
/work/mcktest/git/mckernel/kernel/futex.c:83: Error: no such instruction: `mrs %rbx,cntvct_el0'
/work/mcktest/git/mckernel/kernel/futex.c:82: Error: no such instruction: `isb'
/work/mcktest/git/mckernel/kernel/futex.c:83: Error: no such instruction: `mrs %rdx,cntvct_el0'
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/futex.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 37%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1