Update patch set 7
Patch Set 7: Test-arm64-1

ARM MCKERNEL : mckernel-refs-changes-42-442842-7-?
IHK      : ihk-refs-changes-42-442842-7-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/442842/7 // a79ab78bd5c0d965daebabb1bca83e6a163277d9
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6 -m 58G@0,58G@1 -c 4-27,32-55 -r 4-9:0+10-15:1+16-21:2+22-27:3+32-37:28+38-43:29+44-49:30+50-55:31 -O
HOST  : apollo15.postk.local.r-ccs.riken.jp
DIR   : /work/mcktest/work_refs-changes-42-442842-7_submodule
START : 20200422131937
END   : 20200422132003

/work/mcktest/git /work/mcktest/bin
Cloning into 'mckernel'...
Total 31452 (delta 20385), reused 31083 (delta 20385)
Total 39 (delta 21), reused 37 (delta 21)
From ssh://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/42/442842/7 -> FETCH_HEAD
/work/mcktest/bin
HEAD is now at a79ab78b prepare_process: Load executables with mmap
ihk: submodule commit resolved to refs-changes-08-446808-2
/work/mcktest/git /work/mcktest/bin
Cloning into 'ihk'...
Total 6649 (delta 4582), reused 6491 (delta 4582)
From ssh://review.gerrithub.io/RIKEN-SysSoft/ihk
 * branch            refs/changes/08/446808/2 -> FETCH_HEAD
/work/mcktest/bin
HEAD is now at 0681d7a cmake: change how warning flags are added
MCKBUILD=/work/mcktest/work_refs-changes-42-442842-7_submodule/build
MCKINSTALL=/home/toshi/install/dev2-mckernel
-- The C compiler identification is GNU 4.8.5
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Performing Test IMPLICIT_FALLTHROUGH
-- Performing Test IMPLICIT_FALLTHROUGH - Success
Host kernel CONFIG_ARM64_64K_PAGES=y
Host kernel CONFIG_ARM64_VA_BITS=48
Defined module ihk
Defined module ihk-smp-arm64
Defined module mcctrl
Host kernel CONFIG_NR_CPUS=4096
Host kernel CONFIG_HZ=100
-------------------------------
Option summary
-------------------------------
Build type: Debug
Build target: smp-arm64
IHK_SOURCE_DIR: ../ihk (relative to mckernel source tree)
UNAME_R: 4.14.0-115.13.1.1chaos.el7a.aarch64
KERNEL_DIR: /lib/modules/4.14.0-115.13.1.1chaos.el7a.aarch64/build
SYSTEM_MAP: 
VMLINUX: 
KBUILD_C_FLAGS:  -DPOSTK_DEBUG_ARCH_DEP_1 -DPOSTK_DEBUG_TEMP_FIX_1 -DPOSTK_DEBUG_ARCH_DEP_2 -DPOSTK_DEBUG_TEMP_FIX_2 -DPOSTK_DEBUG_ARCH_DEP_3 -DPOSTK_DEBUG_TEMP_FIX_3 -DPOSTK_DEBUG_ARCH_DEP_4 -DPOSTK_DEBUG_TEMP_FIX_4 -DPOSTK_DEBUG_ARCH_DEP_5 -DPOSTK_DEBUG_TEMP_FIX_5 -DPOSTK_DEBUG_ARCH_DEP_6 -DPOSTK_DEBUG_TEMP_FIX_6 -DPOSTK_DEBUG_ARCH_DEP_7 -DPOSTK_DEBUG_TEMP_FIX_7 -DPOSTK_DEBUG_ARCH_DEP_8 -DPOSTK_DEBUG_TEMP_FIX_8 -DPOSTK_DEBUG_ARCH_DEP_9 -DPOSTK_DEBUG_TEMP_FIX_9 -DPOSTK_DEBUG_ARCH_DEP_10 -DPOSTK_DEBUG_TEMP_FIX_10 -DPOSTK_DEBUG_ARCH_DEP_11 -DPOSTK_DEBUG_TEMP_FIX_11 -DPOSTK_DEBUG_ARCH_DEP_12 -DPOSTK_DEBUG_TEMP_FIX_12 -DPOSTK_DEBUG_ARCH_DEP_13 -DPOSTK_DEBUG_TEMP_FIX_13 -DPOSTK_DEBUG_ARCH_DEP_14 -DPOSTK_DEBUG_TEMP_FIX_14 -DPOSTK_DEBUG_ARCH_DEP_15 -DPOSTK_DEBUG_TEMP_FIX_15 -DPOSTK_DEBUG_ARCH_DEP_16 -DPOSTK_DEBUG_TEMP_FIX_16 -DPOSTK_DEBUG_ARCH_DEP_17 -DPOSTK_DEBUG_TEMP_FIX_17 -DPOSTK_DEBUG_ARCH_DEP_18 -DPOSTK_DEBUG_TEMP_FIX_18 -DPOSTK_DEBUG_ARCH_DEP_19 -DPOSTK_DEBUG_TEMP_FIX_19 -DPOSTK_DEBUG_ARCH_DEP_20 -DPOSTK_DEBUG_TEMP_FIX_20 -DPOSTK_DEBUG_ARCH_DEP_21 -DPOSTK_DEBUG_TEMP_FIX_21 -DPOSTK_DEBUG_ARCH_DEP_22 -DPOSTK_DEBUG_TEMP_FIX_22 -DPOSTK_DEBUG_ARCH_DEP_23 -DPOSTK_DEBUG_TEMP_FIX_23 -DPOSTK_DEBUG_ARCH_DEP_24 -DPOSTK_DEBUG_TEMP_FIX_24 -DPOSTK_DEBUG_ARCH_DEP_25 -DPOSTK_DEBUG_TEMP_FIX_25 -DPOSTK_DEBUG_ARCH_DEP_26 -DPOSTK_DEBUG_TEMP_FIX_26 -DPOSTK_DEBUG_ARCH_DEP_27 -DPOSTK_DEBUG_TEMP_FIX_27 -DPOSTK_DEBUG_ARCH_DEP_28 -DPOSTK_DEBUG_TEMP_FIX_28 -DPOSTK_DEBUG_ARCH_DEP_29 -DPOSTK_DEBUG_TEMP_FIX_29 -DPOSTK_DEBUG_ARCH_DEP_30 -DPOSTK_DEBUG_TEMP_FIX_30 -DPOSTK_DEBUG_ARCH_DEP_31 -DPOSTK_DEBUG_TEMP_FIX_31 -DPOSTK_DEBUG_ARCH_DEP_32 -DPOSTK_DEBUG_TEMP_FIX_32 -DPOSTK_DEBUG_ARCH_DEP_33 -DPOSTK_DEBUG_TEMP_FIX_33 -DPOSTK_DEBUG_ARCH_DEP_34 -DPOSTK_DEBUG_TEMP_FIX_34 -DPOSTK_DEBUG_ARCH_DEP_35 -DPOSTK_DEBUG_TEMP_FIX_35 -DPOSTK_DEBUG_ARCH_DEP_36 -DPOSTK_DEBUG_TEMP_FIX_36 -DPOSTK_DEBUG_ARCH_DEP_37 -DPOSTK_DEBUG_TEMP_FIX_37 -DPOSTK_DEBUG_ARCH_DEP_38 -DPOSTK_DEBUG_TEMP_FIX_38 -DPOSTK_DEBUG_ARCH_DEP_39 -DPOSTK_DEBUG_TEMP_FIX_39 -DPOSTK_DEBUG_ARCH_DEP_40 -DPOSTK_DEBUG_TEMP_FIX_40 -DPOSTK_DEBUG_ARCH_DEP_41 -DPOSTK_DEBUG_TEMP_FIX_41 -DPOSTK_DEBUG_ARCH_DEP_42 -DPOSTK_DEBUG_TEMP_FIX_42 -DPOSTK_DEBUG_ARCH_DEP_43 -DPOSTK_DEBUG_TEMP_FIX_43 -DPOSTK_DEBUG_ARCH_DEP_44 -DPOSTK_DEBUG_TEMP_FIX_44 -DPOSTK_DEBUG_ARCH_DEP_45 -DPOSTK_DEBUG_TEMP_FIX_45 -DPOSTK_DEBUG_ARCH_DEP_46 -DPOSTK_DEBUG_TEMP_FIX_46 -DPOSTK_DEBUG_ARCH_DEP_47 -DPOSTK_DEBUG_TEMP_FIX_47 -DPOSTK_DEBUG_ARCH_DEP_48 -DPOSTK_DEBUG_TEMP_FIX_48 -DPOSTK_DEBUG_ARCH_DEP_49 -DPOSTK_DEBUG_TEMP_FIX_49 -DPOSTK_DEBUG_ARCH_DEP_50 -DPOSTK_DEBUG_TEMP_FIX_50 -DPOSTK_DEBUG_ARCH_DEP_51 -DPOSTK_DEBUG_TEMP_FIX_51 -DPOSTK_DEBUG_ARCH_DEP_52 -DPOSTK_DEBUG_TEMP_FIX_52 -DPOSTK_DEBUG_ARCH_DEP_53 -DPOSTK_DEBUG_TEMP_FIX_53 -DPOSTK_DEBUG_ARCH_DEP_54 -DPOSTK_DEBUG_TEMP_FIX_54 -DPOSTK_DEBUG_ARCH_DEP_55 -DPOSTK_DEBUG_TEMP_FIX_55 -DPOSTK_DEBUG_ARCH_DEP_56 -DPOSTK_DEBUG_TEMP_FIX_56 -DPOSTK_DEBUG_ARCH_DEP_57 -DPOSTK_DEBUG_TEMP_FIX_57 -DPOSTK_DEBUG_ARCH_DEP_58 -DPOSTK_DEBUG_TEMP_FIX_58 -DPOSTK_DEBUG_ARCH_DEP_59 -DPOSTK_DEBUG_TEMP_FIX_59 -DPOSTK_DEBUG_ARCH_DEP_60 -DPOSTK_DEBUG_TEMP_FIX_60 -DPOSTK_DEBUG_ARCH_DEP_61 -DPOSTK_DEBUG_TEMP_FIX_61 -DPOSTK_DEBUG_ARCH_DEP_62 -DPOSTK_DEBUG_TEMP_FIX_62 -DPOSTK_DEBUG_ARCH_DEP_63 -DPOSTK_DEBUG_TEMP_FIX_63 -DPOSTK_DEBUG_ARCH_DEP_64 -DPOSTK_DEBUG_TEMP_FIX_64 -DPOSTK_DEBUG_ARCH_DEP_65 -DPOSTK_DEBUG_TEMP_FIX_65 -DPOSTK_DEBUG_ARCH_DEP_66 -DPOSTK_DEBUG_TEMP_FIX_66 -DPOSTK_DEBUG_ARCH_DEP_67 -DPOSTK_DEBUG_TEMP_FIX_67 -DPOSTK_DEBUG_ARCH_DEP_68 -DPOSTK_DEBUG_TEMP_FIX_68 -DPOSTK_DEBUG_ARCH_DEP_69 -DPOSTK_DEBUG_TEMP_FIX_69 -DPOSTK_DEBUG_ARCH_DEP_70 -DPOSTK_DEBUG_TEMP_FIX_70 -DPOSTK_DEBUG_ARCH_DEP_71 -DPOSTK_DEBUG_TEMP_FIX_71 -DPOSTK_DEBUG_ARCH_DEP_72 -DPOSTK_DEBUG_TEMP_FIX_72 -DPOSTK_DEBUG_ARCH_DEP_73 -DPOSTK_DEBUG_TEMP_FIX_73 -DPOSTK_DEBUG_ARCH_DEP_74 -DPOSTK_DEBUG_TEMP_FIX_74 -DPOSTK_DEBUG_ARCH_DEP_75 -DPOSTK_DEBUG_TEMP_FIX_75 -DPOSTK_DEBUG_ARCH_DEP_76 -DPOSTK_DEBUG_TEMP_FIX_76 -DPOSTK_DEBUG_ARCH_DEP_77 -DPOSTK_DEBUG_TEMP_FIX_77 -DPOSTK_DEBUG_ARCH_DEP_78 -DPOSTK_DEBUG_TEMP_FIX_78 -DPOSTK_DEBUG_ARCH_DEP_79 -DPOSTK_DEBUG_TEMP_FIX_79 -DPOSTK_DEBUG_ARCH_DEP_80 -DPOSTK_DEBUG_TEMP_FIX_80 -DPOSTK_DEBUG_ARCH_DEP_81 -DPOSTK_DEBUG_TEMP_FIX_81 -DPOSTK_DEBUG_ARCH_DEP_82 -DPOSTK_DEBUG_TEMP_FIX_82 -DPOSTK_DEBUG_ARCH_DEP_83 -DPOSTK_DEBUG_TEMP_FIX_83 -DPOSTK_DEBUG_ARCH_DEP_84 -DPOSTK_DEBUG_TEMP_FIX_84 -DPOSTK_DEBUG_ARCH_DEP_85 -DPOSTK_DEBUG_TEMP_FIX_85 -DPOSTK_DEBUG_ARCH_DEP_86 -DPOSTK_DEBUG_TEMP_FIX_86 -DPOSTK_DEBUG_ARCH_DEP_87 -DPOSTK_DEBUG_TEMP_FIX_87 -DPOSTK_DEBUG_ARCH_DEP_88 -DPOSTK_DEBUG_TEMP_FIX_88 -DPOSTK_DEBUG_ARCH_DEP_89 -DPOSTK_DEBUG_TEMP_FIX_89 -DPOSTK_DEBUG_ARCH_DEP_90 -DPOSTK_DEBUG_TEMP_FIX_90 -DPOSTK_DEBUG_ARCH_DEP_91 -DPOSTK_DEBUG_TEMP_FIX_91 -DPOSTK_DEBUG_ARCH_DEP_92 -DPOSTK_DEBUG_TEMP_FIX_92 -DPOSTK_DEBUG_ARCH_DEP_93 -DPOSTK_DEBUG_TEMP_FIX_93 -DPOSTK_DEBUG_ARCH_DEP_94 -DPOSTK_DEBUG_TEMP_FIX_94 -DPOSTK_DEBUG_ARCH_DEP_95 -DPOSTK_DEBUG_TEMP_FIX_95 -DPOSTK_DEBUG_ARCH_DEP_96 -DPOSTK_DEBUG_TEMP_FIX_96 -DPOSTK_DEBUG_ARCH_DEP_97 -DPOSTK_DEBUG_TEMP_FIX_97 -DPOSTK_DEBUG_ARCH_DEP_98 -DPOSTK_DEBUG_TEMP_FIX_98 -DPOSTK_DEBUG_ARCH_DEP_99 -DPOSTK_DEBUG_TEMP_FIX_99 -DPOSTK_DEBUG_ARCH_DEP_100 -DPOSTK_DEBUG_TEMP_FIX_100 -DPOSTK_DEBUG_ARCH_DEP_101 -DPOSTK_DEBUG_TEMP_FIX_101 -DPOSTK_DEBUG_ARCH_DEP_102 -DPOSTK_DEBUG_TEMP_FIX_102 -DPOSTK_DEBUG_ARCH_DEP_103 -DPOSTK_DEBUG_TEMP_FIX_103 -DPOSTK_DEBUG_ARCH_DEP_104 -DPOSTK_DEBUG_TEMP_FIX_104 -DPOSTK_DEBUG_ARCH_DEP_105 -DPOSTK_DEBUG_TEMP_FIX_105 -DPOSTK_DEBUG_ARCH_DEP_106 -DPOSTK_DEBUG_TEMP_FIX_106 -DPOSTK_DEBUG_ARCH_DEP_107 -DPOSTK_DEBUG_TEMP_FIX_107 -DPOSTK_DEBUG_ARCH_DEP_108 -DPOSTK_DEBUG_TEMP_FIX_108 -DPOSTK_DEBUG_ARCH_DEP_109 -DPOSTK_DEBUG_TEMP_FIX_109 -DPOSTK_DEBUG_ARCH_DEP_110 -DPOSTK_DEBUG_TEMP_FIX_110 -DPOSTK_DEBUG_ARCH_DEP_111 -DPOSTK_DEBUG_TEMP_FIX_111 -DPOSTK_DEBUG_ARCH_DEP_112 -DPOSTK_DEBUG_TEMP_FIX_112 -DPOSTK_DEBUG_ARCH_DEP_113 -DPOSTK_DEBUG_TEMP_FIX_113 -DPOSTK_DEBUG_ARCH_DEP_114 -DPOSTK_DEBUG_TEMP_FIX_114 -DPOSTK_DEBUG_ARCH_DEP_115 -DPOSTK_DEBUG_TEMP_FIX_115 -DPOSTK_DEBUG_ARCH_DEP_116 -DPOSTK_DEBUG_TEMP_FIX_116 -DPOSTK_DEBUG_ARCH_DEP_117 -DPOSTK_DEBUG_TEMP_FIX_117 -DPOSTK_DEBUG_ARCH_DEP_118 -DPOSTK_DEBUG_TEMP_FIX_118 -DPOSTK_DEBUG_ARCH_DEP_119 -DPOSTK_DEBUG_TEMP_FIX_119 -DPOSTK_DEBUG_ARCH_DEP_120 -DPOSTK_DEBUG_TEMP_FIX_120
ENABLE_MEMDUMP: ON
ENABLE_PERF: ON
ENABLE_RUSAGE: ON
ENABLE_QLMPI: OFF
ENABLE_UTI: OFF
ENABLE_WERROR: OFF
ENABLE_UBSAN: OFF
-------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /work/mcktest/work_refs-changes-42-442842-7_submodule/build/4.14.0-115.13.1.1chaos.el7a.aarch64
Scanning dependencies of target ihk_ko
Scanning dependencies of target libmcexec
Scanning dependencies of target sched_yield
Scanning dependencies of target eclair
Scanning dependencies of target ihklib
Scanning dependencies of target ldump2mcdump
[  1%] [  2%] [  3%] [  4%] [  5%] [  7%] [  7%] [  8%] Generating old_timestamp, host_driver.o, mem_alloc.o, mm.o, mikc.o, ../../ikc/linux.o, ../../ikc/master.o, ../../ikc/queue.o, .host_driver.o.cmd, .mem_alloc.o.cmd, .mm.o.cmd, .mikc.o.cmd, ../../ikc/.linux.o.cmd, ../../ikc/.master.o.cmd, ../../ikc/.queue.o.cmd, ihk.o, .ihk.o.cmd, ihk.mod.c, ihk.mod.o, .ihk.mod.o.cmd, .ihk.ko.cmd, .tmp_versions/ihk.mod, .tmp_versions, modules.order
Generating kmod_always_rebuild
Building ASM object executer/user/CMakeFiles/libmcexec.dir/arch/arm64/archdep.S.o
Building C object executer/user/CMakeFiles/sched_yield.dir/libsched_yield.c.o
Building C object executer/user/CMakeFiles/eclair.dir/eclair.c.o
Building C object executer/user/CMakeFiles/eclair.dir/arch/arm64/arch-eclair.c.o
Building C object ihk/linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
Building C object executer/user/CMakeFiles/ldump2mcdump.dir/ldump2mcdump.c.o
[  9%] Building kmod ihk
Linking ASM static library libmcexec.a
Linking C shared library libsched_yield.so
[  9%] Built target libmcexec
[  9%] Built target sched_yield
Linking C shared library libldump2mcdump.so
Linking C executable eclair
[  9%] Built target ldump2mcdump
Scanning dependencies of target mckernel.img
[  9%] Built target eclair
[ 10%] [ 11%] [ 14%] [ 14%] [ 14%] [ 15%] [ 16%] [ 17%] [ 18%] [ 20%] [ 21%] [ 22%] [ 23%] [ 24%] [ 25%] [ 26%] [ 27%] [ 28%] Building C object kernel/CMakeFiles/mckernel.img.dir/init.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/mikc.c.o
[ 29%] Building C object kernel/CMakeFiles/mckernel.img.dir/listeners.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/mem.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/debug.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/ap.c.o
[ 30%] Building C object kernel/CMakeFiles/mckernel.img.dir/syscall.c.o
[ 31%] Building C object kernel/CMakeFiles/mckernel.img.dir/cls.c.o
[ 32%] Building C object kernel/CMakeFiles/mckernel.img.dir/host.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/process.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/copy.c.o
[ 33%] Building C object kernel/CMakeFiles/mckernel.img.dir/futex.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/waitq.c.o
[ 34%] Building C object kernel/CMakeFiles/mckernel.img.dir/timer.c.o
[ 35%] Building C object kernel/CMakeFiles/mckernel.img.dir/plist.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/fileobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/shmobj.c.o
[ 36%] Building C object kernel/CMakeFiles/mckernel.img.dir/zeroobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/procfs.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/devobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/sysfs.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/freeze.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/profile.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/rbtree.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/pager.c.o
[ 37%] [ 38%] [ 42%] [ 42%] [ 42%] [ 43%] [ 44%] [ 45%] [ 46%] [ 47%] [ 48%] [ 49%] Building C object kernel/CMakeFiles/mckernel.img.dir/hugefileobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-42-442842-7_submodule/src/ihk/ikc/manycore.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/gencore.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-42-442842-7_submodule/src/ihk/ikc/master.c.o
[ 50%] Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-42-442842-7_submodule/src/ihk/ikc/queue.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/bitmap.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/abort.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/string.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/page_alloc.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/bitops.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-42-442842-7_submodule/src/ihk/cokernel/smp/arm64/dma.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/vsprintf.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-42-442842-7_submodule/src/ihk/cokernel/smp/arm64/ikc.c.o
[ 51%] [ 52%] Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-42-442842-7_submodule/src/ihk/cokernel/smp/arm64/setup.c.o
[ 53%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/assert.c.o
[ 54%] [ 55%] Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/cache.S.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/context.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/coredump.c.o
[ 56%] [ 57%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/cpu.c.o
[ 58%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/cpufeature.c.o
[ 60%] [ 61%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/cputable.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/debug-monitors.c.o
Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/entry-fpsimd.S.o
Linking C shared library libihk.so
[ 62%] [ 63%] [ 64%] [ 65%] [ 66%] Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/entry.S.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/fault.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/fpsimd.c.o
Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/head.S.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/hw_breakpoint.c.o
[ 68%] [ 68%] [ 69%] Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/hyp-stub.S.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/imp-sysreg.c.o
[ 70%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/irq-gic-v2.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/irq-gic-v3.c.o
[ 71%] [ 72%] [ 73%] [ 74%] Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/memcpy.S.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/memory.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/local.c.o
Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/memset.S.o
[ 75%] [ 76%] [ 77%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/mikc.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/perfctr.c.o
[ 78%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/perfctr_armv8pmu.c.o
[ 80%] [ 81%] [ 82%] Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/proc-macros.S.o
[ 83%] Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/proc.S.o
[ 84%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/psci.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/ptrace.c.o
[ 84%] Built target ihklib
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/smp.c.o
[ 85%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/syscall.c.o
[ 86%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/timer.c.o
Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/trampoline.S.o
Scanning dependencies of target ihkconfig
Scanning dependencies of target ihkmond
Scanning dependencies of target ihkosctl
[ 88%] [ 88%] [ 89%] [ 90%] [ 91%] Scanning dependencies of target mcstat
Scanning dependencies of target mcexec
Building C object ihk/linux/user/CMakeFiles/ihkconfig.dir/ihkconfig.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/traps.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/vdso.c.o
Building C object ihk/linux/user/CMakeFiles/ihkmond.dir/ihkmond.c.o
Building C object ihk/linux/user/CMakeFiles/ihkosctl.dir/ihkosctl.c.o
[ 92%] [ 93%] Building C object tools/mcstat/CMakeFiles/mcstat.dir/mcstat.c.o
Building C object executer/user/CMakeFiles/mcexec.dir/mcexec.c.o
Linking C executable mcstat
Linking C executable ihkconfig
[ 93%] Built target mcstat
Linking C executable ihkosctl
[ 93%] Built target ihkconfig
Linking C executable ihkmond
[ 93%] Built target ihkosctl
[ 93%] Built target ihkmond
Linking C executable mcexec
[ 93%] Built target mcexec
[ 93%] Built target ihk_ko
Scanning dependencies of target mcctrl_ko
Scanning dependencies of target ihk-smp-arm64_ko
[ 94%] [ 95%] [ 97%] [ 97%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/arm64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/arm64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
Generating kmod_always_rebuild
Generating kmod_always_rebuild
Generating old_timestamp, arch/arm64/smp-arm64-startup.o, arch/arm64/smp-arm64-trampoline.o, arch/arm64/smp-arch-driver.o, smp-driver.o, arch/arm64/.smp-arm64-startup.o.cmd, arch/arm64/.smp-arm64-trampoline.o.cmd, arch/arm64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-arm64.o, .ihk-smp-arm64.o.cmd, ihk-smp-arm64.mod.c, ihk-smp-arm64.mod.o, .ihk-smp-arm64.mod.o.cmd, .ihk-smp-arm64.ko.cmd, .tmp_versions/ihk-smp-arm64.mod, .tmp_versions, modules.order
[100%] [100%] Building kmod ihk-smp-arm64
Building kmod mcctrl
Linking C executable mckernel.img
[100%] Built target mckernel.img
[100%] Built target mcctrl_ko
[100%] Built target ihk-smp-arm64_ko
Install the project...
-- Install configuration: "Debug"
-- Installing: /home/toshi/install/dev2-mckernel/sbin/mcreboot.sh
CMake Error at cmake_install.cmake:36 (FILE):
  file INSTALL cannot copy file
  "/work/mcktest/work_refs-changes-42-442842-7_submodule/build/4.14.0-115.13.1.1chaos.el7a.aarch64/mcreboot.sh"
  to "/home/toshi/install/dev2-mckernel/sbin/mcreboot.sh".


make: *** [install] Error 1
ERROR: autobuild.sh failed

Patch-set: 7
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Test-arm64=-1