Update patch set 1
Patch Set 1: Test-x86-1

MCKERNEL : mckernel-refs-changes-77-510077-1-?
IHK      : ihk-refs-changes-77-510077-1-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/510077/1 // e3b5d7656154ea73ea666d64521abe93ea5ac489
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_refs-changes-77-510077-1_submodule
START : 20210216154224
END   : 20210216154258

+++ dirname /work/mcktest/bin/autobuild.sh
++ cd /work/mcktest/bin/..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ pwd
+ CWD=/
++ dirname /work/mcktest/bin/autobuild.sh
+ cd /work/mcktest/bin
+ . ./config.sh
+++ shopt -po xtrace
++ tracestate='set -o xtrace'
++ echo set -o xtrace
++ grep -q -
++ set +x
+ export BINDIR=
+ BINDIR=
+ bash -x ./wget-postpeta.sh mckernel refs-changes-77-510077-1
++ pwd
+ CWD=/work/mcktest/bin
+++ dirname ./wget-postpeta.sh
++ cd ./..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ dirname ./wget-postpeta.sh
+ cd .
+ . ./config.sh
+++ shopt -po xtrace
++ tracestate='set -o xtrace'
++ echo set -o xtrace
++ grep -q -
++ set +x
+ forwatchgerrit=0
+ REPO=mckernel
+ BRANCH=refs-changes-77-510077-1
+ case "$BRANCH" in
+ remote_type=gerrit-git
+ PATHSPEC=refs/changes/77/510077/1
+ '[' /work/mcktest/work_refs-changes-77-510077-1_submodule/src == '' ']'
+ '[' mckernel == '' ']'
+ DEST=mckernel
+ [[ -d /work/mcktest/work_refs-changes-77-510077-1_submodule/src ]]
+ mkdir /work/mcktest/work_refs-changes-77-510077-1_submodule/src
+ rm -rf '/work/mcktest/work_refs-changes-77-510077-1_submodule/src/mckernel-*'
+ case $NODETYPE in
+ case $remote_type in
+ pushd /work/mcktest/git
/work/mcktest/git /work/mcktest/bin
+ sudo -u mcktest rm -rf mckernel
+ sudo -u mcktest git clone ssh://riken-syssoft-gerrit@review.gerrithub.io/RIKEN-SysSoft/mckernel
Cloning into 'mckernel'...
Total 33104 (delta 21340), reused 32583 (delta 21340)
+ cd mckernel
+ sudo -u mcktest git fetch origin refs/changes/77/510077/1
Total 20 (delta 7), reused 20 (delta 7)
From ssh://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/77/510077/1 -> FETCH_HEAD
++ sudo -u mcktest git rev-parse FETCH_HEAD
+ COMMIT=e3b5d7656154ea73ea666d64521abe93ea5ac489
+ DEST=mckernel-refs-changes-77-510077-1-e3b5d7656154ea73ea666d64521abe93ea5ac489
+ popd
/work/mcktest/bin
+ '[' 0 -ne 0 ']'
+ '[' 0 -eq 1 ']'
+ case $remote_type in
+ mkdir /work/mcktest/work_refs-changes-77-510077-1_submodule/src/mckernel-refs-changes-77-510077-1-e3b5d7656154ea73ea666d64521abe93ea5ac489
+ cd /work/mcktest/work_refs-changes-77-510077-1_submodule/src/mckernel-refs-changes-77-510077-1-e3b5d7656154ea73ea666d64521abe93ea5ac489
+ GIT_DIR=/work/mcktest/git/mckernel/.git
+ git reset --hard e3b5d7656154ea73ea666d64521abe93ea5ac489
HEAD is now at e3b5d76 migrate: Don't migrate on in-kernel interrupt
+ GIT_DIR=/work/mcktest/git/mckernel/.git
+ git submodule update --init
Submodule 'executer/user/lib/libdwarf/libdwarf' (https://github.com/bgerofi/libdwarf.git) registered for path 'executer/user/lib/libdwarf/libdwarf'
Submodule 'ihk' (https://github.com/RIKEN-SysSoft/ihk.git) registered for path 'ihk'
Cloning into 'executer/user/lib/libdwarf/libdwarf'...
Submodule path 'executer/user/lib/libdwarf/libdwarf': checked out 'ab9230b2b8aa66a3d1d52e4be11fca17a3b63753'
Cloning into 'ihk'...
Submodule path 'ihk': checked out 'efacf4fceb239713063aa013252bf98a513b3b40'
+ cd /work/mcktest/bin
+ exit 0
+ [[ submodule == \s\u\b\m\o\d\u\l\e ]]
+ read subref _
++ cd /work/mcktest/work_refs-changes-77-510077-1_submodule/src/mckernel-refs-changes-77-510077-1-e3b5d7656154ea73ea666d64521abe93ea5ac489
++ GIT_DIR=/work/mcktest/git/mckernel/.git
++ /work/mcktest/tools/bin/git submodule status
++ awk '$2 == "ihk" {print}'
+ SUBMODULE_HASH=efacf4fceb239713063aa013252bf98a513b3b40
++ ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io 'gerrit query --format=TEXT --current-patch-set --commit-message commit:efacf4fceb239713063aa013252bf98a513b3b40'
++ awk '/ref:/ { print $2 }'
+ SUBMODULE_PATHSPEC=refs/changes/09/509609/3
+ [[ refs/changes/09/509609/3 != '' ]]
+ IHKBRANCH=refs-changes-09-509609-3
+ echo 'ihk: submodule commit resolved to refs-changes-09-509609-3'
ihk: submodule commit resolved to refs-changes-09-509609-3
+ [[ -n refs-changes-09-509609-3 ]]
+ case "$IHKBRANCH" in
+ bash -x ./wget-postpeta.sh ihk refs-changes-09-509609-3
++ pwd
+ CWD=/work/mcktest/bin
+++ dirname ./wget-postpeta.sh
++ cd ./..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ dirname ./wget-postpeta.sh
+ cd .
+ . ./config.sh
+++ shopt -po xtrace
++ tracestate='set -o xtrace'
++ echo set -o xtrace
++ grep -q -
++ set +x
+ forwatchgerrit=0
+ REPO=ihk
+ BRANCH=refs-changes-09-509609-3
+ case "$BRANCH" in
+ remote_type=gerrit-git
+ PATHSPEC=refs/changes/09/509609/3
+ '[' /work/mcktest/work_refs-changes-77-510077-1_submodule/src == '' ']'
+ '[' ihk == '' ']'
+ DEST=ihk
+ [[ -d /work/mcktest/work_refs-changes-77-510077-1_submodule/src ]]
+ rm -rf '/work/mcktest/work_refs-changes-77-510077-1_submodule/src/ihk-*'
+ case $NODETYPE in
+ case $remote_type in
+ pushd /work/mcktest/git
/work/mcktest/git /work/mcktest/bin
+ sudo -u mcktest rm -rf ihk
+ sudo -u mcktest git clone ssh://riken-syssoft-gerrit@review.gerrithub.io/RIKEN-SysSoft/ihk
Cloning into 'ihk'...
Total 9827 (delta 7241), reused 9614 (delta 7241)
+ cd ihk
+ sudo -u mcktest git fetch origin refs/changes/09/509609/3
From ssh://review.gerrithub.io/RIKEN-SysSoft/ihk
 * branch            refs/changes/09/509609/3 -> FETCH_HEAD
++ sudo -u mcktest git rev-parse FETCH_HEAD
+ COMMIT=efacf4fceb239713063aa013252bf98a513b3b40
+ DEST=ihk-refs-changes-09-509609-3-efacf4fceb239713063aa013252bf98a513b3b40
+ popd
/work/mcktest/bin
+ '[' 0 -ne 0 ']'
+ '[' 0 -eq 1 ']'
+ case $remote_type in
+ mkdir /work/mcktest/work_refs-changes-77-510077-1_submodule/src/ihk-refs-changes-09-509609-3-efacf4fceb239713063aa013252bf98a513b3b40
+ cd /work/mcktest/work_refs-changes-77-510077-1_submodule/src/ihk-refs-changes-09-509609-3-efacf4fceb239713063aa013252bf98a513b3b40
+ GIT_DIR=/work/mcktest/git/ihk/.git
+ git reset --hard efacf4fceb239713063aa013252bf98a513b3b40
HEAD is now at efacf4f SMP: __ihk_smp_reserve_mem: report only summary of __GFP_ATOMIC allocations
+ GIT_DIR=/work/mcktest/git/ihk/.git
+ git submodule update --init
+ cd /work/mcktest/bin
+ exit 0
++ head -n1
++ ls -dt /work/mcktest/work_refs-changes-77-510077-1_submodule/src/ihk-refs-changes-09-509609-3-efacf4fceb239713063aa013252bf98a513b3b40
++ xargs -r basename
+ IHKHEAD=ihk-refs-changes-09-509609-3-efacf4fceb239713063aa013252bf98a513b3b40
++ head -n1
++ ls -dt /work/mcktest/work_refs-changes-77-510077-1_submodule/src/mckernel-refs-changes-77-510077-1-e3b5d7656154ea73ea666d64521abe93ea5ac489
++ xargs -r basename
+ MCKERNELHEAD=mckernel-refs-changes-77-510077-1-e3b5d7656154ea73ea666d64521abe93ea5ac489
+ '[' -f /work/mcktest/work_refs-changes-77-510077-1_submodule/mck/ihk-refs-changes-09-509609-3-efacf4fceb239713063aa013252bf98a513b3b40 ']'
+ rm -f /work/mcktest/work_refs-changes-77-510077-1_submodule/src/ihk
+ rm -f /work/mcktest/work_refs-changes-77-510077-1_submodule/src/mckernel
+ '[' '!' -d /work/mcktest/work_refs-changes-77-510077-1_submodule/src/ihk-refs-changes-09-509609-3-efacf4fceb239713063aa013252bf98a513b3b40 ']'
+ ln -s ihk-refs-changes-09-509609-3-efacf4fceb239713063aa013252bf98a513b3b40 /work/mcktest/work_refs-changes-77-510077-1_submodule/src/ihk
+ '[' '!' -d /work/mcktest/work_refs-changes-77-510077-1_submodule/src/mckernel-refs-changes-77-510077-1-e3b5d7656154ea73ea666d64521abe93ea5ac489 ']'
+ ln -s mckernel-refs-changes-77-510077-1-e3b5d7656154ea73ea666d64521abe93ea5ac489 /work/mcktest/work_refs-changes-77-510077-1_submodule/src/mckernel
+ rm -rf /work/mcktest/work_refs-changes-77-510077-1_submodule/src/mckernel/ihk
+ echo MCKBUILD=/work/mcktest/work_refs-changes-77-510077-1_submodule/build
MCKBUILD=/work/mcktest/work_refs-changes-77-510077-1_submodule/build
+ echo MCKINSTALL=/work/mcktest/work_refs-changes-77-510077-1_submodule/mck
MCKINSTALL=/work/mcktest/work_refs-changes-77-510077-1_submodule/mck
+ sudo rm -rf /work/mcktest/work_refs-changes-77-510077-1_submodule/build
+ /work/mcktest/bin/config_and_build_smp_x86.sh /work/mcktest/work_refs-changes-77-510077-1_submodule/src /work/mcktest/work_refs-changes-77-510077-1_submodule/build /work/mcktest/work_refs-changes-77-510077-1_submodule/mck
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.11 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
+ error 'autobuild.sh failed'
+ echo 'ERROR: autobuild.sh failed'
ERROR: autobuild.sh failed
+ cd /
+ exit -1

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Test-x86=-1