Update patch set 1
Patch Set 1: Verified-1

setns_dummy_uts: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  5%] Built target ihklib
[  8%] Built target ihkmond
[ 10%] Built target ihkconfig
[ 12%] Built target ihkosctl
[ 14%] Generating kmod_always_rebuild
[ 15%] Building kmod ihk-smp-x86_64
[ 16%] Built target ihk-smp-x86_64_ko
[ 17%] Generating kmod_always_rebuild
[ 18%] Building kmod mcctrl
[ 20%] Built target mcctrl_ko
[ 22%] Built target libmcexec
[ 24%] Built target mcexec
[ 27%] Built target mcinspect
[ 29%] Built target sched_yield
[ 31%] Built target ldump2mcdump
[ 35%] Built target eclair
[ 36%] Building C object kernel/CMakeFiles/mckernel.img.dir/syscall.c.o
/work/mcktest/git/mckernel/kernel/syscall.c:1743:5: error: conflicting types for ‘do_munmap’
 int do_munmap(struct thread *thread, struct process_vm *vm,
     ^
In file included from /work/mcktest/git/mckernel/kernel/include/process.h:26:0,
                 from /work/mcktest/git/mckernel/kernel/include/cls.h:16,
                 from /work/mcktest/git/mckernel/kernel/syscall.c:33:
/work/mcktest/git/mckernel/kernel/include/syscall.h:535:5: note: previous declaration of ‘do_munmap’ was here
 int do_munmap(void *addr, size_t len, int holding_memory_range_lock);
     ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/syscall.c.o] Error 1
[ 37%] Building C object kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o
/work/mcktest/git/mckernel/kernel/xpmem.c: In function ‘xpmem_attach’:
/work/mcktest/git/mckernel/kernel/xpmem.c:1279:3: error: implicit declaration of function ‘ihk_atomic64_cmpxchg’ [-Werror=implicit-function-declaration]
   if ((old = ihk_atomic64_cmpxchg(&src_range->xpmem_count.atomic, 0, 2)) != 0) {
   ^
/work/mcktest/git/mckernel/kernel/xpmem.c: In function ‘xpmem_detach’:
/work/mcktest/git/mckernel/kernel/xpmem.c:1462:6: error: passing argument 2 of ‘do_munmap’ makes integer from pointer without a cast [-Werror]
      1);
      ^
In file included from /work/mcktest/git/mckernel/kernel/include/process.h:26:0,
                 from /work/mcktest/git/mckernel/kernel/include/cls.h:16,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:17,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/kernel/include/syscall.h:535:5: note: expected ‘size_t’ but argument is of type ‘struct process_vm *’
 int do_munmap(void *addr, size_t len, int holding_memory_range_lock);
     ^
/work/mcktest/git/mckernel/kernel/xpmem.c:1462:6: error: passing argument 3 of ‘do_munmap’ makes integer from pointer without a cast [-Werror]
      1);
      ^
In file included from /work/mcktest/git/mckernel/kernel/include/process.h:26:0,
                 from /work/mcktest/git/mckernel/kernel/include/cls.h:16,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:17,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/kernel/include/syscall.h:535:5: note: expected ‘int’ but argument is of type ‘void *’
 int do_munmap(void *addr, size_t len, int holding_memory_range_lock);
     ^
/work/mcktest/git/mckernel/kernel/xpmem.c:1462:6: error: too many arguments to function ‘do_munmap’
      1);
      ^
In file included from /work/mcktest/git/mckernel/kernel/include/process.h:26:0,
                 from /work/mcktest/git/mckernel/kernel/include/cls.h:16,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:17,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/kernel/include/syscall.h:535:5: note: declared here
 int do_munmap(void *addr, size_t len, int holding_memory_range_lock);
     ^
/work/mcktest/git/mckernel/kernel/xpmem.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 40%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1