Update patch set 1
Patch Set 1: Verified-1

mckernel build failed:
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcctrl SUBDIRS=/tmp/build/mckernel/executer/kernel/mcctrl ARCH=x86_64 modules
make[2]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[2]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[2]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 SUBDIRS=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 ARCH=x86_64 modules
make[3]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[3]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[2]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[1]: Entering directory `/tmp/build/mckernel/executer/user'
(cd arch/x86_64; make)
make[2]: Entering directory `/tmp/build/mckernel/executer/user/arch/x86_64'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/tmp/build/mckernel/executer/user/arch/x86_64'
gcc -shared -fPIC -Wl,-soname,sched_yield.so.1 -o libsched_yield.so.1.0.0 /work/mcktest/git/mckernel/executer/user/libsched_yield.c -lc -ldl
make[1]: Leaving directory `/tmp/build/mckernel/executer/user'
make[1]: Entering directory `/tmp/build/mckernel/kernel'
make[1]: Circular /tmp/build/mckernel/kernel/build/smp-x86/kernel.img <- /tmp/build/mckernel/kernel/build/smp-x86/kernel.img dependency dropped.
Building for /tmp/build/mckernel/kernel/build/smp-x86/
 (smp-x86) DEPEND
 (smp-x86) BUILD IHK smp-x86
 (smp-x86) BUILD IHK smp-x86
 (smp-x86) DEPEND [IHK]
 (smp-x86) BUILD IKC [IHK] smp-x86
 (smp-x86) DEPEND [IKC]
 (smp-x86) LDKERN kernel.img
process.o: In function `copy_user_pte':
/work/mcktest/git/mckernel/kernel/process.c:675: undefined reference to `pte_is_compound'
/work/mcktest/git/mckernel/kernel/process.c:676: undefined reference to `pgsize_to_tbllv'
/work/mcktest/git/mckernel/kernel/process.c:677: undefined reference to `tbllv_to_cmppgsize'
/work/mcktest/git/mckernel/kernel/process.c:680: undefined reference to `tbllv_to_cmppgshift'
make[2]: *** [kernel.img] Error 1
make[2]: Target `all' not remade because of errors.
make[1]: *** [/tmp/build/mckernel/kernel/build/smp-x86/kernel.img] Error 2
make[1]: Target `all' not remade because of errors.
rm /tmp/build/mckernel/kernel/build/smp-x86/Makefile
make[1]: Leaving directory `/tmp/build/mckernel/kernel'
make: *** [mckernel] Error 2
make[1]: Entering directory `/tmp/build/mckernel/tools/mcstat'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/tmp/build/mckernel/tools/mcstat'
make: Target `all' not remade because of errors.

Patch-set: 1
Reviewer: riken-syssoft-gerrit <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1