Update patch set 4
Patch Set 4: Build-arm64-1

apollo15: build report: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  6%] Built target ihkmond
[  8%] Built target ihkconfig
[ 10%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-arm64
[ 13%] Built target ihk-smp-arm64_ko
[ 14%] Generating kmod_always_rebuild
[ 15%] Building kmod mcctrl
[ 16%] Built target mcctrl_ko
[ 18%] Built target libmcexec
[ 19%] Built target mcexec
[ 21%] Built target mcinspect
[ 23%] Built target sched_yield
[ 25%] Built target ldump2mcdump
[ 27%] Built target eclair
[ 28%] Building C object kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o
In file included from /tmp/mckernel/lib/include/ihk/mm.h:20:0,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/xpmem.c:25:
/tmp/mckernel/kernel/xpmem.c: In function ‘xpmem_fault_process_memory_range’:
/tmp/mckernel/lib/include/ihk/lock.h:169:23: error: ‘at_lock’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  cpu_restore_interrupt(irqstate);
                       ^
/tmp/mckernel/kernel/xpmem.c:1772:16: note: ‘at_lock’ was declared here
  unsigned long at_lock;
                ^
/tmp/mckernel/kernel/xpmem.c: At top level:
cc1: error: unrecognized command line option "-Wno-stringop-truncation" [-Werror]
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 30%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 4
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1