Update patch set 2
Patch Set 2: Verified-1

build failed for aarch64:
[  1%] Generating old_timestamp, host_driver.o, mem_alloc.o, mm.o, mikc.o, ../../ikc/linux.o, ../../ikc/master.o, ../../ikc/queue.o, .host_driver.o.cmd, .mem_alloc.o.cmd, .mm.o.cmd, .mikc.o.cmd, ../../ikc/.linux.o.cmd, ../../ikc/.master.o.cmd, ../../ikc/.queue.o.cmd, ihk.o, .ihk.o.cmd, ihk.mod.c, ihk.mod.o, .ihk.mod.o.cmd, .ihk.ko.cmd, .tmp_versions/ihk.mod, .tmp_versions, modules.order
[  2%] Building kmod ihk
Makefile:643: arch/aarch64/Makefile: No such file or directory
make[3]: *** No rule to make target `arch/aarch64/Makefile'.
make[3]: Failed to remake makefile `arch/aarch64/Makefile'.
In file included from /work/mcktest/git/mckernel/ihk/linux/core/host_driver.c:19:0:
./include/linux/sched.h:12:25: fatal error: asm/current.h: No such file or directory
 #include <asm/current.h>
                         ^
compilation terminated.
make[4]: *** [/tmp/build-aarch64-mckernel/ihk/linux/core/host_driver.o] Error 1
In file included from ./include/linux/compiler.h:258:0,
                 from ./include/linux/linkage.h:5,
                 from ./include/linux/kernel.h:7,
                 from /work/mcktest/git/mckernel/ihk/linux/core/mem_alloc.c:10:
./include/uapi/linux/types.h:5:23: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>
                       ^
compilation terminated.
make[4]: *** [/tmp/build-aarch64-mckernel/ihk/linux/core/mem_alloc.o] Error 1
In file included from ./include/linux/compiler.h:258:0,
                 from ./include/linux/linkage.h:5,
                 from ./include/linux/kernel.h:7,
                 from /work/mcktest/git/mckernel/ihk/linux/core/mm.c:9:
./include/uapi/linux/types.h:5:23: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>
                       ^
compilation terminated.
make[4]: *** [/tmp/build-aarch64-mckernel/ihk/linux/core/mm.o] Error 1
In file included from /work/mcktest/git/mckernel/ihk/linux/core/mikc.c:12:0:
./include/linux/sched.h:12:25: fatal error: asm/current.h: No such file or directory
 #include <asm/current.h>
                         ^
compilation terminated.
make[4]: *** [/tmp/build-aarch64-mckernel/ihk/linux/core/mikc.o] Error 1
In file included from ./include/linux/compiler.h:258:0,
                 from ./include/linux/linkage.h:5,
                 from ./include/linux/kernel.h:7,
                 from /work/mcktest/git/mckernel/ihk/ikc/include/ikc/ihk.h:48,
                 from /work/mcktest/git/mckernel/ihk/linux/core/../../ikc/linux.c:8:
./include/uapi/linux/types.h:5:23: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>
                       ^
compilation terminated.
make[4]: *** [/tmp/build-aarch64-mckernel/ihk/linux/core/../../ikc/linux.o] Error 1
In file included from ./include/linux/compiler.h:258:0,
                 from ./include/linux/linkage.h:5,
                 from ./include/linux/kernel.h:7,
                 from /work/mcktest/git/mckernel/ihk/ikc/include/ikc/ihk.h:48,
                 from /work/mcktest/git/mckernel/ihk/linux/core/../../ikc/master.c:7:
./include/uapi/linux/types.h:5:23: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>
                       ^
compilation terminated.
make[4]: *** [/tmp/build-aarch64-mckernel/ihk/linux/core/../../ikc/master.o] Error 1
In file included from ./include/linux/compiler.h:258:0,
                 from ./include/linux/linkage.h:5,
                 from ./include/linux/kernel.h:7,
                 from /work/mcktest/git/mckernel/ihk/ikc/include/ikc/ihk.h:48,
                 from /work/mcktest/git/mckernel/ihk/linux/core/../../ikc/queue.c:8:
./include/uapi/linux/types.h:5:23: fatal error: asm/types.h: No such file or directory
 #include <asm/types.h>
                       ^
compilation terminated.
make[4]: *** [/tmp/build-aarch64-mckernel/ihk/linux/core/../../ikc/queue.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-aarch64-mckernel/ihk/linux/core] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [ihk/linux/core/ihk.ko] Error 2
make[2]: Target `ihk/linux/core/CMakeFiles/ihk_ko.dir/build' not remade because of errors.
make[1]: *** [ihk/linux/core/CMakeFiles/ihk_ko.dir/all] Error 2
[  3%] Built target ihklib
[  4%] Built target ihkconfig
[  5%] Built target ihkmond
[  6%] Built target ihkosctl
[  8%] Built target eclair
[  9%] Built target ldump2mcdump
[ 10%] Built target libmcexec
[ 11%] Built target mcexec
[ 12%] Built target sched_yield
[ 91%] Built target mckernel.img
[ 92%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1