Update patch set 3
Patch Set 3: Test-x86-1

MCKERNEL : mckernel-refs-changes-89-489189-3-?
IHK      : ihk-refs-changes-89-489189-3-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/489189/3 // f4db60f9f8d85a0968d4348e2b7bc51ca5027a27
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_refs-changes-89-489189-3_submodule
START : 20200413180028
END   : 20200413180050

+++ dirname /work/mcktest/bin/autobuild.sh
++ cd /work/mcktest/bin/..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ pwd
+ CWD=/
++ dirname /work/mcktest/bin/autobuild.sh
+ cd /work/mcktest/bin
+ . ./config.sh
++ export NODETYPE=wallaby
++ NODETYPE=wallaby
++ export WGETSSHPROXY=ofp05
++ WGETSSHPROXY=ofp05
++ export 'WGETPROXYOPTS=-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ WGETPROXYOPTS='-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ MCKERNELBRANCH=refs-changes-89-489189-3
++ IHKBRANCH=submodule
++ REFBRANCH=development
++ export WORKDIR=/work/mcktest/work_refs-changes-89-489189-3_submodule
++ WORKDIR=/work/mcktest/work_refs-changes-89-489189-3_submodule
++ SRC=/work/mcktest/work_refs-changes-89-489189-3_submodule/src
++ MCKBUILD=/work/mcktest/work_refs-changes-89-489189-3_submodule/build
++ MCKINSTALL=/work/mcktest/work_refs-changes-89-489189-3_submodule/mck
++ BUILDID_DIR=/work/mcktest/buildids
++ GITS=/work/mcktest/git
++ LTPINSTALL=/work/mcktest/ltp/install
++ STRESS_TEST_DIR=/work/mcktest/stress_test/install
++ MCKBUILDSCRIPT=/work/mcktest/bin/config_and_build_smp_x86.sh
++ MPICH=/usr/lib64/mpich-3.2
++ export LTPDIR=/work/mcktest/ltp/install
++ LTPDIR=/work/mcktest/ltp/install
++ export LTPROOT=/work/mcktest/ltp/install
++ LTPROOT=/work/mcktest/ltp/install
++ export 'MAIL_TO=mckernel@www.pccluster.org toshi@metahack.jp'
++ MAIL_TO='mckernel@www.pccluster.org toshi@metahack.jp'
++ export 'MCKERNELCONFIGOPTION=--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ MCKERNELCONFIGOPTION='--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ export IHKCONFIGOPTION=--enable-rusage
++ IHKCONFIGOPTION=--enable-rusage
++ MCREBOOTOPTION='-k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O'
++ export PATH=/work/mcktest/bin:/work/mcktest/work_refs-changes-89-489189-3_submodule/mck/bin:/work/mcktest/work_refs-changes-89-489189-3_submodule/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin
++ PATH=/work/mcktest/bin:/work/mcktest/work_refs-changes-89-489189-3_submodule/mck/bin:/work/mcktest/work_refs-changes-89-489189-3_submodule/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin
++ export DATADIR=/work/mcktest/data
++ DATADIR=/work/mcktest/data
++ export BINDIR=/work/mcktest/bin
++ BINDIR=/work/mcktest/bin
++ export LOGDIR=/work/mcktest/log
++ LOGDIR=/work/mcktest/log
++ STRESS_TEST_TIMEOUT=60
++ export OMP_NUM_THREADS_1=1
++ OMP_NUM_THREADS_1=1
++ export OMP_NUM_THREADS_2=2
++ OMP_NUM_THREADS_2=2
++ export OMP_NUM_THREADS_4=4
++ OMP_NUM_THREADS_4=4
++ export OMP_NUM_THREADS_8=8
++ OMP_NUM_THREADS_8=8
++ export OMP_NUM_THREADS_16=16
++ OMP_NUM_THREADS_16=16
++ export OMP_NUM_THREADS_24=24
++ OMP_NUM_THREADS_24=24
++ export OMP_NUM_THREADS_32=32
++ OMP_NUM_THREADS_32=32
++ export 'MPI_HOSTS=wallaby7 wallaby13'
++ MPI_HOSTS='wallaby7 wallaby13'
++ [[ -e /work/mcktest/bin/gerrit-creds ]]
++ . /work/mcktest/bin/gerrit-creds
+++ GERRITUSER=riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg
++ export GERRITSERVER=review.gerrithub.io
++ GERRITSERVER=review.gerrithub.io
++ export 'GERRITCURL=curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ GERRITCURL='curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ export GERRIT_USER=riken-syssoft-gerrit
++ GERRIT_USER=riken-syssoft-gerrit
++ export GERRIT_SERVER=review.gerrithub.io
++ GERRIT_SERVER=review.gerrithub.io
++ export 'GITSUDO=sudo -u mcktest'
++ GITSUDO='sudo -u mcktest'
++ export 'SSH_GERRIT=ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io'
++ SSH_GERRIT='ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io'
++ export GIT=/home/m-takagi/project/src/git/install/bin/git
++ GIT=/home/m-takagi/project/src/git/install/bin/git
+ export BINDIR=
+ BINDIR=
+ ./wget-postpeta.sh mckernel refs-changes-89-489189-3
++ pwd
+ CWD=/work/mcktest/bin
+++ dirname ./wget-postpeta.sh
++ cd ./..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ dirname ./wget-postpeta.sh
+ cd .
+ . ./config.sh
++ export NODETYPE=wallaby
++ NODETYPE=wallaby
++ export WGETSSHPROXY=ofp05
++ WGETSSHPROXY=ofp05
++ export 'WGETPROXYOPTS=-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ WGETPROXYOPTS='-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ MCKERNELBRANCH=refs-changes-89-489189-3
++ IHKBRANCH=submodule
++ REFBRANCH=development
++ export WORKDIR=/work/mcktest/work_refs-changes-89-489189-3_submodule
++ WORKDIR=/work/mcktest/work_refs-changes-89-489189-3_submodule
++ SRC=/work/mcktest/work_refs-changes-89-489189-3_submodule/src
++ MCKBUILD=/work/mcktest/work_refs-changes-89-489189-3_submodule/build
++ MCKINSTALL=/work/mcktest/work_refs-changes-89-489189-3_submodule/mck
++ BUILDID_DIR=/work/mcktest/buildids
++ GITS=/work/mcktest/git
++ LTPINSTALL=/work/mcktest/ltp/install
++ STRESS_TEST_DIR=/work/mcktest/stress_test/install
++ MCKBUILDSCRIPT=/work/mcktest/bin/config_and_build_smp_x86.sh
++ MPICH=/usr/lib64/mpich-3.2
++ export LTPDIR=/work/mcktest/ltp/install
++ LTPDIR=/work/mcktest/ltp/install
++ export LTPROOT=/work/mcktest/ltp/install
++ LTPROOT=/work/mcktest/ltp/install
++ export 'MAIL_TO=mckernel@www.pccluster.org toshi@metahack.jp'
++ MAIL_TO='mckernel@www.pccluster.org toshi@metahack.jp'
++ export 'MCKERNELCONFIGOPTION=--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ MCKERNELCONFIGOPTION='--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ export IHKCONFIGOPTION=--enable-rusage
++ IHKCONFIGOPTION=--enable-rusage
++ MCREBOOTOPTION='-k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O'
++ export PATH=/work/mcktest/bin:/work/mcktest/work_refs-changes-89-489189-3_submodule/mck/bin:/work/mcktest/work_refs-changes-89-489189-3_submodule/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin
++ PATH=/work/mcktest/bin:/work/mcktest/work_refs-changes-89-489189-3_submodule/mck/bin:/work/mcktest/work_refs-changes-89-489189-3_submodule/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin
++ export DATADIR=/work/mcktest/data
++ DATADIR=/work/mcktest/data
++ export BINDIR=/work/mcktest/bin
++ BINDIR=/work/mcktest/bin
++ export LOGDIR=/work/mcktest/log
++ LOGDIR=/work/mcktest/log
++ STRESS_TEST_TIMEOUT=60
++ export OMP_NUM_THREADS_1=1
++ OMP_NUM_THREADS_1=1
++ export OMP_NUM_THREADS_2=2
++ OMP_NUM_THREADS_2=2
++ export OMP_NUM_THREADS_4=4
++ OMP_NUM_THREADS_4=4
++ export OMP_NUM_THREADS_8=8
++ OMP_NUM_THREADS_8=8
++ export OMP_NUM_THREADS_16=16
++ OMP_NUM_THREADS_16=16
++ export OMP_NUM_THREADS_24=24
++ OMP_NUM_THREADS_24=24
++ export OMP_NUM_THREADS_32=32
++ OMP_NUM_THREADS_32=32
++ export 'MPI_HOSTS=wallaby7 wallaby13'
++ MPI_HOSTS='wallaby7 wallaby13'
++ [[ -e /work/mcktest/bin/gerrit-creds ]]
++ . /work/mcktest/bin/gerrit-creds
+++ GERRITUSER=riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg
++ export GERRITSERVER=review.gerrithub.io
++ GERRITSERVER=review.gerrithub.io
++ export 'GERRITCURL=curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ GERRITCURL='curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ export GERRIT_USER=riken-syssoft-gerrit
++ GERRIT_USER=riken-syssoft-gerrit
++ export GERRIT_SERVER=review.gerrithub.io
++ GERRIT_SERVER=review.gerrithub.io
++ export 'GITSUDO=sudo -u mcktest'
++ GITSUDO='sudo -u mcktest'
++ export 'SSH_GERRIT=ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io'
++ SSH_GERRIT='ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io'
++ export GIT=/home/m-takagi/project/src/git/install/bin/git
++ GIT=/home/m-takagi/project/src/git/install/bin/git
+ forwatchgerrit=0
+ REPO=mckernel
+ BRANCH=refs-changes-89-489189-3
+ case "$BRANCH" in
+ remote_type=gerrit-git
+ PATHSPEC=refs/changes/89/489189/3
+ '[' /work/mcktest/work_refs-changes-89-489189-3_submodule/src == '' ']'
+ '[' mckernel == '' ']'
+ DEST=mckernel
+ [[ -d /work/mcktest/work_refs-changes-89-489189-3_submodule/src ]]
+ mkdir /work/mcktest/work_refs-changes-89-489189-3_submodule/src
+ rm -rf '/work/mcktest/work_refs-changes-89-489189-3_submodule/src/mckernel-*'
+ case $NODETYPE in
+ case $remote_type in
+ pushd /work/mcktest/git
/work/mcktest/git /work/mcktest/bin
+ sudo -u mcktest rm -rf mckernel
+ sudo -u mcktest git clone ssh://riken-syssoft-gerrit@review.gerrithub.io/RIKEN-SysSoft/mckernel
Cloning into 'mckernel'...
Total 31354 (delta 20330), reused 30996 (delta 20330)
+ cd mckernel
+ sudo -u mcktest git fetch origin refs/changes/89/489189/3
Total 11 (delta 6), reused 11 (delta 6)
From ssh://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/89/489189/3 -> FETCH_HEAD
++ sudo -u mcktest git rev-parse FETCH_HEAD
+ COMMIT=f4db60f9f8d85a0968d4348e2b7bc51ca5027a27
+ DEST=mckernel-refs-changes-89-489189-3-f4db60f9f8d85a0968d4348e2b7bc51ca5027a27
+ popd
/work/mcktest/bin
+ '[' 0 -ne 0 ']'
+ '[' 0 -eq 1 ']'
+ case $remote_type in
+ mkdir /work/mcktest/work_refs-changes-89-489189-3_submodule/src/mckernel-refs-changes-89-489189-3-f4db60f9f8d85a0968d4348e2b7bc51ca5027a27
+ cd /work/mcktest/work_refs-changes-89-489189-3_submodule/src/mckernel-refs-changes-89-489189-3-f4db60f9f8d85a0968d4348e2b7bc51ca5027a27
+ GIT_DIR=/work/mcktest/git/mckernel/.git
+ git reset --hard f4db60f9f8d85a0968d4348e2b7bc51ca5027a27
HEAD is now at f4db60f freeze: arm64: use normal interrupt instead of NMI
+ cd /work/mcktest/bin
+ exit 0
+ [[ submodule == \s\u\b\m\o\d\u\l\e ]]
+ local subref
/work/mcktest/bin/autobuild.sh: line 26: local: can only be used in a function
+ read subref _
++ cd /work/mcktest/git/mckernel
++ /home/m-takagi/project/src/git/install/bin/git submodule status
+ SUBMODULE_HASH=dd52fbbb9f364cce4ff827a729daafa4476f6801
++ ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io 'gerrit query --format=TEXT --current-patch-set --commit-message commit:dd52fbbb9f364cce4ff827a729daafa4476f6801'
++ awk '/ref:/ { print $2 }'
+ SUBMODULE_PATHSPEC=refs/changes/54/486254/5
+ [[ refs/changes/54/486254/5 != '' ]]
+ IHKBRANCH=refs_changes_54_486254_5
+ echo 'ihk: submodule commit resolved to refs_changes_54_486254_5'
ihk: submodule commit resolved to refs_changes_54_486254_5
+ [[ -n refs_changes_54_486254_5 ]]
+ case "$IHKBRANCH" in
+ ./wget-postpeta.sh ihk refs_changes_54_486254_5
++ pwd
+ CWD=/work/mcktest/bin
+++ dirname ./wget-postpeta.sh
++ cd ./..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ dirname ./wget-postpeta.sh
+ cd .
+ . ./config.sh
++ export NODETYPE=wallaby
++ NODETYPE=wallaby
++ export WGETSSHPROXY=ofp05
++ WGETSSHPROXY=ofp05
++ export 'WGETPROXYOPTS=-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ WGETPROXYOPTS='-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ MCKERNELBRANCH=refs-changes-89-489189-3
++ IHKBRANCH=submodule
++ REFBRANCH=development
++ export WORKDIR=/work/mcktest/work_refs-changes-89-489189-3_submodule
++ WORKDIR=/work/mcktest/work_refs-changes-89-489189-3_submodule
++ SRC=/work/mcktest/work_refs-changes-89-489189-3_submodule/src
++ MCKBUILD=/work/mcktest/work_refs-changes-89-489189-3_submodule/build
++ MCKINSTALL=/work/mcktest/work_refs-changes-89-489189-3_submodule/mck
++ BUILDID_DIR=/work/mcktest/buildids
++ GITS=/work/mcktest/git
++ LTPINSTALL=/work/mcktest/ltp/install
++ STRESS_TEST_DIR=/work/mcktest/stress_test/install
++ MCKBUILDSCRIPT=/work/mcktest/bin/config_and_build_smp_x86.sh
++ MPICH=/usr/lib64/mpich-3.2
++ export LTPDIR=/work/mcktest/ltp/install
++ LTPDIR=/work/mcktest/ltp/install
++ export LTPROOT=/work/mcktest/ltp/install
++ LTPROOT=/work/mcktest/ltp/install
++ export 'MAIL_TO=mckernel@www.pccluster.org toshi@metahack.jp'
++ MAIL_TO='mckernel@www.pccluster.org toshi@metahack.jp'
++ export 'MCKERNELCONFIGOPTION=--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ MCKERNELCONFIGOPTION='--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ export IHKCONFIGOPTION=--enable-rusage
++ IHKCONFIGOPTION=--enable-rusage
++ MCREBOOTOPTION='-k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O'
++ export PATH=/work/mcktest/bin:/work/mcktest/work_refs-changes-89-489189-3_submodule/mck/bin:/work/mcktest/work_refs-changes-89-489189-3_submodule/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin
++ PATH=/work/mcktest/bin:/work/mcktest/work_refs-changes-89-489189-3_submodule/mck/bin:/work/mcktest/work_refs-changes-89-489189-3_submodule/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin
++ export DATADIR=/work/mcktest/data
++ DATADIR=/work/mcktest/data
++ export BINDIR=/work/mcktest/bin
++ BINDIR=/work/mcktest/bin
++ export LOGDIR=/work/mcktest/log
++ LOGDIR=/work/mcktest/log
++ STRESS_TEST_TIMEOUT=60
++ export OMP_NUM_THREADS_1=1
++ OMP_NUM_THREADS_1=1
++ export OMP_NUM_THREADS_2=2
++ OMP_NUM_THREADS_2=2
++ export OMP_NUM_THREADS_4=4
++ OMP_NUM_THREADS_4=4
++ export OMP_NUM_THREADS_8=8
++ OMP_NUM_THREADS_8=8
++ export OMP_NUM_THREADS_16=16
++ OMP_NUM_THREADS_16=16
++ export OMP_NUM_THREADS_24=24
++ OMP_NUM_THREADS_24=24
++ export OMP_NUM_THREADS_32=32
++ OMP_NUM_THREADS_32=32
++ export 'MPI_HOSTS=wallaby7 wallaby13'
++ MPI_HOSTS='wallaby7 wallaby13'
++ [[ -e /work/mcktest/bin/gerrit-creds ]]
++ . /work/mcktest/bin/gerrit-creds
+++ GERRITUSER=riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg
++ export GERRITSERVER=review.gerrithub.io
++ GERRITSERVER=review.gerrithub.io
++ export 'GERRITCURL=curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ GERRITCURL='curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ export GERRIT_USER=riken-syssoft-gerrit
++ GERRIT_USER=riken-syssoft-gerrit
++ export GERRIT_SERVER=review.gerrithub.io
++ GERRIT_SERVER=review.gerrithub.io
++ export 'GITSUDO=sudo -u mcktest'
++ GITSUDO='sudo -u mcktest'
++ export 'SSH_GERRIT=ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io'
++ SSH_GERRIT='ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io'
++ export GIT=/home/m-takagi/project/src/git/install/bin/git
++ GIT=/home/m-takagi/project/src/git/install/bin/git
+ forwatchgerrit=0
+ REPO=ihk
+ BRANCH=refs_changes_54_486254_5
+ case "$BRANCH" in
+ remote_type=git
+ PATHSPEC=origin/refs_changes_54_486254_5
+ '[' /work/mcktest/work_refs-changes-89-489189-3_submodule/src == '' ']'
+ '[' ihk == '' ']'
+ DEST=ihk
+ [[ -d /work/mcktest/work_refs-changes-89-489189-3_submodule/src ]]
+ rm -rf '/work/mcktest/work_refs-changes-89-489189-3_submodule/src/ihk-*'
+ case $NODETYPE in
+ case $remote_type in
+ pushd /work/mcktest/git
/work/mcktest/git /work/mcktest/bin
+ sudo -u mcktest rm -rf ihk
+ sudo -u mcktest git clone ssh://riken-syssoft-gerrit@review.gerrithub.io/RIKEN-SysSoft/ihk
Cloning into 'ihk'...
Total 6388 (delta 4404), reused 6258 (delta 4404)
+ cd ihk
+ [[ '' != '' ]]
++ sudo -u mcktest git rev-parse origin/refs_changes_54_486254_5
fatal: ambiguous argument 'origin/refs_changes_54_486254_5': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
+ COMMIT=origin/refs_changes_54_486254_5
+ DEST=ihk-refs_changes_54_486254_5-origin/refs_changes_54_486254_5
+ popd
/work/mcktest/bin
+ '[' 0 -ne 0 ']'
+ '[' 0 -eq 1 ']'
+ case $remote_type in
+ mkdir /work/mcktest/work_refs-changes-89-489189-3_submodule/src/ihk-refs_changes_54_486254_5-origin/refs_changes_54_486254_5
mkdir: cannot create directory ‘/work/mcktest/work_refs-changes-89-489189-3_submodule/src/ihk-refs_changes_54_486254_5-origin/refs_changes_54_486254_5’: No such file or directory
+ cd /work/mcktest/work_refs-changes-89-489189-3_submodule/src/ihk-refs_changes_54_486254_5-origin/refs_changes_54_486254_5
./wget-postpeta.sh: line 136: cd: /work/mcktest/work_refs-changes-89-489189-3_submodule/src/ihk-refs_changes_54_486254_5-origin/refs_changes_54_486254_5: No such file or directory
+ GIT_DIR=/work/mcktest/git/ihk/.git
+ git reset --hard origin/refs_changes_54_486254_5
fatal: ambiguous argument 'origin/refs_changes_54_486254_5': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
+ error 'commit not found in repo'
++ basename ./wget-postpeta.sh
+ echo 'wget-postpeta.sh: ERROR: commit not found in repo'
wget-postpeta.sh: ERROR: commit not found in repo
+ cd /work/mcktest/bin
+ exit -1
+ error 'autobuild.sh couldn'\''t get ihk'
+ echo 'ERROR: autobuild.sh couldn'\''t get ihk'
ERROR: autobuild.sh couldn't get ihk
+ cd /
+ exit -1

Patch-set: 3
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Test-x86=-1