Update patch set 10
Patch Set 10: Verified-1

build failed for aarch64:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  5%] Built target ihkconfig
[  6%] Built target ihkmond
[  7%] Built target ihkosctl
[  8%] Generating old_timestamp, arch/arm64/smp-arm64-startup.o, arch/arm64/smp-arm64-trampoline.o, arch/arm64/smp-arch-driver.o, smp-driver.o, arch/arm64/.smp-arm64-startup.o.cmd, arch/arm64/.smp-arm64-trampoline.o.cmd, arch/arm64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-arm64.o, .ihk-smp-arm64.o.cmd, ihk-smp-arm64.mod.c, ihk-smp-arm64.mod.o, .ihk-smp-arm64.mod.o.cmd, .ihk-smp-arm64.ko.cmd, .tmp_versions/ihk-smp-arm64.mod, .tmp_versions, modules.order
[  9%] Building kmod ihk-smp-arm64
/work/mcktest/git/mckernel/ihk/linux/driver/smp/arch/arm64/smp-arch-driver.c:79:33: error: ‘ihk_smp_irq’ defined but not used [-Werror=unused-variable]
 static struct ihk_smp_irq_table ihk_smp_irq[SMP_MAX_IRQS];
                                 ^
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-aarch64-mckernel/ihk/linux/driver/smp/arch/arm64/smp-arch-driver.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-aarch64-mckernel/ihk/linux/driver/smp] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [ihk/linux/driver/smp/ihk-smp-arm64.ko] Error 2
make[2]: Target `ihk/linux/driver/smp/CMakeFiles/ihk-smp-arm64_ko.dir/build' not remade because of errors.
make[1]: *** [ihk/linux/driver/smp/CMakeFiles/ihk-smp-arm64_ko.dir/all] Error 2
[ 10%] Generating kmod_always_rebuild
[ 11%] Building kmod mcctrl
[ 12%] Built target mcctrl_ko
[ 14%] Built target eclair
[ 15%] Built target ldump2mcdump
[ 16%] Built target libmcexec
[ 17%] Built target mcexec
[ 18%] Built target sched_yield
[ 97%] Built target mckernel.img
[ 98%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 10
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1