Update patch set 1
Patch Set 1:

wallaby7: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  2%] Built target ihk_ko
[  3%] Built target ihklib
[  4%] Built target ihkconfig
[  5%] Built target ihkmond
[  5%] Built target ihkosctl
[  5%] Generating kmod_always_rebuild
[  6%] Building kmod ihk-smp-x86_64
[  7%] Built target ihk-smp-x86_64_ko
[  7%] Generating kmod_always_rebuild
[  8%] Building kmod mcctrl
[  9%] Built target mcctrl_ko
[ 10%] Built target eclair
[ 11%] Built target ldump2mcdump
[ 12%] Built target libmcexec
[ 13%] Built target mcexec
[ 15%] Built target gennames
[ 59%] Built target dwarf
[ 60%] Built target mcinspect
[ 61%] Built target sched_yield
[ 62%] Building C object kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o
/work/mcktest/git/mckernel/kernel/xpmem.c: In function ‘xpmem_remove_process_memory_range’:
/work/mcktest/git/mckernel/kernel/xpmem.c:1667:2: error: passing argument 1 of ‘__ihk_mc_spinlock_lock_noirq’ from incompatible pointer type [-Werror]
  ihk_mc_spinlock_lock_noirq(&vm->memory_range_lock);
  ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-lock.h:108:20: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static inline void __ihk_mc_spinlock_lock_noirq(ihk_spinlock_t *lock)
                    ^
/work/mcktest/git/mckernel/kernel/xpmem.c:1747:2: error: passing argument 1 of ‘__ihk_mc_spinlock_unlock_noirq’ from incompatible pointer type [-Werror]
  ihk_mc_spinlock_unlock_noirq(&vm->memory_range_lock);
  ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/lock.h:16:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-lock.h:159:20: note: expected ‘struct ihk_spinlock_t *’ but argument is of type ‘struct ihk_rwspinlock_t *’
 static inline void __ihk_mc_spinlock_unlock_noirq(ihk_spinlock_t *lock)
                    ^
/work/mcktest/git/mckernel/kernel/xpmem.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 63%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>