Update patch set 3
Patch Set 3:

MCKERNEL : mckernel-refs-changes-10-427610-3-?
IHK      : ihk-refs-changes-10-427610-3-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/427610/3 // 035b53bdd14326cd350e4cbdc8c1caa14f280640
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_refs-changes-10-427610-3_submodule
START : 20181013211125
END   : 20181013211136

From ssh://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/10/427610/3 -> FETCH_HEAD
HEAD is now at 035b53b build system switch to cmake
HEAD is now at 29be544 build system: switch to cmake
MCKBUILD=/work/mcktest/work_refs-changes-10-427610-3_submodule/build
MCKINSTALL=/work/mcktest/work_refs-changes-10-427610-3_submodule/mck
/work/mcktest/bin/config_and_build_smp_x86.sh: line 24: /work/mcktest/work_refs-changes-10-427610-3_submodule/src/ihk/configure: No such file or directory
ERROR: autobuild.sh failed

Patch-set: 3
Reviewer: syssoft-gerrit@ml.riken.jp <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>