Update patch set 2
Patch Set 2: Verified-1

build failed for aarch64:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  5%] Built target ihkconfig
[  6%] Built target ihkmond
[  7%] Built target ihkosctl
[  8%] Generating kmod_always_rebuild
[  9%] Building kmod ihk-smp-arm64
[ 10%] Built target ihk-smp-arm64_ko
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod mcctrl
[ 13%] Built target mcctrl_ko
[ 15%] Built target eclair
[ 16%] Built target ldump2mcdump
[ 17%] Built target libmcexec
[ 18%] Built target mcexec
[ 19%] Built target sched_yield
[ 20%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/vdso.c.o
/work/mcktest/git/mckernel/arch/arm64/kernel/vdso.c: In function ‘arch_map_vdso’:
/work/mcktest/git/mckernel/arch/arm64/kernel/vdso.c:140:9: error: variable ‘free’ has initializer but incomplete type
  struct rb_tree free = RB_ROOT;
         ^
/work/mcktest/git/mckernel/arch/arm64/kernel/vdso.c:140:17: error: storage size of ‘free’ isn’t known
  struct rb_tree free = RB_ROOT;
                 ^
/work/mcktest/git/mckernel/arch/arm64/kernel/vdso.c:140:17: error: unused variable ‘free’ [-Werror=unused-variable]
/work/mcktest/git/mckernel/arch/arm64/kernel/vdso.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/vdso.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 21%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1