Update patch set 1
Patch Set 1: Build-arm64-1

apollo15: build report: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  6%] Built target ihkmond
[  8%] Built target ihkconfig
[ 10%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-arm64
[ 13%] Built target ihk-smp-arm64_ko
[ 14%] Generating kmod_always_rebuild
[ 15%] Building kmod mcctrl
[ 16%] Built target mcctrl_ko
[ 18%] Built target libmcexec
[ 19%] Built target mcexec
[ 21%] Built target mcinspect
[ 23%] Built target sched_yield
[ 25%] Built target ldump2mcdump
[ 27%] Built target eclair
[ 28%] Building C object kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o
In file included from /tmp/mckernel/kernel/xpmem.c:35:0:
/tmp/mckernel/kernel/include/xpmem_private.h:180:8: error: redefinition of ‘struct xpmem_attachment’
 struct xpmem_attachment {
        ^
In file included from /tmp/mckernel/kernel/include/xpmem_private.h:28:0,
                 from /tmp/mckernel/kernel/xpmem.c:35:
/tmp/mckernel/kernel/include/xpmem.h:31:8: note: originally defined here
 struct xpmem_attachment {
        ^
/tmp/mckernel/kernel/xpmem.c: In function ‘xpmem_attach’:
/tmp/mckernel/kernel/xpmem.c:1085:2: error: passing argument 1 of ‘ihk_rwspinlock_init’ from incompatible pointer type [-Werror]
  ihk_rwspinlock_init(&att->at_lock);
  ^
In file included from /tmp/mckernel/lib/include/ihk/mm.h:20:0,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/xpmem.c:25:
/tmp/mckernel/lib/include/ihk/lock.h:25:13: note: expected ‘struct ihk_rwspinlock_t *’ but argument is of type ‘struct mcs_rwlock_lock_t *’
 static void ihk_rwspinlock_init(ihk_rwspinlock_t *lock)
             ^
/tmp/mckernel/kernel/xpmem.c:1095:2: error: passing argument 1 of ‘ihk_rwspinlock_write_lock’ from incompatible pointer type [-Werror]
  at_lock = ihk_rwspinlock_write_lock(&att->at_lock);
  ^
In file included from /tmp/mckernel/lib/include/ihk/mm.h:20:0,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/xpmem.c:25:
/tmp/mckernel/lib/include/ihk/lock.h:150:15: note: expected ‘struct ihk_rwspinlock_t *’ but argument is of type ‘struct mcs_rwlock_lock_t *’
 unsigned long ihk_rwspinlock_write_lock(ihk_rwspinlock_t *lock)
               ^
/tmp/mckernel/kernel/xpmem.c:1179:2: error: passing argument 1 of ‘ihk_rwspinlock_write_unlock’ from incompatible pointer type [-Werror]
  ihk_rwspinlock_write_unlock(&att->at_lock, at_lock);
  ^
In file included from /tmp/mckernel/lib/include/ihk/mm.h:20:0,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/xpmem.c:25:
/tmp/mckernel/lib/include/ihk/lock.h:165:20: note: expected ‘struct ihk_rwspinlock_t *’ but argument is of type ‘struct mcs_rwlock_lock_t *’
 static inline void ihk_rwspinlock_write_unlock(ihk_rwspinlock_t *lock,
                    ^
/tmp/mckernel/kernel/xpmem.c: In function ‘xpmem_detach’:
/tmp/mckernel/kernel/xpmem.c:1222:2: error: passing argument 1 of ‘ihk_rwspinlock_write_lock’ from incompatible pointer type [-Werror]
  at_lock = ihk_rwspinlock_write_lock(&att->at_lock);
  ^
In file included from /tmp/mckernel/lib/include/ihk/mm.h:20:0,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/xpmem.c:25:
/tmp/mckernel/lib/include/ihk/lock.h:150:15: note: expected ‘struct ihk_rwspinlock_t *’ but argument is of type ‘struct mcs_rwlock_lock_t *’
 unsigned long ihk_rwspinlock_write_lock(ihk_rwspinlock_t *lock)
               ^
/tmp/mckernel/kernel/xpmem.c:1225:3: error: passing argument 1 of ‘ihk_rwspinlock_write_unlock’ from incompatible pointer type [-Werror]
   ihk_rwspinlock_write_unlock(&att->at_lock, at_lock);
   ^
In file included from /tmp/mckernel/lib/include/ihk/mm.h:20:0,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/xpmem.c:25:
/tmp/mckernel/lib/include/ihk/lock.h:165:20: note: expected ‘struct ihk_rwspinlock_t *’ but argument is of type ‘struct mcs_rwlock_lock_t *’
 static inline void ihk_rwspinlock_write_unlock(ihk_rwspinlock_t *lock,
                    ^
/tmp/mckernel/kernel/xpmem.c:1238:3: error: passing argument 1 of ‘ihk_rwspinlock_write_unlock’ from incompatible pointer type [-Werror]
   ihk_rwspinlock_write_unlock(&att->at_lock, at_lock);
   ^
In file included from /tmp/mckernel/lib/include/ihk/mm.h:20:0,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/xpmem.c:25:
/tmp/mckernel/lib/include/ihk/lock.h:165:20: note: expected ‘struct ihk_rwspinlock_t *’ but argument is of type ‘struct mcs_rwlock_lock_t *’
 static inline void ihk_rwspinlock_write_unlock(ihk_rwspinlock_t *lock,
                    ^
/tmp/mckernel/kernel/xpmem.c:1250:2: error: passing argument 1 of ‘ihk_rwspinlock_write_unlock’ from incompatible pointer type [-Werror]
  ihk_rwspinlock_write_unlock(&att->at_lock, at_lock);
  ^
In file included from /tmp/mckernel/lib/include/ihk/mm.h:20:0,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/xpmem.c:25:
/tmp/mckernel/lib/include/ihk/lock.h:165:20: note: expected ‘struct ihk_rwspinlock_t *’ but argument is of type ‘struct mcs_rwlock_lock_t *’
 static inline void ihk_rwspinlock_write_unlock(ihk_rwspinlock_t *lock,
                    ^
/tmp/mckernel/kernel/xpmem.c: In function ‘xpmem_detach_att’:
/tmp/mckernel/kernel/xpmem.c:1424:2: error: passing argument 1 of ‘ihk_rwspinlock_write_lock’ from incompatible pointer type [-Werror]
  at_lock = ihk_rwspinlock_write_lock(&att->at_lock);
  ^
In file included from /tmp/mckernel/lib/include/ihk/mm.h:20:0,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/xpmem.c:25:
/tmp/mckernel/lib/include/ihk/lock.h:150:15: note: expected ‘struct ihk_rwspinlock_t *’ but argument is of type ‘struct mcs_rwlock_lock_t *’
 unsigned long ihk_rwspinlock_write_lock(ihk_rwspinlock_t *lock)
               ^
/tmp/mckernel/kernel/xpmem.c:1427:3: error: passing argument 1 of ‘ihk_rwspinlock_write_unlock’ from incompatible pointer type [-Werror]
   ihk_rwspinlock_write_unlock(&att->at_lock, at_lock);
   ^
In file included from /tmp/mckernel/lib/include/ihk/mm.h:20:0,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/xpmem.c:25:
/tmp/mckernel/lib/include/ihk/lock.h:165:20: note: expected ‘struct ihk_rwspinlock_t *’ but argument is of type ‘struct mcs_rwlock_lock_t *’
 static inline void ihk_rwspinlock_write_unlock(ihk_rwspinlock_t *lock,
                    ^
/tmp/mckernel/kernel/xpmem.c:1443:3: error: passing argument 1 of ‘ihk_rwspinlock_write_unlock’ from incompatible pointer type [-Werror]
   ihk_rwspinlock_write_unlock(&att->at_lock, at_lock);
   ^
In file included from /tmp/mckernel/lib/include/ihk/mm.h:20:0,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/xpmem.c:25:
/tmp/mckernel/lib/include/ihk/lock.h:165:20: note: expected ‘struct ihk_rwspinlock_t *’ but argument is of type ‘struct mcs_rwlock_lock_t *’
 static inline void ihk_rwspinlock_write_unlock(ihk_rwspinlock_t *lock,
                    ^
/tmp/mckernel/kernel/xpmem.c:1469:2: error: passing argument 1 of ‘ihk_rwspinlock_write_unlock’ from incompatible pointer type [-Werror]
  ihk_rwspinlock_write_unlock(&att->at_lock, at_lock);
  ^
In file included from /tmp/mckernel/lib/include/ihk/mm.h:20:0,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/xpmem.c:25:
/tmp/mckernel/lib/include/ihk/lock.h:165:20: note: expected ‘struct ihk_rwspinlock_t *’ but argument is of type ‘struct mcs_rwlock_lock_t *’
 static inline void ihk_rwspinlock_write_unlock(ihk_rwspinlock_t *lock,
                    ^
/tmp/mckernel/kernel/xpmem.c: In function ‘xpmem_clear_PTEs_of_att’:
/tmp/mckernel/kernel/xpmem.c:158

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1
Attention: {"person_ident":"Gerrit User 1014954 \u003c1014954@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"ADD","reason":"Reviewer was added"}