Update patch set 1
Patch Set 1: Verified-1

build failed for aarch64:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  5%] Built target ihkconfig
[  6%] Built target ihkmond
[  7%] Built target ihkosctl
[  8%] Generating kmod_always_rebuild
[  9%] Building kmod ihk-smp-arm64
[ 10%] Built target ihk-smp-arm64_ko
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod mcctrl
[ 13%] Built target mcctrl_ko
[ 15%] Built target eclair
[ 16%] Built target ldump2mcdump
[ 17%] Built target libmcexec
[ 18%] Built target mcexec
[ 20%] Built target sched_yield
[ 21%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/cpufeature.c.o
In file included from /work/mcktest/git/mckernel/arch/arm64/kernel/cpufeature.c:5:0:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/traps.h:12:19: error: field ‘node’ has incomplete type
  struct list_head node;
                   ^
/work/mcktest/git/mckernel/arch/arm64/kernel/cpufeature.c: In function ‘emulate_mrs’:
/work/mcktest/git/mckernel/arch/arm64/kernel/cpufeature.c:896:7: error: dereferencing pointer to incomplete type
   regs->pc += 4;
       ^
/work/mcktest/git/mckernel/arch/arm64/kernel/cpufeature.c: At top level:
/work/mcktest/git/mckernel/arch/arm64/kernel/cpufeature.c:906:17: error: ‘COMPAT_PSR_MODE_MASK’ undeclared here (not in a function)
  .pstate_mask = COMPAT_PSR_MODE_MASK,
                 ^
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/cpufeature.c.o] Error 1
[ 22%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/traps.c.o
In file included from /work/mcktest/git/mckernel/arch/arm64/kernel/traps.c:4:0:
/work/mcktest/git/mckernel/arch/arm64/kernel/include/traps.h:12:19: error: field ‘node’ has incomplete type
  struct list_head node;
                   ^
In file included from /work/mcktest/git/mckernel/arch/arm64/kernel/include/arch-memory.h:9:0,
                 from /work/mcktest/git/mckernel/arch/arm64/kernel/include/thread_info.h:7,
                 from /work/mcktest/git/mckernel/arch/arm64/kernel/include/cpulocal.h:7,
                 from /work/mcktest/git/mckernel/arch/arm64/kernel/traps.c:7:
/work/mcktest/git/mckernel/arch/arm64/kernel/traps.c: In function ‘call_undef_hook’:
/work/mcktest/git/mckernel/lib/include/list.h:15:55: error: initialization from incompatible pointer type [-Werror]
         const typeof( ((type *)0)->member ) *__mptr = (ptr);    \
                                                       ^
/work/mcktest/git/mckernel/lib/include/list.h:367:2: note: in expansion of macro ‘container_of’
  container_of(ptr, type, member)
  ^
/work/mcktest/git/mckernel/lib/include/list.h:435:13: note: in expansion of macro ‘list_entry’
  for (pos = list_entry((head)->next, typeof(*pos), member); \
             ^
/work/mcktest/git/mckernel/arch/arm64/kernel/traps.c:126:2: note: in expansion of macro ‘list_for_each_entry’
  list_for_each_entry(hook, &undef_hook, node)
  ^
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/traps.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 23%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1