Update patch set 2
Patch Set 2: Build-arm64-1

apollo15: build report: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  6%] Built target ihkmond
[  8%] Built target ihkconfig
[ 10%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-arm64
[ 13%] Built target ihk-smp-arm64_ko
[ 14%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, mc_plist.o, futex.o, arch/arm64/archdeps.o, arch/arm64/cpu.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, .mc_plist.o.cmd, .futex.o.cmd, arch/arm64/.archdeps.o.cmd, arch/arm64/.cpu.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 15%] Building kmod mcctrl
In file included from /tmp/mckernel/executer/kernel/mcctrl/ikc.c:31:0:
/tmp/mckernel/executer/kernel/mcctrl/mcctrl.h:47:5: error: "KERNEL_VERSION" is not defined [-Werror=undef]
 #if KERNEL_VERSION(4, 11, 0) > LINUX_VERSION_CODE
     ^
/tmp/mckernel/executer/kernel/mcctrl/mcctrl.h:47:19: error: missing binary operator before token "("
 #if KERNEL_VERSION(4, 11, 0) > LINUX_VERSION_CODE
                   ^
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/ikc.o] Error 1
In file included from /tmp/mckernel/executer/kernel/mcctrl/syscall.c:55:0:
/tmp/mckernel/executer/kernel/mcctrl/mcctrl.h:47:5: error: "KERNEL_VERSION" is not defined [-Werror=undef]
 #if KERNEL_VERSION(4, 11, 0) > LINUX_VERSION_CODE
     ^
/tmp/mckernel/executer/kernel/mcctrl/mcctrl.h:47:19: error: missing binary operator before token "("
 #if KERNEL_VERSION(4, 11, 0) > LINUX_VERSION_CODE
                   ^
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/syscall.o] Error 1
In file included from /tmp/mckernel/executer/kernel/mcctrl/procfs.c:23:0:
/tmp/mckernel/executer/kernel/mcctrl/mcctrl.h:47:5: error: "KERNEL_VERSION" is not defined [-Werror=undef]
 #if KERNEL_VERSION(4, 11, 0) > LINUX_VERSION_CODE
     ^
/tmp/mckernel/executer/kernel/mcctrl/mcctrl.h:47:19: error: missing binary operator before token "("
 #if KERNEL_VERSION(4, 11, 0) > LINUX_VERSION_CODE
                   ^
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/procfs.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 17%] Built target libmcexec
[ 18%] Built target mcexec
[ 20%] Built target mcinspect
[ 22%] Built target sched_yield
[ 24%] Built target ldump2mcdump
[ 26%] Built target eclair
[ 97%] Built target mckernel.img
[ 99%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1