Update patch set 3
Patch Set 3:

mckernel build failed:
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcctrl SUBDIRS=/tmp/build/mckernel/executer/kernel/mcctrl ARCH=x86_64 modules
make[2]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[2]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[2]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 SUBDIRS=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 ARCH=x86_64 modules
make[3]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[3]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[2]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[1]: Entering directory `/tmp/build/mckernel/executer/user'
(cd arch/x86_64; make)
make[2]: Entering directory `/tmp/build/mckernel/executer/user/arch/x86_64'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/tmp/build/mckernel/executer/user/arch/x86_64'
gcc -shared -fPIC -Wl,-soname,sched_yield.so.1 -o libsched_yield.so.1.0.0 /work/mcktest/git/mckernel/executer/user/libsched_yield.c -lc -ldl
make[1]: Leaving directory `/tmp/build/mckernel/executer/user'
make[1]: Entering directory `/tmp/build/mckernel/kernel'
make[1]: Circular /tmp/build/mckernel/kernel/build/smp-x86/kernel.img <- /tmp/build/mckernel/kernel/build/smp-x86/kernel.img dependency dropped.
Building for /tmp/build/mckernel/kernel/build/smp-x86/
 (smp-x86) DEPEND
 (smp-x86) CC /work/mcktest/git/mckernel/kernel/fileobj.c
/work/mcktest/git/mckernel/kernel/fileobj.c: In function ‘fileobj_create’:
/work/mcktest/git/mckernel/kernel/fileobj.c:239:13: error: ‘MAP_PRIVATE’ undeclared (first use in this function)
   ((flags & MAP_PRIVATE) ? MF_PRIVATE : 0);
             ^
/work/mcktest/git/mckernel/kernel/fileobj.c:239:13: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [fileobj.o] Error 1
 (smp-x86) BUILD IHK smp-x86
 (smp-x86) BUILD IHK smp-x86
 (smp-x86) DEPEND [IHK]
 (smp-x86) BUILD IKC [IHK] smp-x86
 (smp-x86) DEPEND [IKC]
make[2]: Target `all' not remade because of errors.
make[1]: *** [/tmp/build/mckernel/kernel/build/smp-x86/kernel.img] Error 2
make[1]: Target `all' not remade because of errors.
rm /tmp/build/mckernel/kernel/build/smp-x86/Makefile
make[1]: Leaving directory `/tmp/build/mckernel/kernel'
make: *** [mckernel] Error 2
make[1]: Entering directory `/tmp/build/mckernel/tools/mcstat'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/tmp/build/mckernel/tools/mcstat'
make: Target `all' not remade because of errors.

Patch-set: 3
Reviewer: riken-syssoft-gerrit <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>