Update patch set 1
Patch Set 1:

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 10%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 15%] Generating kmod_always_rebuild
[ 16%] Building kmod mcctrl
[ 17%] Built target mcctrl_ko
[ 20%] Built target eclair
[ 21%] Built target ldump2mcdump
[ 23%] Built target libmcexec
[ 24%] Built target mcexec
[ 26%] Built target mcinspect
[ 27%] Built target sched_yield
[ 28%] Building C object kernel/CMakeFiles/mckernel.img.dir/syscall.c.o
/work/mcktest/git/mckernel/kernel/syscall.c: In function ‘do_fork’:
/work/mcktest/git/mckernel/kernel/syscall.c:2872:3: error: implicit declaration of function ‘ihk_rwspinlock_read_lock_noirq’ [-Werror=implicit-function-declaration]
   ihk_rwspinlock_read_lock_noirq(&old->vm->memory_range_lock);
   ^
/work/mcktest/git/mckernel/kernel/syscall.c:2876:3: error: implicit declaration of function ‘ihk_rwspinlock_read_unlock_noirq’ [-Werror=implicit-function-declaration]
   ihk_rwspinlock_read_unlock_noirq(&old->vm->memory_range_lock);
   ^
/work/mcktest/git/mckernel/kernel/syscall.c:2870:17: error: unused variable ‘irqflags’ [-Werror=unused-variable]
   unsigned long irqflags;
                 ^
/work/mcktest/git/mckernel/kernel/syscall.c:2788:32: error: unused variable ‘cpu_info’ [-Werror=unused-variable]
  const struct ihk_mc_cpu_info *cpu_info = ihk_mc_get_cpu_info();
                                ^
/work/mcktest/git/mckernel/kernel/syscall.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/syscall.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 30%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>