Update patch set 18
Patch Set 18: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 15%] Generating kmod_always_rebuild
[ 16%] Building kmod mcctrl
[ 18%] Built target mcctrl_ko
[ 20%] Built target eclair
[ 22%] Built target ldump2mcdump
[ 23%] Built target libmcexec
[ 25%] Built target mcexec
[ 26%] Built target sched_yield
[ 27%] Building C object kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o
/work/mcktest/git/mckernel/kernel/xpmem.c: In function ‘xpmem_detach’:
/work/mcktest/git/mckernel/kernel/xpmem.c:1200:3: error: passing argument 2 of ‘ihk_rwspinlock_write_unlock’ makes integer from pointer without a cast [-Werror]
   ihk_rwspinlock_write_unlock(&att->at_lock, &at_lock);
   ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20:0,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/lib/include/ihk/lock.h:165:20: note: expected ‘long unsigned int’ but argument is of type ‘long unsigned int *’
 static inline void ihk_rwspinlock_write_unlock(ihk_rwspinlock_t *lock,
                    ^
/work/mcktest/git/mckernel/kernel/xpmem.c:1213:3: error: passing argument 2 of ‘ihk_rwspinlock_write_unlock’ makes integer from pointer without a cast [-Werror]
   ihk_rwspinlock_write_unlock(&att->at_lock, &at_lock);
   ^
In file included from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:20:0,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/xpmem.c:25:
/work/mcktest/git/mckernel/lib/include/ihk/lock.h:165:20: note: expected ‘long unsigned int’ but argument is of type ‘long unsigned int *’
 static inline void ihk_rwspinlock_write_unlock(ihk_rwspinlock_t *lock,
                    ^
/work/mcktest/git/mckernel/kernel/xpmem.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 29%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 18
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1