Update patch set 1
Patch Set 1: Verified-1

wallaby7: ihk build failed:
++ make -k
make[1]: Entering directory `/tmp/build/ihk/executer/kernel/mcctrl'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/ihk/executer/kernel/mcctrl SUBDIRS=/tmp/build/ihk/executer/kernel/mcctrl ARCH=x86_64 modules
make[2]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  CC [M]  /tmp/build/ihk/executer/kernel/mcctrl/driver.o
In file included from /work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/driver.c:32:0:
/work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/mcctrl.h:37:33: fatal error: ihk/ihk_host_driver.h: No such file or directory
 #include <ihk/ihk_host_driver.h>
                                 ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/executer/kernel/mcctrl/driver.o] Error 1
  CC [M]  /tmp/build/ihk/executer/kernel/mcctrl/control.o
In file included from /work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/control.c:45:0:
/work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/mcctrl.h:37:33: fatal error: ihk/ihk_host_driver.h: No such file or directory
 #include <ihk/ihk_host_driver.h>
                                 ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/executer/kernel/mcctrl/control.o] Error 1
  CC [M]  /tmp/build/ihk/executer/kernel/mcctrl/ikc.o
In file included from /work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/ikc.c:31:0:
/work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/mcctrl.h:37:33: fatal error: ihk/ihk_host_driver.h: No such file or directory
 #include <ihk/ihk_host_driver.h>
                                 ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/executer/kernel/mcctrl/ikc.o] Error 1
  CC [M]  /tmp/build/ihk/executer/kernel/mcctrl/syscall.o
In file included from /work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/syscall.c:50:0:
/work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/mcctrl.h:37:33: fatal error: ihk/ihk_host_driver.h: No such file or directory
 #include <ihk/ihk_host_driver.h>
                                 ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/executer/kernel/mcctrl/syscall.o] Error 1
  CC [M]  /tmp/build/ihk/executer/kernel/mcctrl/procfs.o
In file included from /work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/procfs.c:22:0:
/work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/mcctrl.h:37:33: fatal error: ihk/ihk_host_driver.h: No such file or directory
 #include <ihk/ihk_host_driver.h>
                                 ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/executer/kernel/mcctrl/procfs.o] Error 1
  CC [M]  /tmp/build/ihk/executer/kernel/mcctrl/binfmt_mcexec.o
In file included from /work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/binfmt_mcexec.c:14:0:
/work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/mcctrl.h:37:33: fatal error: ihk/ihk_host_driver.h: No such file or directory
 #include <ihk/ihk_host_driver.h>
                                 ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/executer/kernel/mcctrl/binfmt_mcexec.o] Error 1
  CC [M]  /tmp/build/ihk/executer/kernel/mcctrl/sysfs.o
In file included from /work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/sysfs.c:18:0:
/work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/mcctrl.h:37:33: fatal error: ihk/ihk_host_driver.h: No such file or directory
 #include <ihk/ihk_host_driver.h>
                                 ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/executer/kernel/mcctrl/sysfs.o] Error 1
  CC [M]  /tmp/build/ihk/executer/kernel/mcctrl/sysfs_files.o
In file included from /work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/sysfs_files.c:19:0:
/work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/mcctrl.h:37:33: fatal error: ihk/ihk_host_driver.h: No such file or directory
 #include <ihk/ihk_host_driver.h>
                                 ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/executer/kernel/mcctrl/sysfs_files.o] Error 1
  CC [M]  /tmp/build/ihk/executer/kernel/mcctrl/arch/x86_64/archdeps.o
In file included from /work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/arch/x86_64/archdeps.c:5:0:
/work/mcktest/git/mckernel/../ihk/executer/kernel/mcctrl/arch/x86_64/../../mcctrl.h:37:33: fatal error: ihk/ihk_host_driver.h: No such file or directory
 #include <ihk/ihk_host_driver.h>
                                 ^
compilation terminated.
make[3]: *** [/tmp/build/ihk/executer/kernel/mcctrl/arch/x86_64/archdeps.o] Error 1
make[3]: Target `__build' not remade because of errors.
make[2]: *** [_module_/tmp/build/ihk/executer/kernel/mcctrl] Error 2
make[2]: Target `modules' not remade because of errors.
make[2]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/tmp/build/ihk/executer/kernel/mcctrl'
make: *** [executer-mcctrl] Error 2
make[1]: Entering directory `/tmp/build/ihk/executer/kernel/mcoverlayfs'
make[2]: Entering directory `/tmp/build/ihk/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/ihk/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 SUBDIRS=/tmp/build/ihk/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 ARCH=x86_64 modules
make[3]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[3]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[2]: Leaving directory `/tmp/build/ihk/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make[1]: Leaving directory `/tmp/build/ihk/executer/kernel/mcoverlayfs'
make[1]: Entering directory `/tmp/build/ihk/executer/user'
(cd arch/x86_64; make)
make[2]: Entering directory `/tmp/build/ihk/executer/user/arch/x86_64'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/tmp/build/ihk/executer/user/arch/x86_64'
gcc -I/lib/modules/3.10.0-693.2.2.el7.x86_64/build -Wall -O -I. -I/work/mcktest/git/mckernel/../ihk/executer/user/arch/x86_64 -I/work/mcktest/git/mckernel/../ihk/executer/user/../../../ihk/linux/include/ -I/tmp/build/ihk/executer/user/../../../ihk/linux/include   -DLIBDIR=\"/tmp/install/lib\" -fPIE -pie -L. -lmcexec -lrt -lnuma -pthread -L/tmp/build/ihk/executer/user/../../../ihk/linux/user -lihk -Wl,-rpath,/tmp/install/lib -o mcexec /work/mcktest/git/mckernel/../ihk/executer/user/mcexec.c libmcexec.a  
/work/mcktest/git/mckernel/../ihk/executer/user/mcexec.c:79:31: fatal error: ihk/ihk_host_user.h: No such file or directory
 #include <ihk/ihk_host_user.h>
                               ^
compilation terminated.
make[1]: *** [mcexec] Error 1
gcc -shared -fPIC -Wl,-soname,sched_yield.so.1 -o libsched_yield.so.1.0.0 /work/mcktest/git/mckernel/../ihk/executer/user/libsched_yield.c -lc -ldl
gcc -I.. -I/work/mcktest/git/mckernel/../ihk/executer/user -I/work/mcktest/git/mckernel/../ihk/executer/user/arch/x86_64/include -Wall -O -I. -I/work/mcktest/git/mckernel/../ihk/executer/user/arch/x86_64 -I/work/mcktest/git/mckernel/../ihk/executer/user/../../../ihk/linux/include/ -I/tmp/build/ihk/executer/user/../../../ihk/linux/include -o eclair /work/mcktest/git/mckernel/../ihk/executer/user/eclair.c /work/mcktest/git/mckernel/../ihk/executer/user/arch/x86_64/arch-eclair.c -lbfd -liberty 
/work/mcktest/git/mckernel/../ihk/executer/user/eclair.c:22:31: fatal error: ihk/ihk_host_user.h: No such file or directory
 #include <ihk/ihk_host_user.h>
                               ^
compilation terminated.
make[1]: *** [eclair] Error 1
make[1]: Target `all' not remade because of errors.
make[1]: Leaving directory `/tmp/build/ihk/executer/user'
make: *** [executer-user] Error 2
make[1]: Entering directory `/tmp/build/ihk/kernel'
make[1]: Circular /tmp/build/ihk/kernel/build/smp-x86/kernel.img <- /tmp/build/ihk/kernel/build/smp-x86/kernel.img dependency dropped.
Building for /tmp/build/ihk/kernel/build/smp-x86/
Makefile:41: /tmp/build/ihk/kernel/../../ihk/cokernel/Makefile.common: No such file or directory
make[2]: *** No rule to make target `/tmp/build/ihk/kernel/../../ihk/cokernel/Makefile.common'.
make[2]: Failed to remake makefile `/tmp/build/ihk/kernel/../../ihk/cokernel/Makefile.common'.
C /work/mcktest/git/mckernel/../ihk/kernel/../../ihk/cokernel TARGET=smp-x86 O=/tmp/build/ihk/kernel/build/smp-x86/ihk CC=cc LD=ld SRC=/work/mcktest/git/mckernel/../ihk/kernel prepare
make[2]: C: Command not found
make[2]: [ihk/ihk.o] Error 127 (ignored)
C /work/mcktest/git/mckernel/../ihk/kernel/../../ihk/cokernel TARGET=smp-x86 O=/tmp/build/ihk/kernel/build/smp-x86/ihk CC=cc LD=ld SRC=/work/mcktest/git/mckernel/../ihk/kernel
make[2]: C: Command not found
make[2]: [ihk/ihk.o] Error 127 (ignored)
ld -e arch_start -T /work/mcktest/git/mckernel/../ihk/kernel/config/smp-x86.lds -o kernel.img.elf init.o mem.o debug.o mikc.o listeners.o ap.o syscall.o cls.o host.o process.o copy.o waitq.o futex.o timer.o plist.o fileobj.o shmobj.o zeroobj.o procfs.o devobj.o sysfs.o xpmem.o profile.o freeze.o rbtree.o hugefileobj.o pager.o ihk/ihk.o
ld: cannot find init.o: No such file or directory
ld: cannot find mem.o: No such file or directory
ld: cannot find debug.o: No such file or directory
ld: cannot find mikc.o: No such file or directory
ld: cannot find listeners.o: No such file or directory
ld: cannot find ap.o: No such file or directory
ld: cannot find syscall.o: No such file or directory
ld: cannot find cls.o: No such file or directory
ld: cannot find host.o: No such file or directory
ld: cannot find process.o: No such file or directory
ld: cannot find copy.o: No such file or directory
ld: cannot find waitq.o: No such file or directory
ld: cannot find futex.o: No such file or directory
ld: cannot find timer.o: No such file or directory
ld: cannot find plist.o: No such file or directory
ld: cannot find fileobj.o: No such file or directory
ld: cannot find shmobj.o: No such file or directory
ld: cannot find zeroobj.o: No such file or directory
ld: cannot find procfs.o: No such file or directory
ld: cannot find devobj.o: No such file or directory
ld: cannot find sysfs.o: No such file or directory
ld: cannot find xpmem.o: No such file or directory
ld: cannot find profile.o: No such file or directory
ld: cannot find freeze.o: No such file or directory
ld: cannot find rbtree.o: No such file or directory
ld: cannot find hugefileobj.o: No such file or directory
ld: cannot find pager.o: No such file or directory
ld: cannot find ihk/ihk.o: No such file or directory
make[2]: *** [kernel.img] Error 1
make[2]: Target `all' not remade because of errors.
make[1]: *** [/tmp/build/ihk/kernel/build/smp-x86/kernel.img] Error 2
make[1]: Target `all' not remade because of errors.
rm /tmp/build/ihk/kernel/build/smp-x86/Makefile
make[1]: Leaving directory `/tmp/build/ihk/kernel'
make: *** [mckernel] Error 2
make[1]: Entering directory `/tmp/build/ihk/tools/mcstat'
gcc -I/lib/modules/3.10.0-693.2.2.el7.x86_64/build -Wall -O -I. -I/work/mcktest/git/mckernel/../ihk/tools/mcstat/../../../ihk/linux/include/ -I/work/mcktest/git/mckernel/../ihk/tools/mcstat/../../executer/include   -o mcstat /work/mcktest/git/mckernel/../ihk/tools/mcstat/mcstat.c
/work/mcktest/git/mckernel/../ihk/tools/mcstat/mcstat.c:18:31: fatal error: ihk/ihk_host_user.h: No such file or directory
 #include <ihk/ihk_host_user.h>
                               ^
compilation terminated.
make[1]: *** [mcstat] Error 1
make[1]: Target `all' not remade because of errors.
make[1]: Leaving directory `/tmp/build/ihk/tools/mcstat'
make: *** [mck-tools] Error 2
make: Target `all' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1