Update patch set 10
Patch Set 10: Test-x86-1

MCKERNEL : mckernel-refs-changes-26-507126-10-?
IHK      : ihk-refs-changes-26-507126-10-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/507126/10 // 704120aa53ddcd9da43837f636f95c87b64558c6
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_refs-changes-26-507126-10_submodule
START : 20201214160857
END   : 20201214160917

+++ dirname /work/mcktest/bin/autobuild.sh
++ cd /work/mcktest/bin/..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ pwd
+ CWD=/
++ dirname /work/mcktest/bin/autobuild.sh
+ cd /work/mcktest/bin
+ . ./config.sh
+++ shopt -po xtrace
++ tracestate='set -o xtrace'
++ echo set -o xtrace
++ grep -q -
++ set +x
+ export BINDIR=
+ BINDIR=
+ bash -x ./wget-postpeta.sh mckernel refs-changes-26-507126-10
++ pwd
+ CWD=/work/mcktest/bin
+++ dirname ./wget-postpeta.sh
++ cd ./..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ dirname ./wget-postpeta.sh
+ cd .
+ . ./config.sh
+++ shopt -po xtrace
++ tracestate='set -o xtrace'
++ echo set -o xtrace
++ grep -q -
++ set +x
+ forwatchgerrit=0
+ REPO=mckernel
+ BRANCH=refs-changes-26-507126-10
+ case "$BRANCH" in
+ remote_type=gerrit-git
+ PATHSPEC=refs/changes/26/507126/10
+ '[' /work/mcktest/work_refs-changes-26-507126-10_submodule/src == '' ']'
+ '[' mckernel == '' ']'
+ DEST=mckernel
+ [[ -d /work/mcktest/work_refs-changes-26-507126-10_submodule/src ]]
+ rm -rf '/work/mcktest/work_refs-changes-26-507126-10_submodule/src/mckernel-*'
+ case $NODETYPE in
+ case $remote_type in
+ pushd /work/mcktest/git
/work/mcktest/git /work/mcktest/bin
+ sudo -u mcktest rm -rf mckernel
+ sudo -u mcktest git clone ssh://riken-syssoft-gerrit@review.gerrithub.io/RIKEN-SysSoft/mckernel
Cloning into 'mckernel'...
Total 32446 (delta 20947), reused 31970 (delta 20947)
+ cd mckernel
+ sudo -u mcktest git fetch origin refs/changes/26/507126/10
From ssh://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/26/507126/10 -> FETCH_HEAD
++ sudo -u mcktest git rev-parse FETCH_HEAD
+ COMMIT=704120aa53ddcd9da43837f636f95c87b64558c6
+ DEST=mckernel-refs-changes-26-507126-10-704120aa53ddcd9da43837f636f95c87b64558c6
+ popd
/work/mcktest/bin
+ '[' 0 -ne 0 ']'
+ '[' 0 -eq 1 ']'
+ case $remote_type in
+ mkdir /work/mcktest/work_refs-changes-26-507126-10_submodule/src/mckernel-refs-changes-26-507126-10-704120aa53ddcd9da43837f636f95c87b64558c6
+ cd /work/mcktest/work_refs-changes-26-507126-10_submodule/src/mckernel-refs-changes-26-507126-10-704120aa53ddcd9da43837f636f95c87b64558c6
+ GIT_DIR=/work/mcktest/git/mckernel/.git
+ git reset --hard 704120aa53ddcd9da43837f636f95c87b64558c6
HEAD is now at 704120a TO RESET: page_fault_handler: send SIGSTOP instead of SIGSEGV for debug
+ GIT_DIR=/work/mcktest/git/mckernel/.git
+ git submodule update --init
From https://github.com/bgerofi/libdwarf
 * [new branch]      alt        -> origin/alt
 * [new branch]      exprloc    -> origin/exprloc
 * [new branch]      master     -> origin/master
 * [new branch]      suppress_warnings -> origin/suppress_warnings
Submodule path 'executer/user/lib/libdwarf/libdwarf': checked out 'ab9230b2b8aa66a3d1d52e4be11fca17a3b63753'
From https://github.com/RIKEN-SysSoft/ihk
 * [new branch]      a64fx      -> origin/a64fx
 * [new branch]      bbtest5b_merge18 -> origin/bbtest5b_merge18
 * [new branch]      bbtest5b_merge22 -> origin/bbtest5b_merge22
 * [new branch]      dev+fix    -> origin/dev+fix
 * [new branch]      dev+fix+pkm -> origin/dev+fix+pkm
 * [new branch]      dev+fix-riken2 -> origin/dev+fix-riken2
 * [new branch]      development -> origin/development
 * [new branch]      development+a64fx-rebased -> origin/development+a64fx-rebased
 * [new branch]      development+a64fx-rebased+fullview -> origin/development+a64fx-rebased+fullview
 * [new branch]      development+a64fx-rebased+tofu -> origin/development+a64fx-rebased+tofu
 * [new branch]      development+apollo -> origin/development+apollo
 * [new branch]      development+apollo+a64fx -> origin/development+apollo+a64fx
 * [new branch]      development+apollo+a64fx+fullview -> origin/development+apollo+a64fx+fullview
 * [new branch]      development+apollo+a64fx2 -> origin/development+apollo+a64fx2
 * [new branch]      development+gerrithubrefs -> origin/development+gerrithubrefs
 * [new branch]      development+unimap+hfi -> origin/development+unimap+hfi
 * [new branch]      development+unimap+uti_extract78 -> origin/development+unimap+uti_extract78
 * [new branch]      fix_ihklib -> origin/fix_ihklib
 * [new branch]      fix_uti_kstack2 -> origin/fix_uti_kstack2
 * [new branch]      for_uti_test -> origin/for_uti_test
 * [new branch]      ihk_api_bbtest6 -> origin/ihk_api_bbtest6
 * [new branch]      ihk_api_bbtest7 -> origin/ihk_api_bbtest7
 * [new branch]      master     -> origin/master
 * [new branch]      merge-no-full-view2 -> origin/merge-no-full-view2
 * [new branch]      postk_master -> origin/postk_master
 * [new branch]      rebase3.1  -> origin/rebase3.1
 * [new branch]      rebase3.2  -> origin/rebase3.2
 * [new branch]      wip_ihklib -> origin/wip_ihklib
 * [new tag]         0.4.0      -> 0.4.0
 * [new tag]         0.9.0      -> 0.9.0
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.1.1      -> 1.1.1
 * [new tag]         1.1.2      -> 1.1.2
 * [new tag]         1.1.3      -> 1.1.3
 * [new tag]         1.2.0      -> 1.2.0
 * [new tag]         1.2.1      -> 1.2.1
 * [new tag]         1.2.2      -> 1.2.2
 * [new tag]         1.2.3      -> 1.2.3
 * [new tag]         1.2.4      -> 1.2.4
 * [new tag]         1.2.5      -> 1.2.5
 * [new tag]         1.2.6      -> 1.2.6
 * [new tag]         1.3.0      -> 1.3.0
 * [new tag]         1.4.0      -> 1.4.0
 * [new tag]         1.5.0      -> 1.5.0
 * [new tag]         1.5.0-knl+hfi -> 1.5.0-knl+hfi
 * [new tag]         1.5.1      -> 1.5.1
 * [new tag]         1.5.1-rc1  -> 1.5.1-rc1
 * [new tag]         1.6.0      -> 1.6.0
 * [new tag]         1.7.0-0.2  -> 1.7.0-0.2
 * [new tag]         1.7.0-0.3  -> 1.7.0-0.3
 * [new tag]         fj_test_201902 -> fj_test_201902
fatal: Unable to create '/work/mcktest/git/mckernel/.git/modules/ihk/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
Unable to checkout 'bda97c4cf7385896700868c4efbabe62f685ae82' in submodule path 'ihk'
+ error 'submodule update failed'
++ basename ./wget-postpeta.sh
+ echo 'wget-postpeta.sh: ERROR: submodule update failed'
wget-postpeta.sh: ERROR: submodule update failed
+ cd /work/mcktest/bin
+ exit -1
+ error 'autobuild.sh couldn'\''t get mckernel'
+ echo 'ERROR: autobuild.sh couldn'\''t get mckernel'
ERROR: autobuild.sh couldn't get mckernel
+ cd /
+ exit -1

Patch-set: 10
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Test-x86=-1