Update patch set 3
Patch Set 3: Build-arm64-1

apollo15: build report: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  5%] Built target ihkconfig
[  6%] Built target ihkmond
[  7%] Built target ihkosctl
[  8%] Generating kmod_always_rebuild
[  9%] Building kmod ihk-smp-arm64
[ 10%] Built target ihk-smp-arm64_ko
[ 11%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/arm64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/arm64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 12%] Building kmod mcctrl
/tmp/mckernel/executer/kernel/mcctrl/syscall.c: In function ‘__return_syscall’:
/tmp/mckernel/executer/kernel/mcctrl/syscall.c:1906:5: error: ‘MAX_USER_VA_BITS’ undeclared (first use in this function)
     MAX_USER_VA_BITS, PGDIR_SHIFT);
     ^
/tmp/mckernel/executer/kernel/mcctrl/syscall.c:1906:5: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/syscall.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 14%] Built target eclair
[ 15%] Built target ldump2mcdump
[ 16%] Built target libmcexec
[ 17%] Built target mcexec
[ 18%] Built target mcinspect
[ 19%] Built target sched_yield
[ 20%] Building C object kernel/CMakeFiles/mckernel.img.dir/host.c.o
/tmp/mckernel/kernel/host.c: In function ‘process_msg_prepare_process’:
/tmp/mckernel/kernel/host.c:553:3: error: implicit declaration of function ‘tof_utofu_finalize’ [-Werror=implicit-function-declaration]
   tof_utofu_finalize();
   ^
/tmp/mckernel/kernel/host.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/host.c.o] Error 1
[ 21%] Building C object kernel/CMakeFiles/mckernel.img.dir/tofu/tof_utofu_main.c.o
/tmp/mckernel/kernel/tofu/tof_utofu_main.c: In function ‘tof_utofu_init_globals’:
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1359:34: error: dereferencing pointer to incomplete type
  tof_ib_stag_list = (int16_t *)tg->tof_ib_stag_list_addr;
                                  ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1360:41: error: dereferencing pointer to incomplete type
  tof_ib_stag_lock = (ihk_spinlock_t *)tg->tof_ib_stag_lock_addr;
                                         ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1361:38: error: dereferencing pointer to incomplete type
  tof_ib_stag_list_Rp_addr = (int *)tg->tof_ib_stag_list_Rp_addr;
                                      ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1362:38: error: dereferencing pointer to incomplete type
  tof_ib_stag_list_Wp_addr = (int *)tg->tof_ib_stag_list_Wp_addr;
                                      ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1364:36: error: dereferencing pointer to incomplete type
   (struct tof_util_aligned_mem *)tg->tof_ib_mbpt_mem_addr;
                                    ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1366:38: error: dereferencing pointer to incomplete type
   (struct tof_icc_steering_entry *)tg->tof_ib_steering_addr;
                                      ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1368:32: error: dereferencing pointer to incomplete type
   (struct tof_icc_mb_entry *)tg->tof_ib_mb_addr;
                                ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1370:27: error: dereferencing pointer to incomplete type
   (struct tof_core_cq *)tg->tof_core_cq_addr;
                           ^
In file included from /tmp/mckernel/arch/arm64/kernel/include/arch-lock.h:12:0,
                 from /tmp/mckernel/lib/include/ihk/lock.h:16,
                 from /tmp/mckernel/lib/include/ihk/mm.h:20,
                 from /tmp/mckernel/kernel/include/kmalloc.h:16,
                 from /tmp/mckernel/kernel/tofu/tof_utofu_main.c:5:
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1373:15: error: dereferencing pointer to incomplete type
   __func__, tg->tof_ib_stag_lock_addr);
               ^
/tmp/mckernel/lib/include/ihk/debug.h:44:18: note: in definition of macro ‘dkprintf’
   kprintf(fmt, ##args); \
                  ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1375:16: error: dereferencing pointer to incomplete type
    __func__, tg->tof_ib_stag_list_Wp_addr);
                ^
/tmp/mckernel/lib/include/ihk/debug.h:44:18: note: in definition of macro ‘dkprintf’
   kprintf(fmt, ##args); \
                  ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1377:25: error: dereferencing pointer to incomplete type
    __func__, *((int *)tg->tof_ib_stag_list_Wp_addr));
                         ^
/tmp/mckernel/lib/include/ihk/debug.h:44:18: note: in definition of macro ‘dkprintf’
   kprintf(fmt, ##args); \
                  ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1378:55: error: dereferencing pointer to incomplete type
  kprintf("%s: linux_vmalloc_start: %p\n", __func__, tg->linux_vmalloc_start);
                                                       ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c: In function ‘tof_utofu_finalize’:
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1387:38: error: dereferencing pointer to incomplete type
  ihk_mc_clear_kernel_range((void *)tg->linux_vmalloc_start,
                                      ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c:1388:14: error: dereferencing pointer to incomplete type
    (void *)tg->linux_vmalloc_end);
              ^
/tmp/mckernel/kernel/tofu/tof_utofu_main.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/tofu/tof_utofu_main.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 22%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 3
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1