Update patch set 1
Patch Set 1: Test-arm64-1

MCKERNEL : mckernel-refs-changes-85-442685-1-?
IHK      : ihk-refs-changes-85-442685-1-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/442685/1 // 3b167cfec362f643f6f1c9c1ab340e8f289bfe39
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 2-11,30-39 -m 10G@0,10G@1 -r 2-6:0+7-11:1+30-34:28+35-39:29 -o root -O
HOST  : apollo16.postk.local.r-ccs.riken.jp
DIR   : /work/mcktest/work_refs-changes-85-442685-1_submodule
START : 20190320195808
END   : 20190320195812

From https://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/85/442685/1 -> FETCH_HEAD
HEAD is now at 3b167cf syscall_backward: allocate request instead of using stack
fatal: Could not parse object '58fdc1d8a85af166913392f159e6b7cc8f9c01d0'.
wget-postpeta.sh: ERROR: commit not found in repo
ERROR: autobuild.sh couldn't get ihk

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Test-arm64=-1