Update patch set 3
Patch Set 3:

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 15%] Generating kmod_always_rebuild
[ 16%] Building kmod mcctrl
[ 18%] Built target mcctrl_ko
[ 20%] Built target eclair
[ 22%] Built target ldump2mcdump
[ 23%] Built target libmcexec
[ 25%] Built target mcexec
[ 26%] Built target sched_yield
[ 27%] Building C object kernel/CMakeFiles/mckernel.img.dir/mem.c.o
/work/mcktest/git/mckernel/kernel/mem.c: In function ‘ihk_mc_query_mem_areas’:
/work/mcktest/git/mckernel/kernel/mem.c:2509:6: error: ‘DUMP_LEVEL_USER_UNUSED_EXCLUDE’ undeclared (first use in this function)
  if (DUMP_LEVEL_USER_UNUSED_EXCLUDE == ihk_mc_get_dump_level()) {
      ^
/work/mcktest/git/mckernel/kernel/mem.c:2509:6: note: each undeclared identifier is reported only once for each function it appears in
/work/mcktest/git/mckernel/kernel/mem.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/mem.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 29%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 3
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>