Update patch set 6
Patch Set 6: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Building C object ihk/linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
/work/mcktest/git/mckernel/ihk/linux/user/ihklib.c: In function ‘ihk_os_get_status’:
/work/mcktest/git/mckernel/ihk/linux/user/ihklib.c:2113:7: error: ‘IHK_OS_STATUS_STOPPED’ undeclared (first use in this function)
  case IHK_OS_STATUS_STOPPED:
       ^
/work/mcktest/git/mckernel/ihk/linux/user/ihklib.c:2113:7: note: each undeclared identifier is reported only once for each function it appears in
/work/mcktest/git/mckernel/ihk/linux/user/ihklib.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [ihk/linux/user/CMakeFiles/ihklib.dir/ihklib.c.o] Error 1
make[2]: Target `ihk/linux/user/CMakeFiles/ihklib.dir/build' not remade because of errors.
make[1]: *** [ihk/linux/user/CMakeFiles/ihklib.dir/all] Error 2
[  6%] Generating kmod_always_rebuild
[  8%] Building kmod ihk-smp-x86_64
[  9%] Built target ihk-smp-x86_64_ko
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod mcctrl
[ 13%] Built target mcctrl_ko
[ 16%] Built target eclair
[ 18%] Built target ldump2mcdump
[ 19%] Built target libmcexec
[ 20%] Built target mcexec
[ 22%] Built target sched_yield
[ 94%] Built target mckernel.img
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 6
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1