Update patch set 4
Patch Set 4:

mckernel build failed:
++ make -k
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcctrl SUBDIRS=/tmp/build/mckernel/executer/kernel/mcctrl ARCH=x86_64 modules
make[2]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  CC [M]  /tmp/build/mckernel/executer/kernel/mcctrl/driver.o
  CC [M]  /tmp/build/mckernel/executer/kernel/mcctrl/control.o
  CC [M]  /tmp/build/mckernel/executer/kernel/mcctrl/ikc.o
/work/mcktest/git/mckernel/executer/kernel/mcctrl/ikc.c:31:20: fatal error: mcctrl.h: No such file or directory
compilation terminated.
make[3]: *** [/tmp/build/mckernel/executer/kernel/mcctrl/ikc.o] Error 1
make[3]: *** No rule to make target `/work/mcktest/git/mckernel/executer/kernel/mcctrl/syscall.c', needed by `/tmp/build/mckernel/executer/kernel/mcctrl/syscall.o'.
make[3]: *** No rule to make target `/work/mcktest/git/mckernel/executer/kernel/mcctrl/procfs.c', needed by `/tmp/build/mckernel/executer/kernel/mcctrl/procfs.o'.
make[3]: *** No rule to make target `/work/mcktest/git/mckernel/executer/kernel/mcctrl/binfmt_mcexec.c', needed by `/tmp/build/mckernel/executer/kernel/mcctrl/binfmt_mcexec.o'.
make[3]: *** No rule to make target `/work/mcktest/git/mckernel/executer/kernel/mcctrl/sysfs.c', needed by `/tmp/build/mckernel/executer/kernel/mcctrl/sysfs.o'.
make[3]: *** No rule to make target `/work/mcktest/git/mckernel/executer/kernel/mcctrl/sysfs_files.c', needed by `/tmp/build/mckernel/executer/kernel/mcctrl/sysfs_files.o'.
make[3]: *** No rule to make target `/work/mcktest/git/mckernel/executer/kernel/mcctrl/arch/x86_64/archdeps.c', needed by `/tmp/build/mckernel/executer/kernel/mcctrl/arch/x86_64/archdeps.o'.
make[3]: Target `__build' not remade because of errors.
make[2]: *** [_module_/tmp/build/mckernel/executer/kernel/mcctrl] Error 2
make[2]: Target `modules' not remade because of errors.
make[2]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make: *** [executer-mcctrl] Error 2
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[2]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 SUBDIRS=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 ARCH=x86_64 modules
make[3]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
WARNING: could not open /work/mcktest/git/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7/copy_up.c: No such file or directory
  CC      /tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7/mcoverlay.mod.o
  LD [M]  /tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7/mcoverlay.ko
make[3]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[2]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[1]: Entering directory `/tmp/build/mckernel/executer/user'
make[1]: *** No rule to make target `mcexec.c', needed by `mcexec'.
(cd arch/x86_64; make)
make[2]: Entering directory `/tmp/build/mckernel/executer/user/arch/x86_64'
make[2]: *** No rule to make target `archdep.S', needed by `archdep.o'.
make[2]: *** No rule to make target `arch_syscall.c', needed by `arch_syscall.o'.
make[2]: *** No rule to make target `archdep_c.c', needed by `archdep_c.o'.
make[2]: Target `all' not remade because of errors.
make[2]: Leaving directory `/tmp/build/mckernel/executer/user/arch/x86_64'
make[1]: *** [libmcexec.a] Error 2
make[1]: *** No rule to make target `libsched_yield.c', needed by `libsched_yield'.
make[1]: *** No rule to make target `ldump2mcdump.c', needed by `ldump2mcdump.so'.
make[1]: *** No rule to make target `eclair.c', needed by `eclair'.
make[1]: *** No rule to make target `arch/x86_64/arch-eclair.c', needed by `eclair'.
make[1]: Target `all' not remade because of errors.
make[1]: Leaving directory `/tmp/build/mckernel/executer/user'
make: *** [executer-user] Error 2
make[1]: Entering directory `/tmp/build/mckernel/kernel'
make[1]: Circular /tmp/build/mckernel/kernel/build/smp-x86/kernel.img <- /tmp/build/mckernel/kernel/build/smp-x86/kernel.img dependency dropped.
Building for /tmp/build/mckernel/kernel/build/smp-x86/
Makefile:39: /work/mcktest/git/mckernel/kernel/config/config.smp-x86: No such file or directory
 (smp-x86) DEPEND
cc: fatal error: no input files
compilation terminated.
make[2]: *** No rule to make target `/work/mcktest/git/mckernel/kernel/config/config.smp-x86'.
make[2]: Failed to remake makefile `/work/mcktest/git/mckernel/kernel/config/config.smp-x86'.
make[2]: *** No rule to make target `Makefile.dep', needed by `depend'.
make[2]: *** No rule to make target `init.o', needed by `kernel.img'.
make[2]: *** No rule to make target `mem.o', needed by `kernel.img'.
make[2]: *** No rule to make target `debug.o', needed by `kernel.img'.
make[2]: *** No rule to make target `mikc.o', needed by `kernel.img'.
make[2]: *** No rule to make target `listeners.o', needed by `kernel.img'.
make[2]: *** No rule to make target `ap.o', needed by `kernel.img'.
make[2]: *** No rule to make target `syscall.o', needed by `kernel.img'.
make[2]: *** No rule to make target `cls.o', needed by `kernel.img'.
make[2]: *** No rule to make target `host.o', needed by `kernel.img'.
make[2]: *** No rule to make target `process.o', needed by `kernel.img'.
make[2]: *** No rule to make target `waitq.o', needed by `kernel.img'.
make[2]: *** No rule to make target `futex.o', needed by `kernel.img'.
make[2]: *** No rule to make target `timer.o', needed by `kernel.img'.
make[2]: *** No rule to make target `fileobj.o', needed by `kernel.img'.
make[2]: *** No rule to make target `shmobj.o', needed by `kernel.img'.
make[2]: *** No rule to make target `zeroobj.o', needed by `kernel.img'.
make[2]: *** No rule to make target `procfs.o', needed by `kernel.img'.
make[2]: *** No rule to make target `devobj.o', needed by `kernel.img'.
make[2]: *** No rule to make target `sysfs.o', needed by `kernel.img'.
make[2]: *** No rule to make target `xpmem.o', needed by `kernel.img'.
make[2]: *** No rule to make target `profile.o', needed by `kernel.img'.
make[2]: *** No rule to make target `freeze.o', needed by `kernel.img'.
make[2]: *** No rule to make target `hugefileobj.o', needed by `kernel.img'.
make[2]: *** No rule to make target `pager.o', needed by `kernel.img'.
 (smp-x86) BUILD IHK smp-x86
make: *** /work/mcktest/git/mckernel/kernel/../../ihk/cokernel: No such file or directory.  Stop.
make[2]: *** [ihk/ihk.o] Error 2
make[2]: Target `all' not remade because of errors.
make[1]: *** [/tmp/build/mckernel/kernel/build/smp-x86/kernel.img] Error 2
make[1]: Target `all' not remade because of errors.
rm /tmp/build/mckernel/kernel/build/smp-x86/Makefile
make[1]: Leaving directory `/tmp/build/mckernel/kernel'
make: *** [mckernel] Error 2
make[1]: Entering directory `/tmp/build/mckernel/tools/mcstat'
make[1]: *** No rule to make target `mcstat.c', needed by `mcstat'.
make[1]: Target `all' not remade because of errors.
make[1]: Leaving directory `/tmp/build/mckernel/tools/mcstat'
make: *** [mck-tools] Error 2
make: Target `all' not remade because of errors.

Patch-set: 4
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>