Update patch set 2
Patch Set 2:

ARM MCKERNEL : mckernel-refs-changes-13-427613-2-?
IHK      : ihk-refs-changes-13-427613-2-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/427613/2 // ebee0b93bb3da516067c57537e7978c83131a419
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6 -m 58G@0,58G@1 -c 4-27,32-55 -r 4-9:0+10-15:1+16-21:2+22-27:3+32-37:28+38-43:29+44-49:30+50-55:31 -O
HOST  : apollo15.postk.local.r-ccs.riken.jp
DIR   : /work/mcktest/work_refs-changes-13-427613-2_submodule
START : 20200422132147
END   : 20200422132207

/work/mcktest/git /work/mcktest/bin
Cloning into 'mckernel'...
Total 31452 (delta 20385), reused 31083 (delta 20385)
Total 152 (delta 52), reused 111 (delta 52)
From ssh://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/13/427613/2 -> FETCH_HEAD
/work/mcktest/bin
HEAD is now at ebee0b93 cmake: Add ENABLE_STACK_PROTECTOR
ihk: submodule commit resolved to refs-changes-18-427618-8
/work/mcktest/git /work/mcktest/bin
Cloning into 'ihk'...
Total 6649 (delta 4582), reused 6491 (delta 4582)
From ssh://review.gerrithub.io/RIKEN-SysSoft/ihk
 * branch            refs/changes/18/427618/8 -> FETCH_HEAD
/work/mcktest/bin
HEAD is now at b7c9bb6 build system: switch to cmake
MCKBUILD=/work/mcktest/work_refs-changes-13-427613-2_submodule/build
MCKINSTALL=/home/toshi/install/dev2-mckernel
-- The C compiler identification is GNU 4.8.5
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
fatal: not a git repository: '/work/mcktest/work_refs-changes-13-427613-2_submodule/src/mckernel/ihk/.git'
CMake Warning (dev) at CMakeLists.txt:107 (add_subdirectory):
  The source directory

    /work/mcktest/work_refs-changes-13-427613-2_submodule/src/mckernel/ihk

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

Defined module mcctrl
CMake Error at executer/kernel/mcoverlayfs/CMakeLists.txt:11 (message):
  mcoverlayfs enabled but kernel version not compatible


-- Configuring incomplete, errors occurred!
See also "/work/mcktest/work_refs-changes-13-427613-2_submodule/build/4.14.0-115.13.1.1chaos.el7a.aarch64/CMakeFiles/CMakeOutput.log".
ERROR: autobuild.sh failed

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>