Update patch set 5
Patch Set 5: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 10%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 15%] Generating kmod_always_rebuild
[ 16%] Building kmod mcctrl
[ 17%] Built target mcctrl_ko
[ 20%] Built target eclair
[ 21%] Built target ldump2mcdump
[ 23%] Built target libmcexec
[ 24%] Built target mcexec
[ 26%] Building C object executer/user/CMakeFiles/mcinspect.dir/mcinspect.c.o
/work/mcktest/git/mckernel/executer/user/mcinspect.c:21:19: fatal error: dwarf.h: No such file or directory
 #include <dwarf.h>
                   ^
compilation terminated.
make[2]: *** [executer/user/CMakeFiles/mcinspect.dir/mcinspect.c.o] Error 1
make[2]: Target `executer/user/CMakeFiles/mcinspect.dir/build' not remade because of errors.
make[1]: *** [executer/user/CMakeFiles/mcinspect.dir/all] Error 2
[ 27%] Built target sched_yield
[ 98%] Built target mckernel.img
[100%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 5
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1