Update patch set 1
Patch Set 1: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  7%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 14%] Built target ihk-smp-x86_64_ko
[ 15%] Generating kmod_always_rebuild
[ 16%] Building kmod mcctrl
[ 18%] Built target mcctrl_ko
[ 19%] Building C object executer/user/CMakeFiles/eclair.dir/arch/x86_64/arch-eclair.c.o
/work/mcktest/git/mckernel/executer/user/arch/x86_64/arch-eclair.c:104:18: error: static declaration of ‘virt_to_phys’ follows non-static declaration
 static uintptr_t virt_to_phys(uintptr_t va)
                  ^
In file included from /work/mcktest/git/mckernel/executer/user/eclair.h:9:0,
                 from /work/mcktest/git/mckernel/executer/user/arch/x86_64/arch-eclair.c:2:
/work/mcktest/git/mckernel/executer/user/arch/x86_64/include/arch-eclair.h:35:11: note: previous declaration of ‘virt_to_phys’ was here
 uintptr_t virt_to_phys(uintptr_t va);
           ^
/work/mcktest/git/mckernel/executer/user/arch/x86_64/arch-eclair.c: In function ‘virt_to_phys’:
/work/mcktest/git/mckernel/executer/user/arch/x86_64/arch-eclair.c:108:12: error: ‘MAP_KERNEL_START’ undeclared (first use in this function)
  if (va >= MAP_KERNEL_START) {
            ^
/work/mcktest/git/mckernel/executer/user/arch/x86_64/arch-eclair.c:108:12: note: each undeclared identifier is reported only once for each function it appears in
/work/mcktest/git/mckernel/executer/user/arch/x86_64/arch-eclair.c:111:17: error: ‘LINUX_PAGE_OFFSET’ undeclared (first use in this function)
  else if (va >= LINUX_PAGE_OFFSET) {
                 ^
/work/mcktest/git/mckernel/executer/user/arch/x86_64/arch-eclair.c:114:17: error: ‘MAP_FIXED_START’ undeclared (first use in this function)
  else if (va >= MAP_FIXED_START) {
                 ^
/work/mcktest/git/mckernel/executer/user/arch/x86_64/arch-eclair.c:117:17: error: ‘MAP_ST_START’ undeclared (first use in this function)
  else if (va >= MAP_ST_START) {
                 ^
make[2]: *** [executer/user/CMakeFiles/eclair.dir/arch/x86_64/arch-eclair.c.o] Error 1
make[2]: Target `executer/user/CMakeFiles/eclair.dir/build' not remade because of errors.
make[1]: *** [executer/user/CMakeFiles/eclair.dir/all] Error 2
[ 21%] Built target ldump2mcdump
[ 22%] Built target libmcexec
[ 23%] Built target mcexec
[ 25%] Built target sched_yield
[ 97%] Built target mckernel.img
[ 98%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1