Update patch set 5
Patch Set 5: Verified-1

build failed for aarch64:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  5%] Built target ihkconfig
[  6%] Built target ihkmond
[  7%] Built target ihkosctl
[  8%] Generating kmod_always_rebuild
[  9%] Building kmod ihk-smp-arm64
[ 10%] Built target ihk-smp-arm64_ko
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod mcctrl
[ 13%] Built target mcctrl_ko
[ 14%] Building C object executer/user/CMakeFiles/eclair.dir/arch/arm64/arch-eclair.c.o
/work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c: In function ‘print_kregs’:
/work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c:43:2: error: passing argument 1 of ‘dprintf’ makes integer from pointer without a cast [-Werror]
  dprintf("%s: FP: %s, kregs->fp: 0x%lx\n", __func__, rbp, kregs->fp);
  ^
In file included from /work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c:2:0:
/usr/aarch64-linux-gnu/sys-root/usr/include/stdio.h:415:12: note: expected ‘int’ but argument is of type ‘char *’
 extern int dprintf (int __fd, const char *__restrict __fmt, ...)
            ^
/work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c:43:2: error: too many arguments for format [-Werror=format-extra-args]
  dprintf("%s: FP: %s, kregs->fp: 0x%lx\n", __func__, rbp, kregs->fp);
  ^
/work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c:64:2: error: passing argument 1 of ‘dprintf’ makes integer from pointer without a cast [-Werror]
  dprintf("%s: SP: %s, kregs->sp: 0x%lx\n", __func__, rbp, kregs->sp);
  ^
In file included from /work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c:2:0:
/usr/aarch64-linux-gnu/sys-root/usr/include/stdio.h:415:12: note: expected ‘int’ but argument is of type ‘char *’
 extern int dprintf (int __fd, const char *__restrict __fmt, ...)
            ^
/work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c:64:2: error: too many arguments for format [-Werror=format-extra-args]
  dprintf("%s: SP: %s, kregs->sp: 0x%lx\n", __func__, rbp, kregs->sp);
  ^
/work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c:74:2: error: passing argument 1 of ‘dprintf’ makes integer from pointer without a cast [-Werror]
  dprintf("%s: PC: %s, kregs->pc: 0x%lx\n", __func__, rbp, kregs->pc);
  ^
In file included from /work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c:2:0:
/usr/aarch64-linux-gnu/sys-root/usr/include/stdio.h:415:12: note: expected ‘int’ but argument is of type ‘char *’
 extern int dprintf (int __fd, const char *__restrict __fmt, ...)
            ^
/work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c:74:2: error: too many arguments for format [-Werror=format-extra-args]
  dprintf("%s: PC: %s, kregs->pc: 0x%lx\n", __func__, rbp, kregs->pc);
  ^
/work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c:89:2: error: passing argument 1 of ‘dprintf’ makes integer from pointer without a cast [-Werror]
  dprintf("%s: total: %d\n", __func__, total);
  ^
In file included from /work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c:2:0:
/usr/aarch64-linux-gnu/sys-root/usr/include/stdio.h:415:12: note: expected ‘int’ but argument is of type ‘char *’
 extern int dprintf (int __fd, const char *__restrict __fmt, ...)
            ^
/work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c:89:2: error: too many arguments for format [-Werror=format-extra-args]
  dprintf("%s: total: %d\n", __func__, total);
  ^
/work/mcktest/git/mckernel/executer/user/arch/arm64/arch-eclair.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [executer/user/CMakeFiles/eclair.dir/arch/arm64/arch-eclair.c.o] Error 1
make[2]: Target `executer/user/CMakeFiles/eclair.dir/build' not remade because of errors.
make[1]: *** [executer/user/CMakeFiles/eclair.dir/all] Error 2
[ 15%] Built target ldump2mcdump
[ 16%] Built target libmcexec
[ 17%] Built target mcexec
[ 18%] Built target sched_yield
[ 97%] Built target mckernel.img
[ 98%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 5
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1