Update patch set 2
Patch Set 2: Verified-1

mckernel build failed:
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcctrl SUBDIRS=/tmp/build/mckernel/executer/kernel/mcctrl ARCH=x86_64 modules
make[2]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  CC [M]  /tmp/build/mckernel/executer/kernel/mcctrl/control.o
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c: In function ‘mcctrl_perf_set’:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:2123:32: error: ‘ARCH_PERF_CONTER_START’ undeclared (first use in this function)
   perf_desc->target_cntr = i + ARCH_PERF_CONTER_START;
                                ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:2123:32: note: each undeclared identifier is reported only once for each function it appears in
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c: In function ‘mcctrl_perf_get’:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:2183:32: error: ‘ARCH_PERF_CONTER_START’ undeclared (first use in this function)
   perf_desc->target_cntr = i + ARCH_PERF_CONTER_START;
                                ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c: In function ‘mcctrl_perf_enable’:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:2230:28: error: ‘ARCH_PERF_CONTER_START’ undeclared (first use in this function)
   cntr_mask |= 1UL << (i + ARCH_PERF_CONTER_START);
                            ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c: In function ‘mcctrl_perf_disable’:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:2283:28: error: ‘ARCH_PERF_CONTER_START’ undeclared (first use in this function)
   cntr_mask |= 1UL << (i + ARCH_PERF_CONTER_START);
                            ^
make[3]: *** [/tmp/build/mckernel/executer/kernel/mcctrl/control.o] Error 1
  CC [M]  /tmp/build/mckernel/executer/kernel/mcctrl/syscall.o
/work/mcktest/git/mckernel/executer/kernel/mcctrl/syscall.c: In function ‘rus_mmap’:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/syscall.c:989:19: error: ‘arch_rus_vm_flags’ undeclared (first use in this function)
  vma->vm_flags |= arch_rus_vm_flags;
                   ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/syscall.c:989:19: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [/tmp/build/mckernel/executer/kernel/mcctrl/syscall.o] Error 1
make[3]: Target `__build' not remade because of errors.
make[2]: *** [_module_/tmp/build/mckernel/executer/kernel/mcctrl] Error 2
make[2]: Target `modules' not remade because of errors.
make[2]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcctrl'
make: *** [executer-mcctrl] Error 2
make[1]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[2]: Entering directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make -C /lib/modules/3.10.0-693.2.2.el7.x86_64/build M=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 SUBDIRS=/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7 ARCH=x86_64 modules
make[3]: Entering directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[3]: Leaving directory `/usr/src/kernels/3.10.0-693.2.2.el7.x86_64'
make[2]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs/linux-3.10.0-327.36.1.el7'
make[1]: Leaving directory `/tmp/build/mckernel/executer/kernel/mcoverlayfs'
make[1]: Entering directory `/tmp/build/mckernel/executer/user'
(cd arch/x86_64; make)
make[2]: Entering directory `/tmp/build/mckernel/executer/user/arch/x86_64'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/tmp/build/mckernel/executer/user/arch/x86_64'
gcc -shared -fPIC -Wl,-soname,sched_yield.so.1 -o libsched_yield.so.1.0.0 /work/mcktest/git/mckernel/executer/user/libsched_yield.c -lc -ldl
make[1]: Leaving directory `/tmp/build/mckernel/executer/user'
make[1]: Entering directory `/tmp/build/mckernel/kernel'
make[1]: Circular /tmp/build/mckernel/kernel/build/smp-x86/kernel.img <- /tmp/build/mckernel/kernel/build/smp-x86/kernel.img dependency dropped.
Building for /tmp/build/mckernel/kernel/build/smp-x86/
 (smp-x86) DEPEND
 (smp-x86) BUILD IHK smp-x86
 (smp-x86) BUILD IHK smp-x86
 (smp-x86) DEPEND [IHK]
 (smp-x86) BUILD IKC [IHK] smp-x86
 (smp-x86) DEPEND [IKC]
rm /tmp/build/mckernel/kernel/build/smp-x86/Makefile
make[1]: Leaving directory `/tmp/build/mckernel/kernel'
make[1]: Entering directory `/tmp/build/mckernel/tools/mcstat'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/tmp/build/mckernel/tools/mcstat'
make: Target `all' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1