Update patch set 3
Patch Set 3:

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  5%] Built target ihkconfig
[  6%] Built target ihkmond
[  7%] Built target ihkosctl
[  8%] Generating kmod_always_rebuild
[  9%] Building kmod ihk-smp-arm64
[ 10%] Built target ihk-smp-arm64_ko
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod mcctrl
[ 13%] Built target mcctrl_ko
[ 15%] Built target eclair
[ 16%] Built target ldump2mcdump
[ 17%] Built target libmcexec
[ 18%] Built target mcexec
[ 19%] Building C object executer/user/CMakeFiles/mcinspect.dir/mcinspect.c.o
/work/mcktest/git/mckernel/executer/user/mcinspect.c:21:19: fatal error: dwarf.h: No such file or directory
 #include <dwarf.h>
                   ^
compilation terminated.
make[2]: *** [executer/user/CMakeFiles/mcinspect.dir/mcinspect.c.o] Error 1
make[2]: Target `executer/user/CMakeFiles/mcinspect.dir/build' not remade because of errors.
make[1]: *** [executer/user/CMakeFiles/mcinspect.dir/all] Error 2
[ 20%] Built target sched_yield
[ 21%] Building C object kernel/CMakeFiles/mckernel.img.dir/syscall.c.o
/work/mcktest/git/mckernel/kernel/syscall.c: In function ‘do_fork’:
/work/mcktest/git/mckernel/kernel/syscall.c:2867:3: error: implicit declaration of function ‘ihk_rwspinlock_read_lock_noirq’ [-Werror=implicit-function-declaration]
   ihk_rwspinlock_read_lock_noirq(&old->vm->memory_range_lock);
   ^
/work/mcktest/git/mckernel/kernel/syscall.c:2871:3: error: implicit declaration of function ‘ihk_rwspinlock_read_unlock_noirq’ [-Werror=implicit-function-declaration]
   ihk_rwspinlock_read_unlock_noirq(&old->vm->memory_range_lock);
   ^
/work/mcktest/git/mckernel/kernel/syscall.c:2865:17: error: unused variable ‘irqflags’ [-Werror=unused-variable]
   unsigned long irqflags;
                 ^
/work/mcktest/git/mckernel/kernel/syscall.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/syscall.c.o] Error 1
[ 22%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/syscall.c.o
/work/mcktest/git/mckernel/arch/arm64/kernel/syscall.c: In function ‘obtain_clone_cpuid’:
/work/mcktest/git/mckernel/arch/arm64/kernel/syscall.c:61:25: error: unused variable ‘uti_cpu’ [-Werror=unused-variable]
  int cpu, min_cpu = -1, uti_cpu = -1;
                         ^
/work/mcktest/git/mckernel/arch/arm64/kernel/syscall.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/__/arch/arm64/kernel/syscall.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 23%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 3
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>