Update patch set 9
Patch Set 9: Test-x86-1

MCKERNEL : mckernel-refs-changes-24-495524-9-?
IHK      : ihk-refs-changes-24-495524-9-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/495524/9 // bcf51ab06f778d7f4a3df3dca59500b44077764a
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_refs-changes-24-495524-9_submodule
START : 20200614095040
END   : 20200614095056

+++ dirname /work/mcktest/bin/autobuild.sh
++ cd /work/mcktest/bin/..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ pwd
+ CWD=/
++ dirname /work/mcktest/bin/autobuild.sh
+ cd /work/mcktest/bin
+ . ./config.sh
++ export NODETYPE=wallaby
++ NODETYPE=wallaby
++ export WGETSSHPROXY=ofp05
++ WGETSSHPROXY=ofp05
++ export 'WGETPROXYOPTS=-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ WGETPROXYOPTS='-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ MCKERNELBRANCH=refs-changes-24-495524-9
++ IHKBRANCH=submodule
++ REFBRANCH=development
++ export WORKDIR=/work/mcktest/work_refs-changes-24-495524-9_submodule
++ WORKDIR=/work/mcktest/work_refs-changes-24-495524-9_submodule
++ SRC=/work/mcktest/work_refs-changes-24-495524-9_submodule/src
++ MCKBUILD=/work/mcktest/work_refs-changes-24-495524-9_submodule/build
++ MCKINSTALL=/work/mcktest/work_refs-changes-24-495524-9_submodule/mck
++ BUILDID_DIR=/work/mcktest/buildids
++ GITS=/work/mcktest/git
++ LTPINSTALL=/work/mcktest/ltp/install
++ STRESS_TEST_DIR=/work/mcktest/stress_test/install
++ MCKBUILDSCRIPT=/work/mcktest/bin/config_and_build_smp_x86.sh
++ MPICH=/usr/lib64/mpich-3.2
++ export LTPDIR=/work/mcktest/ltp/install
++ LTPDIR=/work/mcktest/ltp/install
++ export LTPROOT=/work/mcktest/ltp/install
++ LTPROOT=/work/mcktest/ltp/install
++ export 'MAIL_TO=mckernel@www.pccluster.org toshi@metahack.jp'
++ MAIL_TO='mckernel@www.pccluster.org toshi@metahack.jp'
++ export 'MCKERNELCONFIGOPTION=--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ MCKERNELCONFIGOPTION='--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ export IHKCONFIGOPTION=--enable-rusage
++ IHKCONFIGOPTION=--enable-rusage
++ MCREBOOTOPTION='-k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O'
++ export PATH=/work/mcktest/bin:/work/mcktest/work_refs-changes-24-495524-9_submodule/mck/bin:/work/mcktest/work_refs-changes-24-495524-9_submodule/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin
++ PATH=/work/mcktest/bin:/work/mcktest/work_refs-changes-24-495524-9_submodule/mck/bin:/work/mcktest/work_refs-changes-24-495524-9_submodule/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin
++ export DATADIR=/work/mcktest/data
++ DATADIR=/work/mcktest/data
++ export BINDIR=/work/mcktest/bin
++ BINDIR=/work/mcktest/bin
++ export LOGDIR=/work/mcktest/log
++ LOGDIR=/work/mcktest/log
++ STRESS_TEST_TIMEOUT=60
++ export OMP_NUM_THREADS_1=1
++ OMP_NUM_THREADS_1=1
++ export OMP_NUM_THREADS_2=2
++ OMP_NUM_THREADS_2=2
++ export OMP_NUM_THREADS_4=4
++ OMP_NUM_THREADS_4=4
++ export OMP_NUM_THREADS_8=8
++ OMP_NUM_THREADS_8=8
++ export OMP_NUM_THREADS_16=16
++ OMP_NUM_THREADS_16=16
++ export OMP_NUM_THREADS_24=24
++ OMP_NUM_THREADS_24=24
++ export OMP_NUM_THREADS_32=32
++ OMP_NUM_THREADS_32=32
++ export 'MPI_HOSTS=wallaby7 wallaby13'
++ MPI_HOSTS='wallaby7 wallaby13'
++ export ORG_HOSTNAME=wallaby14
++ ORG_HOSTNAME=wallaby14
++ [[ -e /work/mcktest/bin/gerrit-creds ]]
++ . /work/mcktest/bin/gerrit-creds
+++ GERRITUSER=riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg
++ export GERRITSERVER=review.gerrithub.io
++ GERRITSERVER=review.gerrithub.io
++ export 'GERRITCURL=curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ GERRITCURL='curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ export GERRIT_USER=riken-syssoft-gerrit
++ GERRIT_USER=riken-syssoft-gerrit
++ export GERRIT_SERVER=review.gerrithub.io
++ GERRIT_SERVER=review.gerrithub.io
++ export 'GITSUDO=sudo -u mcktest'
++ GITSUDO='sudo -u mcktest'
++ export 'SSH_GERRIT=ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io'
++ SSH_GERRIT='ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io'
++ export GIT=/work/mcktest/tools/bin/git
++ GIT=/work/mcktest/tools/bin/git
+ export BINDIR=
+ BINDIR=
+ ./wget-postpeta.sh mckernel refs-changes-24-495524-9
++ pwd
+ CWD=/work/mcktest/bin
+++ dirname ./wget-postpeta.sh
++ cd ./..
++ pwd -P
+ export AUTOTEST_HOME=/work/mcktest
+ AUTOTEST_HOME=/work/mcktest
++ dirname ./wget-postpeta.sh
+ cd .
+ . ./config.sh
++ export NODETYPE=wallaby
++ NODETYPE=wallaby
++ export WGETSSHPROXY=ofp05
++ WGETSSHPROXY=ofp05
++ export 'WGETPROXYOPTS=-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ WGETPROXYOPTS='-e use_proxy=yes -e http_proxy=wallaby -e https_proxy=wallaby:80'
++ MCKERNELBRANCH=refs-changes-24-495524-9
++ IHKBRANCH=submodule
++ REFBRANCH=development
++ export WORKDIR=/work/mcktest/work_refs-changes-24-495524-9_submodule
++ WORKDIR=/work/mcktest/work_refs-changes-24-495524-9_submodule
++ SRC=/work/mcktest/work_refs-changes-24-495524-9_submodule/src
++ MCKBUILD=/work/mcktest/work_refs-changes-24-495524-9_submodule/build
++ MCKINSTALL=/work/mcktest/work_refs-changes-24-495524-9_submodule/mck
++ BUILDID_DIR=/work/mcktest/buildids
++ GITS=/work/mcktest/git
++ LTPINSTALL=/work/mcktest/ltp/install
++ STRESS_TEST_DIR=/work/mcktest/stress_test/install
++ MCKBUILDSCRIPT=/work/mcktest/bin/config_and_build_smp_x86.sh
++ MPICH=/usr/lib64/mpich-3.2
++ export LTPDIR=/work/mcktest/ltp/install
++ LTPDIR=/work/mcktest/ltp/install
++ export LTPROOT=/work/mcktest/ltp/install
++ LTPROOT=/work/mcktest/ltp/install
++ export 'MAIL_TO=mckernel@www.pccluster.org toshi@metahack.jp'
++ MAIL_TO='mckernel@www.pccluster.org toshi@metahack.jp'
++ export 'MCKERNELCONFIGOPTION=--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ MCKERNELCONFIGOPTION='--enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi'
++ export IHKCONFIGOPTION=--enable-rusage
++ IHKCONFIGOPTION=--enable-rusage
++ MCREBOOTOPTION='-k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O'
++ export PATH=/work/mcktest/bin:/work/mcktest/work_refs-changes-24-495524-9_submodule/mck/bin:/work/mcktest/work_refs-changes-24-495524-9_submodule/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin
++ PATH=/work/mcktest/bin:/work/mcktest/work_refs-changes-24-495524-9_submodule/mck/bin:/work/mcktest/work_refs-changes-24-495524-9_submodule/mck/sbin:/usr/lib64/mpich-3.2/bin:/usr/bin:/bin:/usr/sbin:/sbin
++ export DATADIR=/work/mcktest/data
++ DATADIR=/work/mcktest/data
++ export BINDIR=/work/mcktest/bin
++ BINDIR=/work/mcktest/bin
++ export LOGDIR=/work/mcktest/log
++ LOGDIR=/work/mcktest/log
++ STRESS_TEST_TIMEOUT=60
++ export OMP_NUM_THREADS_1=1
++ OMP_NUM_THREADS_1=1
++ export OMP_NUM_THREADS_2=2
++ OMP_NUM_THREADS_2=2
++ export OMP_NUM_THREADS_4=4
++ OMP_NUM_THREADS_4=4
++ export OMP_NUM_THREADS_8=8
++ OMP_NUM_THREADS_8=8
++ export OMP_NUM_THREADS_16=16
++ OMP_NUM_THREADS_16=16
++ export OMP_NUM_THREADS_24=24
++ OMP_NUM_THREADS_24=24
++ export OMP_NUM_THREADS_32=32
++ OMP_NUM_THREADS_32=32
++ export 'MPI_HOSTS=wallaby7 wallaby13'
++ MPI_HOSTS='wallaby7 wallaby13'
++ export ORG_HOSTNAME=wallaby14
++ ORG_HOSTNAME=wallaby14
++ [[ -e /work/mcktest/bin/gerrit-creds ]]
++ . /work/mcktest/bin/gerrit-creds
+++ GERRITUSER=riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg
++ export GERRITSERVER=review.gerrithub.io
++ GERRITSERVER=review.gerrithub.io
++ export 'GERRITCURL=curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ GERRITCURL='curl -s --proxy http://wallaby:80 https://riken-syssoft-gerrit:ogzuCUSBrLM5gpUoECTKZya52oWf7Bu0fvO+oEeFNg@review.gerrithub.io'
++ export GERRIT_USER=riken-syssoft-gerrit
++ GERRIT_USER=riken-syssoft-gerrit
++ export GERRIT_SERVER=review.gerrithub.io
++ GERRIT_SERVER=review.gerrithub.io
++ export 'GITSUDO=sudo -u mcktest'
++ GITSUDO='sudo -u mcktest'
++ export 'SSH_GERRIT=ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io'
++ SSH_GERRIT='ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io'
++ export GIT=/work/mcktest/tools/bin/git
++ GIT=/work/mcktest/tools/bin/git
+ forwatchgerrit=0
+ REPO=mckernel
+ BRANCH=refs-changes-24-495524-9
+ case "$BRANCH" in
+ remote_type=gerrit-git
+ PATHSPEC=refs/changes/24/495524/9
+ '[' /work/mcktest/work_refs-changes-24-495524-9_submodule/src == '' ']'
+ '[' mckernel == '' ']'
+ DEST=mckernel
+ [[ -d /work/mcktest/work_refs-changes-24-495524-9_submodule/src ]]
+ mkdir /work/mcktest/work_refs-changes-24-495524-9_submodule/src
+ rm -rf '/work/mcktest/work_refs-changes-24-495524-9_submodule/src/mckernel-*'
+ case $NODETYPE in
+ case $remote_type in
+ pushd /work/mcktest/git
/work/mcktest/git /work/mcktest/bin
+ sudo -u mcktest rm -rf mckernel
+ sudo -u mcktest git clone ssh://riken-syssoft-gerrit@review.gerrithub.io/RIKEN-SysSoft/mckernel
Cloning into 'mckernel'...
Total 31547 (delta 20433), reused 31164 (delta 20433)
+ cd mckernel
+ sudo -u mcktest git fetch origin refs/changes/24/495524/9
Total 208 (delta 119), reused 193 (delta 119)
From ssh://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/24/495524/9 -> FETCH_HEAD
++ sudo -u mcktest git rev-parse FETCH_HEAD
+ COMMIT=bcf51ab06f778d7f4a3df3dca59500b44077764a
+ DEST=mckernel-refs-changes-24-495524-9-bcf51ab06f778d7f4a3df3dca59500b44077764a
+ popd
/work/mcktest/bin
+ '[' 0 -ne 0 ']'
+ '[' 0 -eq 1 ']'
+ case $remote_type in
+ mkdir /work/mcktest/work_refs-changes-24-495524-9_submodule/src/mckernel-refs-changes-24-495524-9-bcf51ab06f778d7f4a3df3dca59500b44077764a
+ cd /work/mcktest/work_refs-changes-24-495524-9_submodule/src/mckernel-refs-changes-24-495524-9-bcf51ab06f778d7f4a3df3dca59500b44077764a
+ GIT_DIR=/work/mcktest/git/mckernel/.git
+ git reset --hard bcf51ab06f778d7f4a3df3dca59500b44077764a
HEAD is now at bcf51ab eclair-dump-backtrace: expect script to dump backtrace on all CPUs
+ cd /work/mcktest/bin
+ exit 0
+ [[ submodule == \s\u\b\m\o\d\u\l\e ]]
+ read subref _
++ cd /work/mcktest/git/mckernel
++ /work/mcktest/tools/bin/git submodule status
fatal: no submodule mapping found in .gitmodules for path 'executer/user/lib/libdwarf/libdwarf'
+ SUBMODULE_HASH=
++ ssh -i /work/mcktest/bin/id_rsa_gerrit -l riken-syssoft-gerrit review.gerrithub.io 'gerrit query --format=TEXT --current-patch-set --commit-message commit:'
++ awk '/ref:/ { print $2 }'
+ SUBMODULE_PATHSPEC=
+ [[ '' != '' ]]
+ IHKBRANCH=
+ echo 'ihk: submodule commit resolved to '
ihk: submodule commit resolved to 
+ [[ -n '' ]]
+ error 'submodule not found'
+ echo 'ERROR: submodule not found'
ERROR: submodule not found
+ cd /
+ exit -1

Patch-set: 9
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Test-x86=-1