Update patch set 2
Patch Set 2: Build-arm64-1

apollo15: build report: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  5%] Built target ihkconfig
[  6%] Built target ihkmond
[  7%] Built target ihkosctl
[  8%] Generating kmod_always_rebuild
[  9%] Building kmod ihk-smp-arm64
[ 10%] Built target ihk-smp-arm64_ko
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod mcctrl
[ 13%] Built target mcctrl_ko
[ 15%] Built target eclair
[ 16%] Built target ldump2mcdump
[ 17%] Built target libmcexec
[ 18%] Built target mcexec
[ 19%] Built target mcinspect
[ 20%] Built target sched_yield
Linking C executable mckernel.img
CMakeFiles/mckernel.img.dir/syscall.c.o: In function `do_mmap':
/tmp/mckernel/kernel/syscall.c:2164: undefined reference to `zero_at_free'
/tmp/mckernel/kernel/syscall.c:2164:(.text+0xad88): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against undefined symbol `zero_at_free'
/tmp/mckernel/kernel/syscall.c:2164: undefined reference to `zero_at_free'
make[2]: *** [kernel/mckernel.img] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 21%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1