Update patch set 6
Patch Set 6: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 15%] Generating kmod_always_rebuild
[ 16%] Building kmod mcctrl
[ 18%] Built target mcctrl_ko
[ 20%] Built target eclair
[ 22%] Built target ldump2mcdump
[ 23%] Built target libmcexec
[ 25%] Built target mcexec
[ 26%] Built target sched_yield
Linking C executable mckernel.img
CMakeFiles/mckernel.img.dir/syscall.c.o:(.rodata+0x1948): undefined reference to `sys_pmc_init'
CMakeFiles/mckernel.img.dir/syscall.c.o:(.rodata+0x1950): undefined reference to `sys_pmc_start'
CMakeFiles/mckernel.img.dir/syscall.c.o:(.rodata+0x1958): undefined reference to `sys_pmc_stop'
CMakeFiles/mckernel.img.dir/syscall.c.o:(.rodata+0x1960): undefined reference to `sys_pmc_reset'
make[2]: *** [kernel/mckernel.img] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 27%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 6
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1