Update patch set 1
Patch Set 1:

ARM MCKERNEL : mckernel-refs-changes-02-427602-1-?
IHK      : ihk-refs-changes-02-427602-1-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/427602/1 // cad305d893fafcf5594aef2925723756c92f1027
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6 -m 58G@0,58G@1 -c 4-27,32-55 -r 4-9:0+10-15:1+16-21:2+22-27:3+32-37:28+38-43:29+44-49:30+50-55:31 -O
HOST  : apollo15.postk.local.r-ccs.riken.jp
DIR   : /work/mcktest/work_refs-changes-02-427602-1_submodule
START : 20200422132023
END   : 20200422132035

/work/mcktest/git /work/mcktest/bin
Cloning into 'mckernel'...
Total 31452 (delta 20385), reused 31083 (delta 20385)
Total 8 (delta 3), reused 5 (delta 3)
From ssh://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/02/427602/1 -> FETCH_HEAD
/work/mcktest/bin
HEAD is now at cad305d8 procfs: add missing information in /proc/stat
ihk: submodule commit resolved to 
ERROR: submodule not found

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>