Update patch set 2
Patch Set 2: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  7%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 14%] Built target ihk-smp-x86_64_ko
[ 15%] Generating kmod_always_rebuild
[ 16%] Building kmod mcctrl
[ 18%] Built target mcctrl_ko
[ 21%] Built target eclair
[ 22%] Built target ldump2mcdump
[ 23%] Built target libmcexec
[ 25%] Building C object executer/user/CMakeFiles/mcexec.dir/mcexec.c.o
/work/mcktest/git/mckernel/executer/user/mcexec.c: In function ‘find_libdir’:
/work/mcktest/git/mckernel/executer/user/mcexec.c:2002:3: error: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘ssize_t’ [-Werror=format=]
   fprintf(stderr, "could not open /proc/self/maps: %d\n", -rc);
   ^
/work/mcktest/git/mckernel/executer/user/mcexec.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [executer/user/CMakeFiles/mcexec.dir/mcexec.c.o] Error 1
make[2]: Target `executer/user/CMakeFiles/mcexec.dir/build' not remade because of errors.
make[1]: *** [executer/user/CMakeFiles/mcexec.dir/all] Error 2
[ 26%] Built target sched_yield
[ 98%] Built target mckernel.img
[100%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1