Update patch set 13
Patch Set 13:

wallaby7: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 10%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 15%] Generating kmod_always_rebuild
[ 16%] Building kmod mcctrl
WARNING: "mcctrl_tofu_hijack_release_handlers" [/tmp/build-mckernel/executer/kernel/mcctrl/mcctrl.ko] undefined!
WARNING: "mcctrl_tofu_restore_release_handlers" [/tmp/build-mckernel/executer/kernel/mcctrl/mcctrl.ko] undefined!
[ 17%] Built target mcctrl_ko
[ 20%] Built target eclair
[ 21%] Built target ldump2mcdump
[ 23%] Built target libmcexec
[ 24%] Built target mcexec
[ 26%] Built target mcinspect
[ 27%] Built target sched_yield
Linking C executable mckernel.img
CMakeFiles/mckernel.img.dir/syscall.c.o: In function `__process_cleanup_fd':
/work/mcktest/git/mckernel/kernel/syscall.c:1502: undefined reference to `tof_utofu_release_fd'
make[2]: *** [kernel/mckernel.img] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 28%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 13
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>