Update patch set 7
Patch Set 7: Verified-1

wallaby7: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  5%] Built target ihklib
[  8%] Built target ihkmond
[ 10%] Built target ihkconfig
[ 12%] Built target ihkosctl
[ 14%] Generating kmod_always_rebuild
[ 15%] Building kmod ihk-smp-x86_64
[ 16%] Built target ihk-smp-x86_64_ko
[ 17%] Generating kmod_always_rebuild
[ 18%] Building kmod mcctrl
[ 20%] Built target mcctrl_ko
[ 22%] Built target libmcexec
[ 24%] Built target mcexec
[ 27%] Built target mcinspect
[ 29%] Built target sched_yield
[ 31%] Built target ldump2mcdump
[ 35%] Built target eclair
[ 36%] Building C object kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o
/work/mcktest/git/mckernel/kernel/xpmem.c: In function ‘_xpmem_fault_process_memory_range’:
/work/mcktest/git/mckernel/kernel/xpmem.c:1790:2: error: ‘at_lock’ undeclared (first use in this function)
  at_lock = ihk_rwspinlock_write_lock(&att->at_lock);
  ^
/work/mcktest/git/mckernel/kernel/xpmem.c:1790:2: note: each undeclared identifier is reported only once for each function it appears in
/work/mcktest/git/mckernel/kernel/xpmem.c:1791:2: error: ‘att_locked’ undeclared (first use in this function)
  att_locked = 1;
  ^
/work/mcktest/git/mckernel/kernel/xpmem.c: At top level:
cc1: error: unrecognized command line option "-Wno-stringop-truncation" [-Werror]
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 38%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 7
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1