Update patch set 10
Patch Set 10: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 15%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/x86_64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/x86_64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 16%] Building kmod mcctrl
In file included from /work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:47:0:
/work/mcktest/git/mckernel/kernel/include/rusage.h:12:19: error: redefinition of ‘rusage_pgsize_to_pgshift’
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:6:0,
                 from /work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:47:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: note: previous definition of ‘rusage_pgsize_to_pgshift’ was here
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/control.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 19%] Built target eclair
[ 20%] Built target ldump2mcdump
[ 22%] Built target libmcexec
[ 23%] Built target mcexec
[ 25%] Built target sched_yield
[ 26%] Building C object kernel/CMakeFiles/mckernel.img.dir/init.c.o
In file included from /work/mcktest/git/mckernel/kernel/init.c:35:0:
/work/mcktest/git/mckernel/kernel/include/rusage.h:12:19: error: redefinition of ‘rusage_pgsize_to_pgshift’
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:6:0,
                 from /work/mcktest/git/mckernel/kernel/init.c:35:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: note: previous definition of ‘rusage_pgsize_to_pgshift’ was here
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/init.c.o] Error 1
[ 27%] Building C object kernel/CMakeFiles/mckernel.img.dir/mem.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10:0,
                 from /work/mcktest/git/mckernel/kernel/mem.c:40:
/work/mcktest/git/mckernel/kernel/include/rusage.h:12:19: error: redefinition of ‘rusage_pgsize_to_pgshift’
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:6:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/mem.c:40:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: note: previous definition of ‘rusage_pgsize_to_pgshift’ was here
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/mem.c.o] Error 1
[ 29%] Building C object kernel/CMakeFiles/mckernel.img.dir/ap.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10:0,
                 from /work/mcktest/git/mckernel/kernel/ap.c:30:
/work/mcktest/git/mckernel/kernel/include/rusage.h:12:19: error: redefinition of ‘rusage_pgsize_to_pgshift’
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:6:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/ap.c:30:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: note: previous definition of ‘rusage_pgsize_to_pgshift’ was here
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/ap.c.o] Error 1
[ 30%] Building C object kernel/CMakeFiles/mckernel.img.dir/syscall.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10:0,
                 from /work/mcktest/git/mckernel/kernel/syscall.c:58:
/work/mcktest/git/mckernel/kernel/include/rusage.h:12:19: error: redefinition of ‘rusage_pgsize_to_pgshift’
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:6:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/syscall.c:58:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: note: previous definition of ‘rusage_pgsize_to_pgshift’ was here
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/syscall.c.o] Error 1
[ 31%] Building C object kernel/CMakeFiles/mckernel.img.dir/cls.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10:0,
                 from /work/mcktest/git/mckernel/kernel/cls.c:22:
/work/mcktest/git/mckernel/kernel/include/rusage.h:12:19: error: redefinition of ‘rusage_pgsize_to_pgshift’
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:6:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/cls.c:22:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: note: previous definition of ‘rusage_pgsize_to_pgshift’ was here
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/cls.c.o] Error 1
[ 33%] Building C object kernel/CMakeFiles/mckernel.img.dir/host.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10:0,
                 from /work/mcktest/git/mckernel/kernel/host.c:35:
/work/mcktest/git/mckernel/kernel/include/rusage.h:12:19: error: redefinition of ‘rusage_pgsize_to_pgshift’
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:6:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/host.c:35:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: note: previous definition of ‘rusage_pgsize_to_pgshift’ was here
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/host.c.o] Error 1
[ 34%] Building C object kernel/CMakeFiles/mckernel.img.dir/process.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10:0,
                 from /work/mcktest/git/mckernel/kernel/process.c:36:
/work/mcktest/git/mckernel/kernel/include/rusage.h:12:19: error: redefinition of ‘rusage_pgsize_to_pgshift’
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:6:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/process.c:36:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: note: previous definition of ‘rusage_pgsize_to_pgshift’ was here
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/process.c.o] Error 1
[ 36%] Building C object kernel/CMakeFiles/mckernel.img.dir/fileobj.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10:0,
                 from /work/mcktest/git/mckernel/kernel/fileobj.c:28:
/work/mcktest/git/mckernel/kernel/include/rusage.h:12:19: error: redefinition of ‘rusage_pgsize_to_pgshift’
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:6:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/fileobj.c:28:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: note: previous definition of ‘rusage_pgsize_to_pgshift’ was here
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/fileobj.c.o] Error 1
[ 37%] Building C object kernel/CMakeFiles/mckernel.img.dir/shmobj.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10:0,
                 from /work/mcktest/git/mckernel/kernel/shmobj.c:24:
/work/mcktest/git/mckernel/kernel/include/rusage.h:12:19: error: redefinition of ‘rusage_pgsize_to_pgshift’
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:6:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/shmobj.c:24:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: note: previous definition of ‘rusage_pgsize_to_pgshift’ was here
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/shmobj.c.o] Error 1
[ 38%] Building C object kernel/CMakeFiles/mckernel.img.dir/devobj.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10:0,
                 from /work/mcktest/git/mckernel/kernel/devobj.c:22:
/work/mcktest/git/mckernel/kernel/include/rusage.h:12:19: error: redefinition of ‘rusage_pgsize_to_pgshift’
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:6:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/devobj.c:22:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: note: previous definition of ‘rusage_pgsize_to_pgshift’ was here
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/devobj.c.o] Error 1
[ 40%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/memory.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10:0,
                 from /work/mcktest/git/mckernel/arch/x86_64/kernel/memory.c:27:
/work/mcktest/git/mckernel/kernel/include/rusage.h:12:19: error: redefinition of ‘rusage_pgsize_to_pgshift’
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:6:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/arch/x86_64/kernel/memory.c:27:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: note: previous definition of ‘rusage_pgsize_to_pgshift’ was here
 static inline int rusage_pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/memory.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 41%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 10
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1