Update patch set 2
Patch Set 2: Verified-1

wallaby7: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  5%] Built target ihklib
[  8%] Built target ihkmond
[ 10%] Built target ihkconfig
[ 12%] Built target ihkosctl
[ 14%] Generating kmod_always_rebuild
[ 15%] Building kmod ihk-smp-x86_64
[ 16%] Built target ihk-smp-x86_64_ko
[ 17%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, mc_plist.o, futex.o, arch/x86_64/archdeps.o, arch/x86_64/cpu.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, .mc_plist.o.cmd, .futex.o.cmd, arch/x86_64/.archdeps.o.cmd, arch/x86_64/.cpu.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 18%] Building kmod mcctrl
In file included from /work/mcktest/git/mckernel/executer/kernel/mcctrl/ikc.c:31:0:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/mcctrl.h:47:5: error: "KERNEL_VERSION" is not defined [-Werror=undef]
 #if KERNEL_VERSION(4, 11, 0) > LINUX_VERSION_CODE
     ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/mcctrl.h:47:19: error: missing binary operator before token "("
 #if KERNEL_VERSION(4, 11, 0) > LINUX_VERSION_CODE
                   ^
In file included from /work/mcktest/git/mckernel/executer/kernel/mcctrl/ikc.c:31:0:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/mcctrl.h:407:2: error: unknown type name ‘refcount_t’
  refcount_t count;
  ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/ikc.c: In function ‘mcctrl_wakeup_desc_put’:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/ikc.c:67:2: error: implicit declaration of function ‘refcount_dec_and_test’ [-Werror=implicit-function-declaration]
  if (!refcount_dec_and_test(&desc->count)) {
  ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/ikc.c: In function ‘mcctrl_ikc_send_wait’:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/ikc.c:169:2: error: implicit declaration of function ‘refcount_set’ [-Werror=implicit-function-declaration]
  refcount_set(&desc->count, 2);
  ^
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/ikc.o] Error 1
In file included from /work/mcktest/git/mckernel/executer/kernel/mcctrl/syscall.c:55:0:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/mcctrl.h:47:5: error: "KERNEL_VERSION" is not defined [-Werror=undef]
 #if KERNEL_VERSION(4, 11, 0) > LINUX_VERSION_CODE
     ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/mcctrl.h:47:19: error: missing binary operator before token "("
 #if KERNEL_VERSION(4, 11, 0) > LINUX_VERSION_CODE
                   ^
In file included from /work/mcktest/git/mckernel/executer/kernel/mcctrl/syscall.c:55:0:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/mcctrl.h:407:2: error: unknown type name ‘refcount_t’
  refcount_t count;
  ^
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/syscall.o] Error 1
In file included from /work/mcktest/git/mckernel/executer/kernel/mcctrl/procfs.c:23:0:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/mcctrl.h:47:5: error: "KERNEL_VERSION" is not defined [-Werror=undef]
 #if KERNEL_VERSION(4, 11, 0) > LINUX_VERSION_CODE
     ^
/work/mcktest/git/mckernel/executer/kernel/mcctrl/mcctrl.h:47:19: error: missing binary operator before token "("
 #if KERNEL_VERSION(4, 11, 0) > LINUX_VERSION_CODE
                   ^
In file included from /work/mcktest/git/mckernel/executer/kernel/mcctrl/procfs.c:23:0:
/work/mcktest/git/mckernel/executer/kernel/mcctrl/mcctrl.h:407:2: error: unknown type name ‘refcount_t’
  refcount_t count;
  ^
cc1: all warnings being treated as errors
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/procfs.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 21%] Built target libmcexec
[ 23%] Built target mcexec
[ 25%] Built target mcinspect
[ 28%] Built target sched_yield
[ 30%] Built target ldump2mcdump
[ 34%] Built target eclair
[ 96%] Built target mckernel.img
[ 98%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 2
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1