Update patch set 1
Patch Set 1: Verified-1

build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  4%] Built target ihk_ko
[  5%] Built target ihklib
[  6%] Built target ihkconfig
[  8%] Built target ihkmond
[  9%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-x86_64
[ 13%] Built target ihk-smp-x86_64_ko
[ 15%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/x86_64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/x86_64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 16%] Building kmod mcctrl
In file included from /work/mcktest/git/mckernel/executer/kernel/mcctrl/control.c:47:0:
/work/mcktest/git/mckernel/kernel/include/rusage.h:6:20: fatal error: memory.h: No such file or directory
 #include <memory.h>
                    ^
compilation terminated.
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/control.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 19%] Built target eclair
[ 20%] Built target ldump2mcdump
[ 22%] Built target libmcexec
[ 23%] Building C object executer/user/CMakeFiles/mcexec.dir/mcexec.c.o
/work/mcktest/git/mckernel/executer/user/mcexec.c: In function ‘main’:
/work/mcktest/git/mckernel/executer/user/mcexec.c:2657:6: error: ‘struct program_load_desc’ has no member named ‘heap_pgsize’
  desc->heap_pgsize = heap_pgsize;
      ^
/work/mcktest/git/mckernel/executer/user/mcexec.c:2658:6: error: ‘struct program_load_desc’ has no member named ‘stack_pgsize’
  desc->stack_pgsize = stack_pgsize;
      ^
/work/mcktest/git/mckernel/executer/user/mcexec.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [executer/user/CMakeFiles/mcexec.dir/mcexec.c.o] Error 1
make[2]: Target `executer/user/CMakeFiles/mcexec.dir/build' not remade because of errors.
make[1]: *** [executer/user/CMakeFiles/mcexec.dir/all] Error 2
[ 25%] Built target sched_yield
[ 26%] Building C object kernel/CMakeFiles/mckernel.img.dir/init.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:7:0,
                 from /work/mcktest/git/mckernel/kernel/init.c:35:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: error: redefinition of ‘pgsize_to_pgshift’
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/lib/include/memory.h:17:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:18,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/init.c:23:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:369:19: note: previous definition of ‘pgsize_to_pgshift’ was here
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/init.c.o] Error 1
[ 27%] Building C object kernel/CMakeFiles/mckernel.img.dir/mem.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:7:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/mem.c:40:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: error: redefinition of ‘pgsize_to_pgshift’
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/lib/include/memory.h:17:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:18,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/mem.c:23:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:369:19: note: previous definition of ‘pgsize_to_pgshift’ was here
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/mem.c.o] Error 1
[ 29%] Building C object kernel/CMakeFiles/mckernel.img.dir/ap.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:7:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/ap.c:30:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: error: redefinition of ‘pgsize_to_pgshift’
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/lib/include/memory.h:17:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:18,
                 from /work/mcktest/git/mckernel/kernel/ap.c:23:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:369:19: note: previous definition of ‘pgsize_to_pgshift’ was here
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/ap.c.o] Error 1
[ 30%] Building C object kernel/CMakeFiles/mckernel.img.dir/syscall.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:7:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/syscall.c:58:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: error: redefinition of ‘pgsize_to_pgshift’
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/lib/include/memory.h:17:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:18,
                 from /work/mcktest/git/mckernel/kernel/syscall.c:30:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:369:19: note: previous definition of ‘pgsize_to_pgshift’ was here
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/syscall.c.o] Error 1
[ 31%] Building C object kernel/CMakeFiles/mckernel.img.dir/cls.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:7:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/cls.c:22:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: error: redefinition of ‘pgsize_to_pgshift’
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/lib/include/memory.h:17:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:18,
                 from /work/mcktest/git/mckernel/kernel/cls.c:18:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:369:19: note: previous definition of ‘pgsize_to_pgshift’ was here
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/cls.c.o] Error 1
[ 33%] Building C object kernel/CMakeFiles/mckernel.img.dir/host.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:7:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/host.c:35:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: error: redefinition of ‘pgsize_to_pgshift’
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/lib/include/memory.h:17:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:18,
                 from /work/mcktest/git/mckernel/kernel/host.c:23:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:369:19: note: previous definition of ‘pgsize_to_pgshift’ was here
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
/work/mcktest/git/mckernel/kernel/host.c: In function ‘prepare_process_ranges_args_envs’:
/work/mcktest/git/mckernel/kernel/host.c:246:28: error: ‘struct program_load_desc’ has no member named ‘heap_pgsize’
   (vm->region.data_end + pn->heap_pgsize - 1) &
                            ^
/work/mcktest/git/mckernel/kernel/host.c:247:7: error: ‘struct program_load_desc’ has no member named ‘heap_pgsize’
   ~(pn->heap_pgsize - 1);
       ^
/work/mcktest/git/mckernel/kernel/host.c: In function ‘process_msg_prepare_process’:
/work/mcktest/git/mckernel/kernel/host.c:506:8: error: ‘struct program_load_desc’ has no member named ‘heap_pgsize’
  if (pn->heap_pgsize == -1) {
        ^
/work/mcktest/git/mckernel/kernel/host.c:507:5: error: ‘struct program_load_desc’ has no member named ‘heap_pgsize’
   pn->heap_pgsize =
     ^
/work/mcktest/git/mckernel/kernel/host.c:511:26: error: ‘struct program_load_desc’ has no member named ‘heap_pgsize’
  if (pgsize_to_pgshift(pn->heap_pgsize) == -EINVAL) {
                          ^
/work/mcktest/git/mckernel/kernel/host.c:513:16: error: ‘struct program_load_desc’ has no member named ‘heap_pgsize’
    __func__, pn->heap_pgsize);
                ^
/work/mcktest/git/mckernel/kernel/host.c:518:8: error: ‘struct program_load_desc’ has no member named ‘stack_pgsize’
  if (pn->stack_pgsize == -1) {
        ^
/work/mcktest/git/mckernel/kernel/host.c:519:5: error: ‘struct program_load_desc’ has no member named ‘stack_pgsize’
   pn->stack_pgsize =
     ^
/work/mcktest/git/mckernel/kernel/host.c:523:26: error: ‘struct program_load_desc’ has no member named ‘stack_pgsize’
  if (pgsize_to_pgshift(pn->stack_pgsize) == -EINVAL) {
                          ^
/work/mcktest/git/mckernel/kernel/host.c:525:16: error: ‘struct program_load_desc’ has no member named ‘stack_pgsize’
    __func__, pn->stack_pgsize);
                ^
/work/mcktest/git/mckernel/kernel/host.c:558:6: error: ‘struct process’ has no member named ‘heap_pgsize’
  proc->heap_pgsize = pn->heap_pgsize;
      ^
/work/mcktest/git/mckernel/kernel/host.c:558:24: error: ‘struct program_load_desc’ has no member named ‘heap_pgsize’
  proc->heap_pgsize = pn->heap_pgsize;
                        ^
/work/mcktest/git/mckernel/kernel/host.c:559:6: error: ‘struct process’ has no member named ‘stack_pgsize’
  proc->stack_pgsize = pn->stack_pgsize;
      ^
/work/mcktest/git/mckernel/kernel/host.c:559:25: error: ‘struct program_load_desc’ has no member named ‘stack_pgsize’
  proc->stack_pgsize = pn->stack_pgsize;
                         ^
/work/mcktest/git/mckernel/kernel/host.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/host.c.o] Error 1
[ 34%] Building C object kernel/CMakeFiles/mckernel.img.dir/process.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:7:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/process.c:36:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: error: redefinition of ‘pgsize_to_pgshift’
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/lib/include/memory.h:17:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:18,
                 from /work/mcktest/git/mckernel/kernel/include/process.h:19,
                 from /work/mcktest/git/mckernel/kernel/process.c:24:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:369:19: note: previous definition of ‘pgsize_to_pgshift’ was here
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
/work/mcktest/git/mckernel/kernel/process.c: In function ‘init_process_stack’:
/work/mcktest/git/mckernel/kernel/process.c:2266:27: error: ‘struct program_load_desc’ has no member named ‘stack_pgsize’
  unsigned long pgsize = pn->stack_pgsize;
                           ^
/work/mcktest/git/mckernel/kernel/process.c: In function ‘extend_process_region’:
/work/mcktest/git/mckernel/kernel/process.c:2437:26: error: ‘struct process’ has no member named ‘heap_pgsize’
  size_t pgsize = vm->proc->heap_pgsize;
                          ^
/work/mcktest/git/mckernel/kernel/process.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/process.c.o] Error 1
[ 36%] Building C object kernel/CMakeFiles/mckernel.img.dir/fileobj.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:7:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/fileobj.c:28:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: error: redefinition of ‘pgsize_to_pgshift’
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/lib/include/memory.h:17:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:18,
                 from /work/mcktest/git/mckernel/kernel/fileobj.c:16:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:369:19: note: previous definition of ‘pgsize_to_pgshift’ was here
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/fileobj.c.o] Error 1
[ 37%] Building C object kernel/CMakeFiles/mckernel.img.dir/shmobj.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:7:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/shmobj.c:24:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: error: redefinition of ‘pgsize_to_pgshift’
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/lib/include/memory.h:17:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:18,
                 from /work/mcktest/git/mckernel/kernel/shmobj.c:15:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:369:19: note: previous definition of ‘pgsize_to_pgshift’ was here
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/shmobj.c.o] Error 1
[ 38%] Building C object kernel/CMakeFiles/mckernel.img.dir/devobj.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:7:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/kernel/devobj.c:22:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: error: redefinition of ‘pgsize_to_pgshift’
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/lib/include/memory.h:17:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:18,
                 from /work/mcktest/git/mckernel/kernel/include/kmalloc.h:16,
                 from /work/mcktest/git/mckernel/kernel/devobj.c:15:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:369:19: note: previous definition of ‘pgsize_to_pgshift’ was here
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/devobj.c.o] Error 1
[ 40%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/memory.c.o
In file included from /work/mcktest/git/mckernel/kernel/include/rusage.h:7:0,
                 from /work/mcktest/git/mckernel/kernel/include/rusage_private.h:10,
                 from /work/mcktest/git/mckernel/arch/x86_64/kernel/memory.c:27:
/work/mcktest/git/mckernel/ihk/linux/include/ihk/ihk_rusage.h:70:19: error: redefinition of ‘pgsize_to_pgshift’
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
In file included from /work/mcktest/git/mckernel/lib/include/memory.h:17:0,
                 from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:18,
                 from /work/mcktest/git/mckernel/arch/x86_64/kernel/memory.c:17:
/work/mcktest/git/mckernel/arch/x86_64/kernel/include/arch-memory.h:369:19: note: previous definition of ‘pgsize_to_pgshift’ was here
 static inline int pgsize_to_pgshift(size_t pgsize)
                   ^
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/memory.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 41%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1