Update patch set 5
Patch Set 5: Test-x86-1

MCKERNEL : mckernel-refs-changes-96-460296-5-?
IHK      : ihk-refs-changes-96-460296-5-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/460296/5 // b49f52f86f56338c676638c411ee5a3e0d3dbe5c
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_refs-changes-96-460296-5_submodule
START : 20190723085643
END   : 20190723085651

From https://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/96/460296/5 -> FETCH_HEAD
HEAD is now at b49f52f pmu: change to atomic register access.
HEAD is now at 9a15ade pmu: implement event mapping function.
MCKBUILD=/work/mcktest/work_refs-changes-96-460296-5_submodule/build
MCKINSTALL=/work/mcktest/work_refs-changes-96-460296-5_submodule/mck
-- The C compiler identification is GNU 4.8.5
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Performing Test IMPLICIT_FALLTHROUGH
-- Performing Test IMPLICIT_FALLTHROUGH - Success
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
Defined module ihk
Defined module ihk-smp-x86_64
Defined module mcctrl
-------------------------------
Option summary
-------------------------------
Build type: Debug
Build target: smp-x86
IHK_SOURCE_DIR: ../ihk (relative to mckernel source tree)
UNAME_R: 3.10.0-693.2.2.el7.x86_64
KERNEL_DIR: /lib/modules/3.10.0-693.2.2.el7.x86_64/build
SYSTEM_MAP: 
VMLINUX: 
KBUILD_C_FLAGS:  -DIHK_IKC_USE_LINUX_WORK_IRQ
ENABLE_MEMDUMP: ON
ENABLE_PERF: ON
ENABLE_RUSAGE: ON
ENABLE_QLMPI: OFF
ENABLE_UTI: OFF
ENABLE_WERROR: OFF
ENABLE_UBSAN: OFF
ENABLE_LINUX_WORK_IRQ_FOR_IKC: ON
-------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /work/mcktest/work_refs-changes-96-460296-5_submodule/build/3.10.0-693.2.2.el7.x86_64
Scanning dependencies of target ihk_ko
Scanning dependencies of target libmcexec
Scanning dependencies of target sched_yield
Scanning dependencies of target ihklib
Scanning dependencies of target eclair
Scanning dependencies of target ldump2mcdump
[  4%] [  4%] [  4%] [  5%] [  6%] [  8%] [  9%] [ 11%] Building ASM object executer/user/CMakeFiles/libmcexec.dir/arch/x86_64/archdep.S.o
Generating old_timestamp, host_driver.o, mem_alloc.o, mm.o, mikc.o, ../../ikc/linux.o, ../../ikc/master.o, ../../ikc/queue.o, .host_driver.o.cmd, .mem_alloc.o.cmd, .mm.o.cmd, .mikc.o.cmd, ../../ikc/.linux.o.cmd, ../../ikc/.master.o.cmd, ../../ikc/.queue.o.cmd, ihk.o, .ihk.o.cmd, ihk.mod.c, ihk.mod.o, .ihk.mod.o.cmd, .ihk.ko.cmd, .tmp_versions/ihk.mod, .tmp_versions, modules.order
Building C object executer/user/CMakeFiles/sched_yield.dir/libsched_yield.c.o
Generating kmod_always_rebuild
Building C object ihk/linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
Building C object executer/user/CMakeFiles/eclair.dir/eclair.c.o
Building C object executer/user/CMakeFiles/eclair.dir/arch/x86_64/arch-eclair.c.o
Building C object executer/user/CMakeFiles/ldump2mcdump.dir/ldump2mcdump.c.o
[ 12%] Building kmod ihk
Linking ASM static library libmcexec.a
Linking C shared library libsched_yield.so
[ 12%] Built target libmcexec
[ 12%] Built target sched_yield
Scanning dependencies of target mckernel.img
[ 16%] [ 18%] [ 18%] [ 18%] [ 20%] [ 20%] [ 22%] [ 23%] [ 25%] [ 26%] [ 27%] [ 29%] [ 30%] [ 31%] Building C object kernel/CMakeFiles/mckernel.img.dir/init.c.o
[ 33%] Building C object kernel/CMakeFiles/mckernel.img.dir/mem.c.o
Linking C shared library libldump2mcdump.so
[ 36%] [ 36%] Building C object kernel/CMakeFiles/mckernel.img.dir/host.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/debug.c.o
[ 37%] Building C object kernel/CMakeFiles/mckernel.img.dir/cls.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/listeners.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/syscall.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/mikc.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/ap.c.o
[ 38%] [ 40%] Building C object kernel/CMakeFiles/mckernel.img.dir/process.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/waitq.c.o
[ 41%] [ 43%] Building C object kernel/CMakeFiles/mckernel.img.dir/copy.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/futex.c.o
[ 44%] [ 45%] Building C object kernel/CMakeFiles/mckernel.img.dir/plist.c.o
[ 47%] Building C object kernel/CMakeFiles/mckernel.img.dir/timer.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/fileobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/shmobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/procfs.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/zeroobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/devobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/sysfs.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/profile.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/freeze.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/rbtree.c.o
[ 48%] [ 51%] [ 51%] [ 52%] [ 54%] [ 55%] Linking C executable eclair
Building C object kernel/CMakeFiles/mckernel.img.dir/llist.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/gencore.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-96-460296-5_submodule/src/ihk/ikc/manycore.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/hugefileobj.c.o
[ 56%] [ 58%] Building C object kernel/CMakeFiles/mckernel.img.dir/pager.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-96-460296-5_submodule/src/ihk/ikc/master.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-96-460296-5_submodule/src/ihk/ikc/queue.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/abort.c.o
[ 59%] [ 59%] Built target ldump2mcdump
[ 61%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/bitmap.c.o
[ 62%] [ 63%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/bitops.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/page_alloc.c.o
[ 65%] [ 66%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/string.c.o
[ 66%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/vsprintf.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-96-460296-5_submodule/src/ihk/cokernel/smp/ikc.c.o
[ 68%] Built target eclair
[ 69%] [ 70%] Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-96-460296-5_submodule/src/ihk/cokernel/smp/x86_64/dma.c.o
[ 72%] Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/context.S.o
[ 73%] [ 75%] Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-96-460296-5_submodule/src/ihk/cokernel/smp/x86_64/setup.c.o
[ 76%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/coredump.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/cpu.c.o
Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/interrupt.S.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/local.c.o
[ 77%] [ 79%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/memory.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/mikc.c.o
[ 80%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/perfctr.c.o
[ 81%] [ 83%] [ 84%] Linking C shared library libihk.so
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/syscall.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/vsyscall.c.o
Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/trampoline.S.o
[ 84%] Built target ihklib
Scanning dependencies of target ihkconfig
Scanning dependencies of target ihkosctl
Scanning dependencies of target ihkmond
Scanning dependencies of target mcstat
Scanning dependencies of target mcexec
[ 86%] [ 87%] [ 88%] [ 90%] [ 91%] Building C object ihk/linux/user/CMakeFiles/ihkosctl.dir/ihkosctl.c.o
Building C object ihk/linux/user/CMakeFiles/ihkconfig.dir/ihkconfig.c.o
Building C object tools/mcstat/CMakeFiles/mcstat.dir/mcstat.c.o
Building C object ihk/linux/user/CMakeFiles/ihkmond.dir/ihkmond.c.o
Building C object executer/user/CMakeFiles/mcexec.dir/mcexec.c.o
Linking C executable mcstat
Linking C executable ihkconfig
[ 91%] Built target mcstat
[ 91%] Linking C executable ihkosctl
Built target ihkconfig
Linking C executable ihkmond
[ 91%] Built target ihkosctl
[ 91%] Built target ihkmond
Linking C executable mcexec
[ 91%] Built target mcexec
[ 91%] Built target ihk_ko
Scanning dependencies of target ihk-smp-x86_64_ko
Scanning dependencies of target mcctrl_ko
[ 93%] [ 94%] [ 95%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/x86_64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/x86_64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
Generating kmod_always_rebuild
[ 97%] [ 98%] Generating kmod_always_rebuild
Generating old_timestamp, arch/x86_64/smp-x86_64-startup.o, arch/x86_64/smp-x86_64-trampoline.o, arch/x86_64/smp-arch-driver.o, smp-driver.o, arch/x86_64/.smp-x86_64-startup.o.cmd, arch/x86_64/.smp-x86_64-trampoline.o.cmd, arch/x86_64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-x86_64.o, .ihk-smp-x86_64.o.cmd, ihk-smp-x86_64.mod.c, ihk-smp-x86_64.mod.o, .ihk-smp-x86_64.mod.o.cmd, .ihk-smp-x86_64.ko.cmd, .tmp_versions/ihk-smp-x86_64.mod, .tmp_versions, modules.order
Building kmod mcctrl
[100%] Building kmod ihk-smp-x86_64
/work/mcktest/work_refs-changes-96-460296-5_submodule/build/3.10.0-693.2.2.el7.x86_64/ihk/linux/driver/smp/arch/x86_64/smp-x86_64-startup.o: warning: objtool: .text+0x7: can't find jump dest instruction at .text+0x38
Linking C executable mckernel.img
CMakeFiles/mckernel.img.dir/syscall.c.o:(.rodata+0x1948): undefined reference to `sys_pmc_init'
CMakeFiles/mckernel.img.dir/syscall.c.o:(.rodata+0x1950): undefined reference to `sys_pmc_start'
CMakeFiles/mckernel.img.dir/syscall.c.o:(.rodata+0x1958): undefined reference to `sys_pmc_stop'
CMakeFiles/mckernel.img.dir/syscall.c.o:(.rodata+0x1960): undefined reference to `sys_pmc_reset'
make[2]: *** [kernel/mckernel.img] Error 1
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target mcctrl_ko
[100%] Built target ihk-smp-x86_64_ko
make: *** [all] Error 2
ERROR: autobuild.sh failed

Patch-set: 5
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Test-x86=-1