Update patch set 1
Patch Set 1: Build-arm64-1

apollo15: build report: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  6%] Built target ihkmond
[  8%] Built target ihkconfig
[ 10%] Built target ihkosctl
[ 11%] Generating kmod_always_rebuild
[ 12%] Building kmod ihk-smp-arm64
[ 13%] Built target ihk-smp-arm64_ko
[ 14%] Generating kmod_always_rebuild
[ 15%] Building kmod mcctrl
[ 16%] Built target mcctrl_ko
[ 18%] Built target libmcexec
[ 19%] Built target mcexec
[ 21%] Built target mcinspect
[ 23%] Built target sched_yield
[ 25%] Built target ldump2mcdump
[ 27%] Built target eclair
[ 28%] Building C object kernel/CMakeFiles/mckernel.img.dir/syscall.c.o
/tmp/mckernel/kernel/syscall.c: In function ‘do_mmap’:
/tmp/mckernel/kernel/syscall.c:1946:6: error: too few arguments to function ‘add_process_memory_range’
      PAGE_SHIFT + p2align, &range) != 0) {
      ^
In file included from /tmp/mckernel/arch/arm64/kernel/include/thread_info.h:20:0,
                 from /tmp/mckernel/arch/arm64/kernel/include/cpulocal.h:7,
                 from /tmp/mckernel/kernel/syscall.c:29:
/tmp/mckernel/kernel/include/process.h:844:5: note: declared here
 int add_process_memory_range(struct process_vm *vm,
     ^
/tmp/mckernel/kernel/syscall.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/syscall.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 30%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1