Update patch set 1
Patch Set 1: Test-x86-1

MCKERNEL : mckernel-refs-changes-97-460297-1-?
IHK      : ihk-refs-changes-97-460297-1-?
GERRIT   : https://review.gerrithub.io/c/RIKEN-SysSoft/mckernel/+/460297/1 // 5fc372eb28deee1be5196a6a8965105f498339ac
MCKERNELCONFIGOPTION : --enable-rusage --with-mpi=/usr/lib64/mpich-3.2 --enable-qlmpi
IHKCONFIGOPTION      : --enable-rusage
MCREBOOTOPTION       : -k 0 -f LOG_LOCAL6  -c 1-7,9-15,17-23,25-31 -m 10G@0,10G@1 -r 1-7:0+9-15:8+17-23:16+25-31:24 -o root -O
HOST  : wallaby7
DIR   : /work/mcktest/work_refs-changes-97-460297-1_submodule
START : 20190703220621
END   : 20190703220638

From https://review.gerrithub.io/RIKEN-SysSoft/mckernel
 * branch            refs/changes/97/460297/1 -> FETCH_HEAD
HEAD is now at 5fc372e pmu: change to atomic register access.
HEAD is now at 9a7bb11 rusage: Move pgsize_to_pgshift to arch-memory.h
MCKBUILD=/work/mcktest/work_refs-changes-97-460297-1_submodule/build
MCKINSTALL=/work/mcktest/work_refs-changes-97-460297-1_submodule/mck
-- The C compiler identification is GNU 4.8.5
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Performing Test IMPLICIT_FALLTHROUGH
-- Performing Test IMPLICIT_FALLTHROUGH - Success
Defined module ihk
Defined module ihk-smp-x86_64
Defined module mcctrl
-------------------------------
Option summary
-------------------------------
Build type: Debug
Build target: smp-x86
IHK_SOURCE_DIR: ../ihk (relative to mckernel source tree)
UNAME_R: 3.10.0-693.2.2.el7.x86_64
KERNEL_DIR: /lib/modules/3.10.0-693.2.2.el7.x86_64/build
SYSTEM_MAP: 
VMLINUX: 
KBUILD_C_FLAGS:  -DIHK_IKC_USE_LINUX_WORK_IRQ
ENABLE_MEMDUMP: ON
ENABLE_PERF: ON
ENABLE_RUSAGE: ON
ENABLE_QLMPI: OFF
ENABLE_UTI: OFF
ENABLE_WERROR: OFF
ENABLE_UBSAN: OFF
ENABLE_LINUX_WORK_IRQ_FOR_IKC: ON
-------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /work/mcktest/work_refs-changes-97-460297-1_submodule/build/3.10.0-693.2.2.el7.x86_64
Scanning dependencies of target eclair
Scanning dependencies of target ldump2mcdump
Scanning dependencies of target ihklib
Scanning dependencies of target libmcexec
[  1%] Scanning dependencies of target ihk_ko
Scanning dependencies of target sched_yield
[  2%] [  4%] Building C object executer/user/CMakeFiles/ldump2mcdump.dir/ldump2mcdump.c.o
[  5%] [  6%] [  8%] [  9%] Building C object executer/user/CMakeFiles/eclair.dir/eclair.c.o
[ 11%] Generating old_timestamp, host_driver.o, mem_alloc.o, mm.o, mikc.o, ../../ikc/linux.o, ../../ikc/master.o, ../../ikc/queue.o, .host_driver.o.cmd, .mem_alloc.o.cmd, .mm.o.cmd, .mikc.o.cmd, ../../ikc/.linux.o.cmd, ../../ikc/.master.o.cmd, ../../ikc/.queue.o.cmd, ihk.o, .ihk.o.cmd, ihk.mod.c, ihk.mod.o, .ihk.mod.o.cmd, .ihk.ko.cmd, .tmp_versions/ihk.mod, .tmp_versions, modules.order
Building ASM object executer/user/CMakeFiles/libmcexec.dir/arch/x86_64/archdep.S.o
Building C object executer/user/CMakeFiles/eclair.dir/arch/x86_64/arch-eclair.c.o
Building C object ihk/linux/user/CMakeFiles/ihklib.dir/ihklib.c.o
Generating kmod_always_rebuild
Building C object executer/user/CMakeFiles/sched_yield.dir/libsched_yield.c.o
[ 12%] Building kmod ihk
Linking ASM static library libmcexec.a
Linking C shared library libsched_yield.so
[ 12%] Scanning dependencies of target mckernel.img
Built target libmcexec
Linking C shared library libldump2mcdump.so
[ 13%] Linking C executable eclair
[ 15%] [ 15%] [ 16%] Building C object kernel/CMakeFiles/mckernel.img.dir/mem.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/init.c.o
Built target sched_yield
[ 18%] Building C object kernel/CMakeFiles/mckernel.img.dir/debug.c.o
[ 18%] Built target ldump2mcdump
Building C object kernel/CMakeFiles/mckernel.img.dir/mikc.c.o
[ 19%] Building C object kernel/CMakeFiles/mckernel.img.dir/listeners.c.o
[ 20%] [ 22%] Building C object kernel/CMakeFiles/mckernel.img.dir/ap.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/syscall.c.o
[ 22%] Built target eclair
[ 23%] [ 25%] Building C object kernel/CMakeFiles/mckernel.img.dir/cls.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/host.c.o
[ 26%] [ 27%] Building C object kernel/CMakeFiles/mckernel.img.dir/process.c.o
[ 29%] Building C object kernel/CMakeFiles/mckernel.img.dir/copy.c.o
[ 30%] Building C object kernel/CMakeFiles/mckernel.img.dir/waitq.c.o
Linking C shared library libihk.so
[ 31%] Building C object kernel/CMakeFiles/mckernel.img.dir/futex.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/timer.c.o
[ 33%] [ 34%] Building C object kernel/CMakeFiles/mckernel.img.dir/plist.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/fileobj.c.o
[ 36%] [ 37%] [ 38%] Building C object kernel/CMakeFiles/mckernel.img.dir/shmobj.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/procfs.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/zeroobj.c.o
[ 40%] [ 40%] Built target ihklib
Building C object kernel/CMakeFiles/mckernel.img.dir/devobj.c.o
[ 41%] [ 43%] [ 44%] Building C object kernel/CMakeFiles/mckernel.img.dir/sysfs.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/xpmem.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/profile.c.o
Scanning dependencies of target ihkconfig
Scanning dependencies of target ihkmond
[ 45%] Scanning dependencies of target ihkosctl
Scanning dependencies of target mcstat
[ 47%] [ 48%] Scanning dependencies of target mcexec
Building C object kernel/CMakeFiles/mckernel.img.dir/freeze.c.o
[ 50%] [ 51%] [ 52%] [ 54%] Building C object ihk/linux/user/CMakeFiles/ihkconfig.dir/ihkconfig.c.o
Building C object ihk/linux/user/CMakeFiles/ihkmond.dir/ihkmond.c.o
[ 55%] [ 56%] Building C object kernel/CMakeFiles/mckernel.img.dir/rbtree.c.o
Building C object tools/mcstat/CMakeFiles/mcstat.dir/mcstat.c.o
Building C object ihk/linux/user/CMakeFiles/ihkosctl.dir/ihkosctl.c.o
Building C object executer/user/CMakeFiles/mcexec.dir/mcexec.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/pager.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/gencore.c.o
[ 58%] Building C object kernel/CMakeFiles/mckernel.img.dir/hugefileobj.c.o
[ 59%] [ 61%] [ 62%] Building C object kernel/CMakeFiles/mckernel.img.dir/llist.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-97-460297-1_submodule/src/ihk/ikc/manycore.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-97-460297-1_submodule/src/ihk/ikc/master.c.o
[ 63%] Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-97-460297-1_submodule/src/ihk/ikc/queue.c.o
[ 66%] [ 65%] [ 68%] [ 69%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/abort.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/bitmap.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/bitops.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/page_alloc.c.o
[ 70%] Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/string.c.o
[ 72%] [ 73%] [ 75%] Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-97-460297-1_submodule/src/ihk/cokernel/smp/ikc.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/lib/vsprintf.c.o
Linking C executable mcstat
Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-97-460297-1_submodule/src/ihk/cokernel/smp/x86_64/dma.c.o
[ 76%] [ 77%] Building C object kernel/CMakeFiles/mckernel.img.dir/work/mcktest/work_refs-changes-97-460297-1_submodule/src/ihk/cokernel/smp/x86_64/setup.c.o
[ 79%] Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/context.S.o
[ 80%] [ 81%] Linking C executable ihkconfig
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/coredump.c.o
Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/interrupt.S.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/cpu.c.o
[ 83%] [ 84%] [ 86%] [ 86%] Built target mcstat
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/local.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/mikc.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/memory.c.o
[ 87%] [ 88%] Linking C executable ihkosctl
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/perfctr.c.o
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/syscall.c.o
[ 90%] [ 88%] [ 91%] Built target ihkconfig
Building ASM object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/trampoline.S.o
Linking C executable ihkmond
Building C object kernel/CMakeFiles/mckernel.img.dir/__/arch/x86_64/kernel/vsyscall.c.o
[ 91%] Built target ihkosctl
[ 91%] Built target ihkmond
Linking C executable mcexec
[ 91%] Built target mcexec
[ 91%] Built target ihk_ko
Scanning dependencies of target ihk-smp-x86_64_ko
Scanning dependencies of target mcctrl_ko
[ 93%] [ 94%] Generating kmod_always_rebuild
Generating old_timestamp, arch/x86_64/smp-x86_64-startup.o, arch/x86_64/smp-x86_64-trampoline.o, arch/x86_64/smp-arch-driver.o, smp-driver.o, arch/x86_64/.smp-x86_64-startup.o.cmd, arch/x86_64/.smp-x86_64-trampoline.o.cmd, arch/x86_64/.smp-arch-driver.o.cmd, .smp-driver.o.cmd, ihk-smp-x86_64.o, .ihk-smp-x86_64.o.cmd, ihk-smp-x86_64.mod.c, ihk-smp-x86_64.mod.o, .ihk-smp-x86_64.mod.o.cmd, .ihk-smp-x86_64.ko.cmd, .tmp_versions/ihk-smp-x86_64.mod, .tmp_versions, modules.order
[ 95%] [ 97%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, arch/x86_64/archdeps.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, arch/x86_64/.archdeps.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
Generating kmod_always_rebuild
[ 98%] [100%] Building kmod ihk-smp-x86_64
Building kmod mcctrl
/work/mcktest/work_refs-changes-97-460297-1_submodule/build/3.10.0-693.2.2.el7.x86_64/ihk/linux/driver/smp/arch/x86_64/smp-x86_64-startup.o: warning: objtool: .text+0x7: can't find jump dest instruction at .text+0x38
Linking C executable mckernel.img
CMakeFiles/mckernel.img.dir/syscall.c.o: In function `mc_perf_event_alloc':
/work/mcktest/work_refs-changes-97-460297-1_submodule/src/mckernel/kernel/syscall.c:4097: undefined reference to `ihk_mc_raw_event_map'
make[2]: *** [kernel/mckernel.img] Error 1
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target mcctrl_ko
[100%] Built target ihk-smp-x86_64_ko
make: *** [all] Error 2
ERROR: autobuild.sh failed

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Test-x86=-1