Update patch set 1
Patch Set 1: Verified-1

setns_dummy_uts: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  5%] Built target ihklib
[  8%] Built target ihkmond
[ 10%] Built target ihkconfig
[ 12%] Built target ihkosctl
[ 14%] Generating kmod_always_rebuild
[ 15%] Building kmod ihk-smp-x86_64
[ 16%] Built target ihk-smp-x86_64_ko
[ 17%] Generating kmod_always_rebuild
[ 18%] Building kmod mcctrl
[ 20%] Built target mcctrl_ko
[ 22%] Built target libmcexec
[ 24%] Built target mcexec
[ 27%] Built target mcinspect
[ 29%] Built target sched_yield
[ 31%] Built target ldump2mcdump
[ 35%] Built target eclair
[ 36%] Building C object kernel/CMakeFiles/mckernel.img.dir/syscall.c.o
In file included from /work/mcktest/git/mckernel/lib/include/ihk/mm.h:23:0,
                 from /work/mcktest/git/mckernel/kernel/syscall.c:30:
/work/mcktest/git/mckernel/kernel/syscall.c: In function ‘do_mmap’:
/work/mcktest/git/mckernel/lib/include/ihk/debug.h:46:39: error: ‘error’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 #define ekprintf(fmt, args...) kprintf(fmt, ##args)
                                       ^
/work/mcktest/git/mckernel/kernel/syscall.c:1820:6: note: ‘error’ was declared here
  int error;
      ^
/work/mcktest/git/mckernel/kernel/syscall.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [kernel/CMakeFiles/mckernel.img.dir/syscall.c.o] Error 1
make[2]: Target `kernel/CMakeFiles/mckernel.img.dir/build' not remade because of errors.
make[1]: *** [kernel/CMakeFiles/mckernel.img.dir/all] Error 2
[ 38%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 1
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Verified=-1