Update patch set 3
Patch Set 3: Build-arm64-1

apollo15: build report: build failed:
[  1%] Generating kmod_always_rebuild
[  2%] Building kmod ihk
[  3%] Built target ihk_ko
[  4%] Built target ihklib
[  5%] Built target ihkconfig
[  6%] Built target ihkmond
[  7%] Built target ihkosctl
[  8%] Generating kmod_always_rebuild
[  9%] Building kmod ihk-smp-arm64
[ 10%] Built target ihk-smp-arm64_ko
[ 11%] Generating old_timestamp, driver.o, control.o, ikc.o, syscall.o, procfs.o, binfmt_mcexec.o, sysfs.o, sysfs_files.o, mc_plist.o, futex.o, arch/arm64/archdeps.o, arch/arm64/cpu.o, .driver.o.cmd, .control.o.cmd, .ikc.o.cmd, .syscall.o.cmd, .procfs.o.cmd, .binfmt_mcexec.o.cmd, .sysfs.o.cmd, .sysfs_files.o.cmd, .mc_plist.o.cmd, .futex.o.cmd, arch/arm64/.archdeps.o.cmd, arch/arm64/.cpu.o.cmd, mcctrl.o, .mcctrl.o.cmd, mcctrl.mod.c, mcctrl.mod.o, .mcctrl.mod.o.cmd, .mcctrl.ko.cmd, .tmp_versions/mcctrl.mod, .tmp_versions, modules.order
[ 12%] Building kmod mcctrl
In file included from /tmp/mckernel/executer/kernel/mcctrl/futex.c:31:0:
/tmp/mckernel/arch/arm64/kernel/include/arch-futex.h: In function ‘futex_atomic_op_inuser’:
/tmp/mckernel/arch/arm64/kernel/include/arch-futex.h:40:2: error: expected ‘;’ before ‘uaccess_disable’
  uaccess_disable();     \
  ^
/tmp/mckernel/arch/arm64/kernel/include/arch-futex.h:74:3: note: in expansion of macro ‘__futex_atomic_op’
   __futex_atomic_op("mov %w0, %w4",
   ^
/tmp/mckernel/arch/arm64/kernel/include/arch-futex.h:40:2: error: expected ‘;’ before ‘uaccess_disable’
  uaccess_disable();     \
  ^
/tmp/mckernel/arch/arm64/kernel/include/arch-futex.h:78:3: note: in expansion of macro ‘__futex_atomic_op’
   __futex_atomic_op("add %w0, %w1, %w4",
   ^
/tmp/mckernel/arch/arm64/kernel/include/arch-futex.h:40:2: error: expected ‘;’ before ‘uaccess_disable’
  uaccess_disable();     \
  ^
/tmp/mckernel/arch/arm64/kernel/include/arch-futex.h:82:3: note: in expansion of macro ‘__futex_atomic_op’
   __futex_atomic_op("orr %w0, %w1, %w4",
   ^
/tmp/mckernel/arch/arm64/kernel/include/arch-futex.h:40:2: error: expected ‘;’ before ‘uaccess_disable’
  uaccess_disable();     \
  ^
/tmp/mckernel/arch/arm64/kernel/include/arch-futex.h:86:3: note: in expansion of macro ‘__futex_atomic_op’
   __futex_atomic_op("and %w0, %w1, %w4",
   ^
/tmp/mckernel/arch/arm64/kernel/include/arch-futex.h:40:2: error: expected ‘;’ before ‘uaccess_disable’
  uaccess_disable();     \
  ^
/tmp/mckernel/arch/arm64/kernel/include/arch-futex.h:90:3: note: in expansion of macro ‘__futex_atomic_op’
   __futex_atomic_op("eor %w0, %w1, %w4",
   ^
make[4]: *** [/tmp/build-mckernel/executer/kernel/mcctrl/futex.o] Error 1
make[4]: Target `__build' not remade because of errors.
make[3]: *** [_module_/tmp/build-mckernel/executer/kernel/mcctrl] Error 2
make[3]: Target `modules' not remade because of errors.
make[2]: *** [executer/kernel/mcctrl/mcctrl.ko] Error 2
make[2]: Target `executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/build' not remade because of errors.
make[1]: *** [executer/kernel/mcctrl/CMakeFiles/mcctrl_ko.dir/all] Error 2
[ 14%] Built target eclair
[ 15%] Built target ldump2mcdump
[ 16%] Built target libmcexec
[ 17%] Built target mcexec
[ 18%] Built target mcinspect
[ 19%] Built target sched_yield
[ 97%] Built target mckernel.img
[ 98%] Built target mcstat
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
make: Target `install' not remade because of errors.

Patch-set: 3
Reviewer: Gerrit User 1014954 <1014954@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Build-arm64=-1